packages/agents/sdk/src/sdkBase.ts
packages/deployments/contracts/README.md
packages/deployments/contracts/deployments/arbitrum-one/Unwrapper.json
packages/deployments/contracts/deployments/bnb/Unwrapper.json
packages/deployments/contracts/deployments/mainnet/Unwrapper.json
packages/deployments/contracts/deployments/matic/Unwrapper.json
packages/deployments/contracts/deployments/optimism/Unwrapper.json
packages/deployments/contracts/deployments/xdai/Unwrapper.json

2642 deploy unwrapper

---

packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts
packages/deployments/contracts/src/cli/init/init.ts
yarn.lock

Fix propagate and init

---

CHANGELOG.md
packages/agents/sdk/src/config.ts
packages/agents/sdk/src/interfaces/index.ts
packages/agents/sdk/src/sdk.ts
packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/test/sdkPool.spec.ts
packages/examples/sdk-server/src/index.ts

3219 checksums

---

packages/agents/sdk/src/config.ts
packages/agents/sdk/src/index.ts
packages/agents/sdk/src/sdk.ts
packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/src/sdkRouter.ts
packages/agents/sdk/src/sdkShared.ts
packages/agents/sdk/src/sdkUtils.ts
packages/agents/sdk/test/mock.ts
packages/agents/sdk/test/sdk.spec.ts
packages/agents/sdk/test/sdkBase.spec.ts
packages/agents/sdk/test/sdkPool.spec.ts
packages/agents/sdk/test/sdkRouter.spec.ts
packages/agents/sdk/test/sdkShared.spec.ts
packages/agents/sdk/test/sdkUtils.spec.ts
packages/examples/bridge-reference/src/components/Header.tsx
packages/examples/bridge-reference/src/components/Pool.tsx
packages/examples/bridge-reference/src/components/TransferButton.tsx
packages/examples/bridge-reference/src/contexts/Sdk.tsx
packages/examples/sdk-server/src/base.ts
packages/examples/sdk-server/src/index.ts
packages/examples/sdk-server/src/pool.ts
packages/examples/sdk-server/src/router.ts
packages/examples/sdk-server/src/utils.ts
packages/integration/test/local.spec.ts

Finish removing nxtp from sdk class names

---

packages/agents/sdk/src/sdkUtils.ts
packages/agents/sdk/test/sdkUtils.spec.ts
packages/examples/sdk-server/src/types/api.ts

3223 search by xcall caller

---

packages/adapters/cache/src/lib/caches/auctions.ts
packages/agents/sequencer/src/config.ts
packages/agents/sequencer/src/lib/entities/config.ts
packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
packages/agents/sequencer/test/lib/operations/execute/fastpath.spec.ts
packages/agents/sequencer/test/mock.ts
packages/integration/test/constants/testnet/index.ts
packages/utils/src/types/auctions.ts

Handle router retries more gracefully
Fixes

3182 sequencer retries acting buggy

---

packages/agents/router/src/config.ts
packages/agents/router/src/setup.ts
packages/agents/router/src/tasks/publisher/publisher.ts
packages/agents/router/src/tasks/subscriber/subscriber.ts
packages/utils/src/types/primitives.ts

Limit router subscriber message concurrency
Fixes 
https://github.com/connext/monorepo/issues/3210

Limit router subscriber message concurrency

---

packages/agents/sdk/src/sdkUtils.ts

Fix xcall caller

---

docker/cartographer/Dockerfile
docker/lighthouse/Dockerfile
ops/testnet/prod/backend/config.tf
ops/testnet/prod/core/config.tf
ops/testnet/staging/backend/config.tf
ops/testnet/staging/core/config.tf
packages/agents/cartographer/poller/package.json
packages/agents/lighthouse/package.json
yarn.lock

remove dd trace reqs

---

packages/adapters/cache/src/lib/caches/transfers.ts
packages/adapters/cache/test/lib/caches/transfers.spec.ts
packages/agents/router/src/tasks/publisher/operations/retryXCalls.ts
packages/utils/src/types/xtransfers.ts

Fix https://github.com/connext/monorepo/issues/3211
Fixes 
https://github.com/connext/monorepo/issues/3211

3211 router retry should exponentially backoff

---

ops/mainnet/prod/core/config.tf

Datadog errors indicate issues originate with 1rpc. Remove this from watcher config.
Fixes #3288 
Fixes

fix: remove problematic rpc

---

packages/agents/cartographer/api/example.http
packages/agents/sdk/src/interfaces/index.ts
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/src/sdkShared.ts
packages/agents/sdk/src/sdkUtils.ts
packages/agents/sdk/test/mock.ts
packages/agents/sdk/test/sdkPool.spec.ts
packages/agents/sdk/test/sdkShared.spec.ts
packages/examples/sdk-server/examples/index.http
packages/examples/sdk-server/src/index.ts
packages/examples/sdk-server/src/pool.ts
packages/examples/sdk-server/src/types/api.ts
packages/utils/src/mocks/mock.ts
packages/utils/src/peripherals/chainData.ts

3276 carto pools

---

packages/agents/sdk/src/sdkShared.ts

fix: getSupported

---

ops/mainnet/prod/core/config.tf

Reduce to 15 sec wait time

---

packages/agents/sdk/src/sdkPool.ts
packages/utils/src/mocks/mock.ts

Fixes `getPool` due to checksum mismatches.

Sdk checksum fixes

---

packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/test/sdkPool.spec.ts

Sdk hot fixes

---

packages/agents/sequencer/src/lib/operations/tasks.ts

Fix: #3336

---

packages/agents/sdk/package.json
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/src/sdkShared.ts
packages/agents/sdk/test/sdkUtils.spec.ts

Memoize cartogapher calls that don't need fresh data on UI.
Fixes

Sdk memoize calls

---

ops/mainnet/prod/core/config.tf
ops/testnet/prod/core/config.tf
ops/testnet/staging/core/config.tf
packages/agents/router/src/tasks/publisher/operations/getXCalls.ts
packages/integration/test/constants/testnet/index.ts
packages/utils/src/types/primitives.ts

hot fix for Asset config

---

packages/deployments/subgraph/src/amarok-runtime-v0/mapping/transfers.ts

fix: relayer fee calc at subgraph

---

packages/agents/sequencer/src/bindings/subscriber/auctions/index.ts

Update seq fastpath status on reject.
Fixes 
https://github.com/connext/monorepo/issues/3362

Update seq fastpath status on reject.

---

packages/adapters/relayer/src/index.ts
packages/agents/router/src/tasks/executor/operations/sequencer.ts
packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
packages/agents/sequencer/src/sequencer.ts

Fix slippage check on sequencer

---

packages/agents/sequencer/src/bindings/subscriber/auctions/index.ts

Reset sequencer fastpath status on executor exiting the process in error
Fixes

Reset sequencer fastpath status on error

---

packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/test/sdkPool.spec.ts
packages/examples/sdk-server/examples/index.http
packages/examples/sdk-server/src/pool.ts
packages/examples/sdk-server/src/types/api.ts

3359 yield data days

---

packages/adapters/subgraph/src/lib/helpers/parse.ts

fix: default `relayerFee` to 0 if `null`

---

packages/adapters/txservice/src/shared/errors.ts

Identify error name given sighash using connext iface when parsing

---

ops/testnet/prod/core/config.tf
ops/testnet/staging/core/config.tf

fix: remove faulty rpc

---

packages/adapters/web3signer/api.ts
packages/agents/router/src/errors/index.ts
packages/agents/router/src/errors/reverts.ts
packages/agents/router/src/tasks/executor/operations/sequencer.ts
yarn.lock

3385 better logs

---

packages/agents/lighthouse/src/errors/index.ts
packages/agents/lighthouse/src/errors/processor.ts
packages/agents/lighthouse/src/tasks/processFromRoot/helpers/arbitrum.ts
packages/agents/lighthouse/test/tasks/processFromRoot/helpers/arbitrum.spec.ts

fix: handle case where no logs are found

---

packages/adapters/database/src/client.ts
packages/adapters/database/test/client.spec.ts

3412 transfer errors should be cleared after execute
Fixes

3412 transfer errors should be cleared after execute

---

packages/deployments/subgraph/src/amarok-runtime-v0/mapping/transfers.ts

Fix bump transfer subgraph handler

---

packages/adapters/txservice/src/chainreader.ts
packages/adapters/txservice/src/shared/types.ts
packages/adapters/txservice/test/chainreader.spec.ts
packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/src/sdkShared.ts

`multiread` method enables doing multiple read calls with 1 RPC call, increasing RPC consumption efficiency
Fixes

Add `multiread` method to ChainReader

---

ops/mainnet/prod/core/config.tf
ops/testnet/prod/core/config.tf

Whitelist for bypass relayer fees

---

packages/adapters/relayer/src/index.ts

Check error context message

---

packages/adapters/database/src/client.ts
packages/adapters/database/test/client.spec.ts

Set max limit on backoff in sequencer to a week.
Fixes

Set max limit on backoff

---

packages/deployments/subgraph/src/amarok-runtime-v0/mapping/transfers.ts
packages/deployments/subgraph/src/amarok-runtime-v0/schema.graphql

Graph update

---

packages/deployments/subgraph/src/amarok-runtime-v0/mapping/transfers.ts

fix: slippage issue.

---

packages/agents/sdk/src/sdkBase.ts

Related to #3480 
- Throws if trying to update slippage and not on destination chain
- Throws if trying to update slippage and you are *not* the delegate
Fixes

fix: throw if invalid domain or signer

---

packages/agents/sdk/src/sdkUtils.ts
packages/agents/sdk/test/sdkUtils.spec.ts
packages/examples/sdk-server/examples/index.http
packages/examples/sdk-server/src/types/api.ts

Add errorStatus to getTransfers query params

---

packages/agents/sdk/src/interfaces/index.ts
packages/agents/sdk/test/sdkBase.spec.ts
packages/examples/sdk-server/examples/index.http
packages/examples/sdk-server/src/base.ts

Update slippage tests

---

packages/utils/src/peripherals/relayer.ts
packages/utils/test/peripherals/relayer.spec.ts

Add l1 cost to gas estimation on optimism

---

packages/agents/cartographer/poller/src/lib/operations/transfers.ts

Update transfers with relayer fee updates

---

packages/deployments/contracts/tasks/renounceOwnership.ts

fix: hardhat task to renounce ownership for router only

---

packages/utils/src/helpers/axios.ts

Increase retry count to aid heartbeats.
Fixes

Increase retry count to aid heartbeats.

---

packages/agents/lighthouse/src/tasks/processFromRoot/processFromRoot.ts
packages/utils/src/helpers/health.ts

Staging sync for better logging

---

packages/adapters/database/src/client.ts
packages/adapters/database/test/client.spec.ts

Fix receiveLocal on carto transfers table

---

packages/adapters/database/src/client.ts
packages/adapters/database/test/client.spec.ts

Revert "Fix receiveLocal on carto transfers table"

---

packages/adapters/database/src/client.ts
packages/adapters/database/test/client.spec.ts

Fix #3587 : upsert receive_local
Fixes

Fix #3587 : upsert receive_local

---

packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts

Improve proveAndProcess

---

packages/adapters/subgraph/src/lib/helpers/parse.ts
packages/adapters/subgraph/src/lib/operations/queries.ts
packages/adapters/subgraph/test/lib/helpers/parse.spec.ts
packages/deployments/subgraph/src/amarok-runtime-staging/mapping/transfers.ts
packages/deployments/subgraph/src/amarok-runtime-staging/schema.graphql
packages/deployments/subgraph/src/amarok-runtime-v0/mapping/transfers.ts
packages/deployments/subgraph/src/amarok-runtime-v0/schema.graphql

3444 nextUSDC explorer issue

---

packages/deployments/contracts/package.json
packages/deployments/contracts/src/cli/helpers.ts
packages/deployments/contracts/src/cli/init/helpers/deployments.ts
packages/deployments/contracts/src/cli/ownership/helpers/constants.ts
packages/deployments/contracts/src/cli/ownership/helpers/deployments.ts
packages/deployments/contracts/src/cli/ownership/helpers/index.ts
packages/deployments/contracts/src/cli/ownership/helpers/types.ts
packages/deployments/contracts/src/cli/ownership/main.ts
packages/deployments/contracts/src/cli/ownership/transferOwnership.ts
packages/deployments/contracts/src/utils.ts

Ownership utils

---

.github/workflows/build-test-deploy.yml
packages/agents/sdk/src/interfaces/index.ts
packages/agents/sdk/src/sdkUtils.ts
packages/agents/sdk/test/sdkUtils.spec.ts
packages/examples/sdk-server/examples/index.http
packages/examples/sdk-server/src/types/api.ts
packages/examples/sdk-server/src/utils.ts

3585 fast liquidity

---

CHANGELOG.md
package.json
packages/adapters/cache/package.json
packages/adapters/database/package.json
packages/adapters/relayer/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/adapters/watcher/package.json
packages/adapters/web3signer/package.json
packages/agents/cartographer/poller/package.json
packages/agents/lighthouse/package.json
packages/agents/relayer/package.json
packages/agents/router/package.json
packages/agents/sdk/package.json
packages/agents/sequencer/package.json
packages/agents/watcher/package.json
packages/deployments/contracts/package.json
packages/deployments/subgraph/package.json
packages/integration/package.json
packages/utils/package.json

Changelog for v0.2.7 release.
Fixes

Changelog for 0.2.7

---

.github/workflows/build-test-deploy.yml

No tag flag for non-alpha/beta versions

---

packages/adapters/database/db/migrations/20230227071659_simulate_excecute_transfer.sql
packages/adapters/database/db/schema.sql
packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/src/zapatos/schema.d.ts
packages/adapters/database/test/mock.ts
packages/agents/sequencer/src/lib/operations/relayer/fastpath.ts
packages/agents/sequencer/src/lib/operations/relayer/slowpath.ts
packages/agents/sequencer/test/mock.ts

Execute simulation/ Debugging tooling for execute at explorer

---

packages/utils/src/peripherals/relayer.ts

Hotfix of fallback calculation for relayerFee

---

packages/agents/cartographer/poller/src/lib/operations/transfers.ts

Process relayer fee increases
Fixes

Process fee increases

---

packages/deployments/contracts/contracts/core/connext/interfaces/IConnext.sol

Iface func sigs should match facets

---

packages/agents/lighthouse/src/tasks/sendOutboundRoot/operations/sendOutboundRoot.ts

check outboundRoot is sent

---

packages/utils/src/peripherals/chainData.ts

Fetch chaindata from CDN

---

packages/agents/lighthouse/src/tasks/processFromRoot/helpers/zksync.ts
packages/agents/lighthouse/test/tasks/processFromRoot/helpers/zksync.spec.ts
packages/deployments/subgraph/config/amarok-runtime-v0.json

3694 fix zksync processfromroot

---

packages/agents/lighthouse/src/tasks/processFromRoot/helpers/zksync.ts

Fix Zksync process from root

---

packages/utils/src/peripherals/gelato.ts
packages/utils/src/peripherals/relayer.ts
packages/utils/test/peripherals/gelato.spec.ts
packages/utils/test/peripherals/relayer.spec.ts

Update gas estimation on optimism

---

packages/adapters/database/src/client.ts
packages/adapters/database/test/client.spec.ts

Set past roots to processed.
Fixes

Fix processed state of past roots from same domain

---

packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/test/sdkBase.spec.ts
packages/agents/sdk/test/sdkPool.spec.ts

Sdk backwardcompatible update

---

packages/utils/src/peripherals/chainData.ts

Move to CDN chaindata

---

packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/src/sdkShared.ts

Active liquidity optimisation

---

packages/agents/lighthouse/src/tasks/processFromRoot/errors.ts
packages/agents/lighthouse/src/tasks/processFromRoot/helpers/polygon.ts
packages/agents/lighthouse/test/tasks/processFromRoot/helpers/polygon.spec.ts
packages/deployments/contracts/src/config.ts
packages/deployments/contracts/src/utils.ts
packages/deployments/contracts/tasks/submitExitProof.ts
packages/utils/.nycrc.json
packages/utils/src/maticjs/proof.ts
packages/utils/test/maticjs/proof.spec.ts

3727 lh processfromroot error on polygon

---

.github/workflows/build-test-deploy.yml
CHANGELOG.md
package.json
packages/adapters/cache/package.json
packages/adapters/database/package.json
packages/adapters/relayer/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/adapters/watcher/package.json
packages/adapters/web3signer/package.json
packages/agents/cartographer/poller/package.json
packages/agents/lighthouse/package.json
packages/agents/relayer/package.json
packages/agents/router/package.json
packages/agents/sdk/package.json
packages/agents/sequencer/package.json
packages/agents/watcher/package.json
packages/deployments/contracts/package.json
packages/deployments/subgraph/package.json
packages/integration/package.json
packages/utils/package.json

Stable release

---

ops/env/mainnet/core/secrets.prod.json
ops/env/testnet/core/secrets.prod.json
ops/mainnet/prod/core/config.tf
ops/mainnet/prod/core/variables.tf
ops/testnet/prod/core/config.tf
ops/testnet/prod/core/variables.tf

Heartbeats for LH SendOutboundRoot
Fixes

Heartbeats for LH SendOutboundRoot

---

packages/agents/lighthouse/src/tasks/processFromRoot/errors.ts
packages/agents/lighthouse/src/tasks/processFromRoot/helpers/arbitrum.ts
packages/agents/lighthouse/test/tasks/processFromRoot/helpers/arbitrum.spec.ts

3747 lh arbitrum processfromroot reverted with staked on chain

---

CHANGELOG.md
packages/adapters/cache/package.json
packages/adapters/database/package.json
packages/adapters/relayer/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/adapters/watcher/package.json
packages/adapters/web3signer/package.json
packages/agents/cartographer/poller/package.json
packages/agents/lighthouse/package.json
packages/agents/relayer/package.json
packages/agents/router/package.json
packages/agents/sdk/package.json
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/test/sdkShared.spec.ts
packages/agents/sequencer/package.json
packages/agents/watcher/package.json
packages/deployments/contracts/package.json
packages/deployments/subgraph/package.json
packages/examples/bridge-reference/package.json
packages/integration/package.json
packages/utils/package.json

Calculate amt optimizations

---

CHANGELOG.md
package.json
packages/adapters/cache/package.json
packages/adapters/database/package.json
packages/adapters/relayer/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/adapters/watcher/package.json
packages/adapters/web3signer/package.json
packages/agents/cartographer/poller/package.json
packages/agents/lighthouse/package.json
packages/agents/relayer/package.json
packages/agents/router/package.json
packages/agents/sdk/package.json
packages/agents/sdk/src/sdkPool.ts
packages/agents/sequencer/package.json
packages/agents/watcher/package.json
packages/deployments/contracts/package.json
packages/deployments/contracts/tasks/submitExitProof.ts
packages/deployments/subgraph/package.json
packages/examples/bridge-reference/package.json
packages/integration/package.json
packages/utils/package.json

v1.0.2-alpha.0

---

packages/adapters/relayer/src/index.ts

skip relayer if it will be reverted on chain

---

packages/agents/sdk/src/sdkPool.ts

default fastpath true

---

packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
packages/agents/sequencer/src/sequencer.ts

Fix error status

---

packages/utils/src/peripherals/relayer.ts

Incorrect use of domain vs chainId

---

packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/test/sdkBase.spec.ts
packages/examples/sdk-server/examples/index.http

Fix bumpTransfer in native asset

---

CHANGELOG.md
ops/testnet/staging/core/config.tf
package.json
packages/adapters/cache/package.json
packages/adapters/database/package.json
packages/adapters/relayer/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/adapters/watcher/package.json
packages/adapters/web3signer/package.json
packages/agents/cartographer/poller/package.json
packages/agents/lighthouse/package.json
packages/agents/relayer/package.json
packages/agents/router/package.json
packages/agents/sdk/package.json
packages/agents/sequencer/package.json
packages/agents/watcher/package.json
packages/deployments/contracts/package.json
packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
packages/deployments/contracts/src/cli/init/helpers/tx.ts
packages/deployments/subgraph/package.json
packages/integration/package.json
packages/utils/package.json

v1.2.0-alpha.1

---

packages/agents/lighthouse/src/mockable.ts
packages/agents/lighthouse/src/tasks/propagate/helpers/arbitrum.ts
packages/agents/lighthouse/src/tasks/propagate/helpers/bnb.ts
packages/agents/lighthouse/src/tasks/propagate/helpers/gnosis.ts
packages/agents/lighthouse/src/tasks/propagate/helpers/zksync.ts
packages/agents/lighthouse/src/tasks/sendOutboundRoot/helpers/bnb.ts
packages/agents/lighthouse/src/tasks/sendOutboundRoot/operations/sendOutboundRoot.ts
packages/agents/lighthouse/test/globalTestHook.ts
packages/agents/lighthouse/test/tasks/propagate/helpers/arbitrum.spec.ts
packages/agents/lighthouse/test/tasks/propagate/helpers/bnb.spec.ts
packages/agents/lighthouse/test/tasks/propagate/helpers/gnosis.spec.ts
packages/agents/lighthouse/test/tasks/propagate/helpers/zksync.spec.ts
packages/examples/sdk-server/src/index.ts
packages/utils/src/ethers/shared.ts

Choose a working RPC URL with lowest latency

---

README.md

Benign update

---

ops/mainnet/prod/backend/main.tf
ops/mainnet/prod/core/main.tf
ops/modules/lambda/main.tf
ops/modules/lambda/variables.tf
ops/testnet/prod/backend/main.tf
ops/testnet/prod/core/main.tf
ops/testnet/staging/backend/main.tf
ops/testnet/staging/core/main.tf

Set maximum memory limits for each lambda independently.
Based on the past 4 weeks data, gathered from: https://p.datadoghq.com/sb/b4775c4e-dd8c-11ec-affd-da7ad0900002-21df99cc0fcf8c8c3b08b43df8a283e7
Fixes

set correct memory limits

---

packages/adapters/txservice/src/aggregator.ts
packages/adapters/txservice/src/dispatch.ts

3888 zksync testnet txs failing from our relayer

---

packages/agents/sdk/src/sdkShared.ts
packages/agents/sdk/test/sdkShared.spec.ts

3793 expose chain to domain mapping utils in sdk

---

packages/agents/sdk/src/sdkShared.ts
packages/agents/sdk/test/sdkShared.spec.ts

Add function to get assets with same canonical sdk

---

packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts
packages/agents/lighthouse/test/tasks/propagate/operations/propagate.spec.ts

check if propagate workable before send

---

packages/agents/lighthouse/src/tasks/propagate/helpers/zksync.ts
packages/agents/lighthouse/test/tasks/propagate/helpers/zksync.spec.ts

3897 zksynchubconnector send not working

---

.github/workflows/build-test-deploy.yml
package.json

Workflow fixes

---

packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json

Stable release SDK v2.0.0

---

.github/workflows/build-test-deploy.yml
packages/agents/router/example.http
packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
packages/deployments/contracts/src/cli/init/init.ts

* chore: config
* Whitelist router
* Fix prod jobs
---------
Fixes

Staging sync (#3944)

---

.github/workflows/build-test-deploy.yml
ops/mainnet/prod/core/main.tf
packages/agents/router/example.http
packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
packages/deployments/contracts/src/cli/init/init.ts

Testnet prod

---

packages/agents/sequencer/src/lib/helpers/relayerfee.ts
packages/agents/sequencer/test/lib/helpers/relayerfee.spec.ts

USD value of fee

---

packages/agents/sdk/package.json
packages/utils/package.json
packages/utils/src/peripherals/gelato.ts

* fix: update endpoint composition
* Update versions
---------
Fixes

Testnet sync (#3955)

---

.github/workflows/build-test-deploy.yml
packages/agents/sdk/package.json
packages/utils/package.json
packages/utils/src/peripherals/gelato.ts

Testnet prod sync

---

ops/mainnet/prod/backend/main.tf
ops/testnet/prod/backend/main.tf
ops/testnet/staging/backend/main.tf

fix: lambda schedule expression

---

ops/mainnet/prod/core/config.tf
packages/deployments/contracts/src/utils.ts
packages/deployments/contracts/tasks/connector/processFromRoot.ts
packages/utils/package.json
yarn.lock

Matic updates

---

README.md
packages/agents/cartographer/poller/README.md
packages/agents/lighthouse/README.md
packages/agents/relayer/README.md
packages/agents/router/README.md
packages/agents/sequencer/README.md
packages/agents/watcher/README.md

Changes for the latest documentation for setting up the repository 
Fixes #3977

fix: upgraded docs to latest

---

packages/adapters/database/src/client.ts
packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts

Mark old root messages based on leaf count

---

README.md
packages/adapters/database/src/client.ts
packages/agents/cartographer/poller/README.md
packages/agents/lighthouse/README.md
packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts
packages/agents/relayer/README.md
packages/agents/router/README.md
packages/agents/sequencer/README.md
packages/agents/watcher/README.md

Testnet sync

---

README.md
packages/adapters/database/src/client.ts
packages/agents/cartographer/poller/README.md
packages/agents/lighthouse/README.md
packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts
packages/agents/relayer/README.md
packages/agents/router/README.md
packages/agents/sequencer/README.md
packages/agents/watcher/README.md

* fix: upgraded docs to latest (#3980)
* fix: upgraded docs to latest
* fix: added requested changes
---------
* feat: mark based on leaf count (#3989)
---------
Fixes

Testnet sync (#3990)

---

packages/adapters/database/db/schema.sql
packages/adapters/subgraph/src/lib/operations/queries.ts
packages/adapters/subgraph/src/reader.ts
packages/adapters/subgraph/test/mock.ts
packages/adapters/subgraph/test/reader.spec.ts
packages/agents/cartographer/poller/src/lib/operations/transfers.ts
packages/agents/cartographer/poller/test/lib/operations/transfers.spec.ts
packages/agents/cartographer/poller/test/mock.ts

Query destination by executed timestamp

---

packages/agents/sdk/src/sdkPool.ts
packages/examples/sdk-server/package.json
packages/examples/sdk-server/src/base.ts

Fix SDK pool

---

packages/agents/sdk/src/sdkPool.ts

4072 calculate swap decimal issue on bnb chain

---

packages/utils/src/helpers/signatures.ts

3857 Generate EIP712 signature

---

packages/utils/src/peripherals/errors.ts
packages/utils/src/peripherals/gelato.ts
packages/utils/src/peripherals/index.ts
packages/utils/test/peripherals/gelato.spec.ts

Gelato api errors

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/mock.ts
packages/agents/cartographer/poller/src/lib/operations/messages.ts
packages/agents/cartographer/poller/test/lib/operations/messages.spec.ts

Fix marking messages processed

---

packages/agents/sdk/src/sdkPool.ts

fix: reading symbol and naming of assets

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/database/test/mock.ts
packages/agents/cartographer/poller/src/lib/operations/messages.ts
packages/agents/cartographer/poller/src/lib/operations/transfers.ts
packages/agents/cartographer/poller/test/lib/operations/transfers.spec.ts

Fix carto transfers/messages loop

---

ops/infra/main.tf
ops/mainnet/prod/backend/main.tf
ops/testnet/prod/backend/main.tf
ops/testnet/staging/backend/main.tf

config fixes for docker image and db size

---

packages/agents/cartographer/poller/src/lib/operations/transfers.ts
packages/agents/cartographer/poller/test/lib/operations/transfers.spec.ts

Update pending transfers sync

---

packages/adapters/subgraph/src/lib/operations/queries.ts

fix: use execute timestamp not reconcile timestamp

---

packages/agents/chain-abstraction/src/libs/shared/quote.ts
packages/agents/chain-abstraction/test/libs/shared/quote.spec.ts

Fix quote function

---

packages/agents/chain-abstraction/src/libs/shared/quote.ts
packages/agents/chain-abstraction/test/helpers/swapquote.spec.ts
packages/agents/chain-abstraction/test/libs/shared/address.spec.ts
packages/agents/chain-abstraction/test/libs/shared/quote.spec.ts

Fix chain-abstraction sdk

---

packages/agents/sequencer/src/lib/helpers/relayerfee.ts
packages/agents/sequencer/test/lib/helpers/relayerfee.spec.ts

4140 hotfix

---

packages/agents/sequencer/src/lib/helpers/relayerfee.ts
packages/agents/sequencer/src/mockable.ts
packages/agents/sequencer/test/lib/helpers/relayerfee.spec.ts
packages/utils/src/peripherals/gelato.ts
packages/utils/src/peripherals/relayer.ts
packages/utils/test/peripherals/gelato.spec.ts

Add safe gelato calls

---

packages/agents/sequencer/src/lib/helpers/relayerfee.ts
packages/agents/sequencer/src/mockable.ts
packages/agents/sequencer/test/lib/helpers/relayerfee.spec.ts
packages/utils/src/peripherals/gelato.ts
packages/utils/src/peripherals/relayer.ts
packages/utils/test/peripherals/gelato.spec.ts

Cherry pick fixes from #4167 (too large to safely merge atm) to address gelato `ExecutionErrors`:
```sh
git cherry-pick cf2ce50...9e01320
```
Fixes

Cherry pick gelato fixes

---

packages/agents/sequencer/src/lib/errors/relayer.ts
packages/agents/sequencer/src/lib/helpers/relayerfee.ts
packages/agents/sequencer/test/lib/helpers/relayerfee.spec.ts
packages/deployments/contracts/src/domain.ts
packages/utils/src/helpers/hex.ts

Cherry pick fee fix

---

ops/mainnet/prod/core/config.tf
ops/mainnet/prod/core/main.tf
ops/testnet/prod/core/config.tf
ops/testnet/prod/core/main.tf
ops/testnet/staging/core/config.tf
ops/testnet/staging/core/main.tf

tf configs for prover read replica

---

packages/agents/cartographer/api/gelato2.http
packages/agents/sequencer/src/lib/helpers/relayerfee.ts
packages/agents/sequencer/test/lib/helpers/relayerfee.spec.ts

Hotfix Relayer fee issue

---

packages/agents/sdk/src/sdkPool.ts
packages/agents/watcher/src/watcher.ts
packages/deployments/contracts/src/cli/init/helpers/assets.ts
packages/utils/src/helpers/asset.ts
packages/utils/test/helpers/asset.spec.ts

Adding in a utility to ensure decimals are pulled from chaindata
Fixes #4193

Hotfix decimals

---

ops/mainnet/prod/backend/main.tf
ops/mainnet/prod/core/config.tf
ops/testnet/prod/core/config.tf
ops/testnet/staging/core/config.tf

typos & dk image for postgrest mainnet

---

ops/modules/db/main.tf
ops/modules/db/variables.tf
ops/testnet/prod/backend/main.tf

Use explicit parameter group dependency

---

ops/mainnet/prod/backend/main.tf

Syncing the manual changed made in AWS console due to "Storage-full" issue.
Fixes

Increase max storage

---

packages/examples/sdk-server/README.md
packages/examples/sdk-server/config.json.example
packages/examples/sdk-server/src/index.ts

sdk-server cleanup

---

.github/workflows/build-test-deploy.yml
docker/sdk-server/Dockerfile
docker/sdk-server/conifg.local.json
ops/testnet/staging/backend/config.tf
ops/testnet/staging/backend/main.tf
ops/testnet/staging/backend/variables.tf

WIP: sdk-server

---

packages/utils/src/peripherals/chainData.ts

fix: handle empty chainData cases.

---

ops/mainnet/prod/core/main.tf
ops/testnet/prod/core/main.tf

increase timeouts

---

packages/adapters/cache/src/lib/caches/executor.ts
packages/agents/sequencer/src/lib/operations/execute/slowpath.ts
packages/agents/sequencer/test/lib/operations/execute/slowpath.spec.ts

Sequencer cache persists

---

packages/adapters/database/src/client.ts

Fixes 
https://github.com/connext/monorepo/issues/4147

Fix pending transfers query

---

.github/workflows/build-test-deploy.yml

Fix build workflow

---

ops/testnet/prod/core/config.tf
packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/database/test/mock.ts
packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/tasks/prover/adapters/database/helper.ts
packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts
packages/agents/lighthouse/test/tasks/prover/operations/proveAndProcess.spec.ts

Enhance offchain messaging layer processing

---

packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
packages/agents/sequencer/src/lib/operations/execute/slowpath.ts
packages/agents/sequencer/src/lib/operations/relayer/fastpath.ts
packages/agents/sequencer/src/lib/operations/relayer/slowpath.ts
packages/agents/sequencer/src/sequencer.ts

4244 handle database

---

ops/testnet/prod/core/main.tf

Hot Fix: Bump up testnet LH prover mem

---

.github/workflows/build-test-deploy.yml
.husky/commit-msg
commitlint.config.js
package.json
yarn.lock

4319 add commitlint verification to monorepo

---

packages/agents/chain-abstraction/src/helpers/api.ts
packages/agents/chain-abstraction/src/helpers/asset.ts
packages/agents/chain-abstraction/src/types/index.ts
packages/agents/chain-abstraction/test/helpers/asset.spec.ts

Added methods for utility of getting all tokens for a specific chain. 
Fixes #4250

feat: getSupportedAssets and tests added

---

packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts

Fix aggregate root no exist

---

packages/agents/sequencer/src/bindings/subscriber/auctions/index.ts

Sequencer should ack/reject properly

---

packages/agents/sequencer/src/lib/operations/execute/fastpath.ts

Apply retry execution to all the non ExecStatus.None transfers 

---

packages/adapters/subgraph/test/mock.ts

fix: unit tests of poller

---

packages/agents/sequencer/src/bindings/subscriber/auctions/index.ts
packages/agents/sequencer/src/lib/entities/config.ts
packages/agents/sequencer/src/sequencer.ts

feat: dont scale with load

---

packages/agents/sequencer/src/lib/errors/executor.ts
packages/agents/sequencer/src/lib/operations/execute/slowpath.ts
packages/agents/sequencer/test/lib/operations/execute/slowpath.spec.ts

fix: expire data check

---

packages/adapters/cache/src/lib/caches/auctions.ts

fix: fast path cache issue

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/database/test/mock.ts
packages/agents/cartographer/poller/src/lib/operations/messagestatus.ts
packages/agents/cartographer/poller/test/lib/operations/messagestatus.spec.ts
packages/utils/src/types/amb.ts
packages/utils/src/types/db.ts

fix: cartographer limit needs increase when assigning messagestatus

---

packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
packages/agents/sequencer/src/lib/operations/execute/slowpath.ts

sequencer exec data not found in the cache
Fixes 
#4382

fix: sequencer exec data not found in the cache

---

README.md
packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
packages/agents/sequencer/src/lib/operations/execute/slowpath.ts

ci: prod sync

---

packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
packages/agents/sequencer/src/lib/operations/execute/slowpath.ts

fix: wait until none

---

packages/agents/chain-abstraction/package.json

chore: bump chain abstraction

---

ops/mainnet/prod/core/config.tf
ops/testnet/prod/core/config.tf
ops/testnet/staging/core/config.tf

fix: sequencer http queue config update
Fixes

ci: testnet prod sync

---

.github/workflows/build-test-deploy.yml

ci: remove deprecated commands

---

packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
packages/agents/sequencer/src/lib/operations/execute/slowpath.ts
packages/agents/sequencer/test/lib/operations/execute/fastpath.spec.ts
packages/agents/sequencer/test/lib/operations/execute/slowpath.spec.ts

Make sequencer transfer thread safe
Fixes

feat: [hotfix]make sequencer transfer thread safe

---

packages/agents/sequencer/src/bindings/publisher/publish/index.ts

chore: add transferId to the requestcontext

---

ops/mainnet/prod/core/main.tf

Slow down slow path -- increase time by 2x across all cron jobs
Fixes

config: slow message crons (2x)

---

ops/mainnet/prod/core/config.tf

ci: add alchemy

---

packages/agents/sequencer/src/bindings/subscriber/auctions/index.ts
packages/agents/sequencer/src/lib/operations/execute/fastpath.ts

Sequencer should not find auction data missing
Fixes 
#4431

4431 sequencer should not find auction data missing

---

packages/agents/sequencer/src/sequencer.ts

fix: exclude HTTP_QUEUE from bindSubscriber

---

packages/agents/sequencer/src/sequencer.ts

Bring in hot fix changes into testnet prod
Fixes

sync testnet prod with prod

---

packages/adapters/database/db/migrations/20230608135754_replace_pk_messages.sql
packages/adapters/database/db/schema.sql
packages/adapters/database/src/client.ts
packages/adapters/database/src/zapatos/schema.d.ts
packages/adapters/database/test/client.spec.ts

4376 message verification fails bc of duplicated missing leaves in the message table

---

packages/adapters/database/db/migrations/20230608135754_replace_pk_messages.sql
packages/adapters/database/db/schema.sql
packages/adapters/database/src/client.ts
packages/adapters/database/src/zapatos/schema.d.ts
packages/adapters/database/test/client.spec.ts

…e message table (#4440)
* feat: replace pk on messages tb
* fix: duplicated insert of messages
* test: fix tests of client
* chore: zapatos
Fixes

Testnet prod 

---

ops/mainnet/prod/backend/config.tf
ops/mainnet/prod/backend/variables.tf
ops/testnet/prod/backend/config.tf
ops/testnet/prod/backend/variables.tf
ops/testnet/staging/backend/config.tf
ops/testnet/staging/backend/variables.tf

ci: use latest image

---

packages/adapters/database/db/schema.sql
packages/adapters/subgraph/src/lib/helpers/parse.ts
packages/deployments/subgraph/src/amarok-hub-v0/mapping/optimism.ts

fix: root message id issue

---

packages/deployments/contracts/src/cli/init/config/testnet/production.ts

Added alchemix assets to allowlist
Chaindata mappings PR: https://github.com/connext/chaindata/pull/74

Alchemix assets

---

README.md
ops/mainnet/prod/backend/config.tf
ops/mainnet/prod/backend/variables.tf
ops/testnet/prod/backend/config.tf
ops/testnet/prod/backend/variables.tf
ops/testnet/prod/core/config.tf
ops/testnet/staging/backend/config.tf
ops/testnet/staging/backend/variables.tf
packages/deployments/contracts/contracts/core/connext/helpers/RelayerProxyHub.sol
packages/deployments/contracts/src/cli/init/config/testnet/production.ts

Merge testnet-prod into main

---

packages/examples/sdk-server/package.json
yarn.lock

fix: use sdk-core

---

ops/testnet/prod/backend/main.tf
ops/testnet/staging/backend/main.tf

fix: health check endpt

---

ops/testnet/prod/backend/main.tf
ops/testnet/staging/backend/main.tf

fix: health check endpt (#4480)

---

packages/agents/lighthouse/src/tasks/prover/bindings/index.ts

feat: add a nonce endpoint

---

packages/adapters/database/db/migrations/20230613125451_add_new_indexes_to_transfers.sql
packages/adapters/database/db/schema.sql
packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/database/test/mock.ts
packages/agents/cartographer/poller/src/lib/operations/transfers.ts

feat: 4449 re org non existent transfer

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/agents/lighthouse/src/tasks/prover/bindings/index.ts
packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts

feat: paginate database call

---

packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts

fix: no need to increase offset because the query uses both startIndex and endIndex

---

ops/testnet/prod/backend/main.tf

ci: sdk-server limits

---

packages/adapters/database/src/client.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/subgraph/src/lib/operations/queries.ts
packages/agents/cartographer/poller/src/lib/operations/index.ts
packages/agents/cartographer/poller/src/lib/operations/messages.ts
packages/agents/cartographer/poller/src/lib/operations/transfers.ts
packages/utils/src/peripherals/subgraph.ts

feat: 4495 increase subgraph queries

---

packages/adapters/database/src/client.ts
packages/agents/relayer/src/bindings/relays/index.ts

feat: dedup messages and improve relayer

---

packages/agents/lighthouse/src/tasks/prover/prover.ts
packages/agents/sdk/src/interfaces/index.ts
packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/src/sdkRouter.ts
packages/agents/sdk/src/sdkShared.ts
packages/agents/sdk/test/sdkShared.spec.ts
packages/examples/sdk-server/examples/index.http
packages/examples/sdk-server/src/routes/base.ts
packages/examples/sdk-server/src/routes/pool.ts
packages/examples/sdk-server/src/routes/shared.ts
packages/examples/sdk-server/src/server.ts

Sdk server load test prep

---

packages/agents/lighthouse/src/tasks/prover/adapters/database/helper.ts

Hotfix SMT db helper cache layer.
Fixes

fix: store interval only when complete

---

packages/adapters/relayer/src/gelato/gelato.ts

fix: remove gelato hardcoded gas limit

---

ops/mainnet/prod/backend/main.tf
ops/modules/auto-scaling/main.tf
ops/modules/auto-scaling/variables.tf
ops/testnet/prod/backend/main.tf
ops/testnet/staging/backend/main.tf

feat: as for sdk-server

---

packages/adapters/database/src/client.ts
packages/adapters/relayer/src/gelato/gelato.ts
packages/utils/src/helpers/merkle.ts

fix: cachedRoot not working for message reorganization

---

ops/testnet/prod/core/config.tf

chore: decrease batchsize for mem

---

ops/testnet/prod/core/config.tf
ops/testnet/prod/core/main.tf

chore: bump mem/batchSize

---

packages/utils/src/helpers/domain.ts

need it for ChainReader to work at airdrop repo, next step following this pr is release.

feat: add multiple networks domains

---

ops/env/testnet/core/secrets.prod.json
ops/testnet/prod/core/config.tf

feat: use alchemy rpc in lh

---

ops/testnet/prod/core/variables.tf

fix: terraform config

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/agents/lighthouse/src/errors/prover.ts
packages/agents/lighthouse/src/tasks/prover/adapters/database/helper.ts
packages/agents/lighthouse/src/tasks/prover/operations/consumer.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/utils/src/helpers/merkle.ts

Reset cache on verification fail
Fixes

fix: reset cache on verification fail

---

ops/testnet/prod/core/config.tf
ops/testnet/staging/core/config.tf
packages/agents/lighthouse/config.json.example
packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/tasks/prover/adapters/database/helper.ts
packages/agents/lighthouse/src/tasks/prover/context.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/agents/lighthouse/src/tasks/prover/prover.ts
packages/agents/lighthouse/test/tasks/prover/adapters/database/helper.spec.ts

Separate reader and writer in LH prover. 
Fixes

feat: separate reader and writer in lh

---

packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts

Set max limit on lh prover pub 
Fixes

fix: set max limit on lh prover pub

---

packages/agents/sdk-wrapper/package.json
packages/agents/sdk-wrapper/src/sdkUtils.ts
packages/agents/sdk-wrapper/test/sdkBase.spec.ts
packages/agents/sdk-wrapper/test/sdkUtils.spec.ts
packages/agents/sdk-wrapper/tsconfig.json
packages/examples/sdk-server/package.json
packages/examples/sdk-server/src/routes/base.ts
packages/examples/sdk-server/src/routes/pool.ts
packages/examples/sdk-server/src/routes/router.ts
packages/examples/sdk-server/src/routes/shared.ts
packages/examples/sdk-server/src/routes/utils.ts
packages/examples/sdk-server/src/server.ts
yarn.lock

Sdk server cors

---

packages/adapters/cache/src/lib/caches/messages.ts
packages/adapters/cache/test/lib/caches/messages.spec.ts
packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/tasks/prover/bindings/index.ts
packages/agents/lighthouse/src/tasks/prover/operations/consumer.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts
packages/agents/lighthouse/src/tasks/prover/prover.ts
packages/agents/lighthouse/test/mock.ts
packages/agents/lighthouse/test/tasks/prover/operations/process.spec.ts
packages/agents/lighthouse/test/tasks/prover/operations/publisher.spec.ts

feat: retry mechanism in lh publisher

---

packages/agents/sdk-wrapper/package.json

feat: bump sdk-wrapper version

---

packages/adapters/cache/src/lib/caches/messages.ts
packages/adapters/cache/test/lib/caches/messages.spec.ts
packages/agents/lighthouse/src/tasks/prover/adapters/database/helper.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/agents/lighthouse/test/mock.ts
packages/agents/lighthouse/test/tasks/prover/adapters/database/helper.spec.ts

Use redis to store LH sub cache
Fixes

feat: use redis to store lh sub cache

---

packages/adapters/relayer/src/gelato/gelato.ts

fix: arb goerli gas limit

---

packages/adapters/cache/src/lib/caches/messages.ts
packages/adapters/cache/test/lib/caches/messages.spec.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts

fix: message duplication in queue

---

ops/testnet/prod/core/main.tf

chore: slowdown publisher cron

---

packages/adapters/relayer/src/gelato/gelato.ts

chore: revert hardcoding for linea

---

.github/workflows/build-test-deploy.yml

ci: publish sdk from sdk-wrapper

---

.github/workflows/build-test-deploy.yml
package.json
packages/agents/sdk-wrapper/package.json

Sdk wrapper publish

---

README.md

ci: commitlint

---

packages/agents/cartographer/poller/src/lib/operations/messages.ts
packages/agents/cartographer/poller/test/lib/operations/messages.spec.ts

fix: reset message checkpoint

---

packages/adapters/relayer/src/gelato/gelato.ts

fix: decrease arb-goerli hardcoded gaslimit

---

packages/adapters/relayer/src/gelato/gelato.ts
packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts

fix: lh upper bound

---

packages/adapters/subgraph/src/lib/operations/queries.ts

fix: 4574 carto graph query errors

---

ops/testnet/prod/core/main.tf

chore: decrease prover pub timeout

---

packages/agents/lighthouse/src/tasks/prover/prover.ts
packages/agents/sequencer/src/sequencer.ts

fix: hard exit on mq disruption

---

ops/testnet/prod/core/main.tf
yarn.lock

fix: tune LH config

---

packages/agents/chain-abstraction/CHANGELOG.md
packages/agents/chain-abstraction/package.json
packages/agents/chain-abstraction/src/index.ts

Chain abstraction v1.0.2 alpha.20

---

packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json

build: sdk stable latest

---

packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/agents/sdk/src/sdkUtils.ts

feat: add fitler by domain getTransfers()

---

packages/deployments/contracts/contracts/messaging/RootManager.sol
packages/deployments/contracts/contracts_forge/messaging/RootManager.t.sol

macro l1 - dispute block events

---

ops/mainnet/prod/core/main.tf

Fixes #4629 
Slows slow path
Fixes #4629

config: slow down lighthouse

---

ops/mainnet/prod/core/config.tf
ops/mainnet/prod/core/main.tf

ci: add mainnet ops

---

packages/agents/cartographer/poller/src/lib/operations/messagestatus.ts

Add pagination on message status check
Fixes

fix: add pagination on message status check

---

packages/deployments/contracts/contracts/messaging/connectors/wormhole/WormholeSpokeConnector.sol

fix: renounceOwnership logic

---

packages/deployments/contracts/contracts/messaging/interfaces/ambs/wormhole/IWormholeReceiver.sol

fix: update IWormholeReceiver interface

---

ops/modules/ecr/main.tf

add ecr lifecycle policy

---

ops/mainnet/prod/backend/main.tf
packages/agents/sdk/CHANGELOG.md

Sdk server mainnet ops

---

packages/agents/cartographer/poller/src/lib/operations/prices.ts

fix: historical price poller check to timestamp

---

ops/testnet/prod/core/config.tf

chore: add new excluded address

---

ops/testnet/prod/core/config.tf

Adds satellite for crosschain testing.
Addresses #60 for testnet prod

chore: exempt satellite on mumbai

---

packages/deployments/contracts/contracts_forge/fork/WormholeConnectorFork.t.sol
packages/deployments/contracts/contracts_forge/fork/constants/WormholeUpgradeTransfers.sol
packages/deployments/contracts/contracts_forge/fork/upgrade/Execution.t.sol
packages/deployments/contracts/contracts_forge/utils/DeploymentLookup.sol
packages/deployments/contracts/contracts_forge/utils/ExecutionForkHelper.sol
packages/deployments/contracts/contracts_forge/utils/MotherForker.sol
packages/deployments/contracts/contracts_forge/utils/RpcEnvLookup.sol
packages/deployments/contracts/contracts_forge/utils/RpcLookup.sol

Fixes #4641 
Adds tests outlined https://www.notion.so/connext/Spec-Replacing-Multichain-9e5aedcac7df488b8b38b7f72dcb8535?pvs=4#0d443c6f691448ddb65bbb7c236483af
- Add in test to perform upgrade
- Refactor utilities to make it easier to manage forks
- Add libraries to manage network configuration constants
Fixes

4641 bnb fork tests

---

packages/agents/lighthouse/src/tasks/processFromRoot/helpers/arbitrum.ts

feat: catch error

---

ops/mainnet/prod/backend/config.tf
ops/mainnet/prod/backend/main.tf
ops/mainnet/prod/core/main.tf
packages/agents/lighthouse/src/tasks/processFromRoot/processFromRoot.ts

ci: ops hotfix

---

packages/deployments/contracts/hardhat.config.ts
packages/deployments/contracts/package.json
packages/deployments/contracts/tasks/connector/wormholeDeliver.ts
yarn.lock

feat: wormhole hh task

---

packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk-wrapper/src/sdkPool.ts
packages/agents/sdk-wrapper/test/sdkPool.spec.ts
packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/agents/sdk/src/interfaces/index.ts
packages/agents/sdk/src/sdkPool.ts
packages/examples/sdk-server/examples/index.http
packages/examples/sdk-server/src/routes/pool.ts

4699 sdk provider options

---

install-tenderly-cli.sh
packages/deployments/contracts/package.json
packages/deployments/contracts/src/spawnDevnet.ts

feat: tenderly devnet setup

---

ops/mainnet/prod/core/main.tf

fix: 512 -> 2048

---

packages/agents/sdk-wrapper/src/sdkPool.ts
packages/agents/sdk-wrapper/src/sdkShared.ts
packages/agents/sdk-wrapper/test/sdkPool.spec.ts
packages/agents/sdk-wrapper/test/sdkShared.spec.ts
packages/agents/sdk/src/sdkShared.ts
packages/agents/sdk/test/sdkShared.spec.ts

4730 sdk latency subfix

---

packages/agents/sequencer/src/config.ts
packages/agents/sequencer/src/lib/operations/execute/fastpath.ts

fix: sequencer missing bids

---

docker-compose.devnet-services.yaml

Set up required services for core offchain agents

---

packages/deployments/contracts/src/cli/init/config/testnet/production.ts

Fixes 
Chaindata: https://github.com/connext/chaindata/pull/81

add BTRST token to allowlisting scripts

---

packages/agents/cartographer/api/gelato2.http
packages/utils/src/peripherals/gelato.ts

chore: Re update gelato estimate testnet

---

packages/agents/sdk/package.json
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/test/sdkPool.spec.ts

fix: account for decimal precision differences

---

packages/agents/cartographer/poller/src/lib/operations/transfers.ts

fix: pending transfers poller in carto-transfers

---

packages/agents/sdk/src/sdkBase.ts

fix: force update slippage in sdkbase

---

packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json

build: bump sdk core

---

packages/deployments/contracts/contracts_forge/messaging/connectors/admin/AdminHubConnector.t.sol

Fix test contract to be able to compile
Fixes

fix: update admin hub connector test

---

ops/testnet/prod/core/config.tf
packages/agents/cartographer/api/example.http

config: add test contract to relayer fee exemption

---

packages/deployments/contracts/src/cli/init/helpers/assets.ts

fix: include all chains

---

ops/testnet/prod/core/config.tf

fix: update mumbai distributor

---

ops/testnet/prod/core/config.tf

config: add new distributor

---

ops/testnet/prod/core/config.tf

chore: Hotfix-update-mumbai-distributor-2

---

ops/mainnet/prod/core/config.tf

Hotfix-distributor-update-for-tokensoft

---

ops/mainnet/prod/core/config.tf

config: update distributors and satellites

---

packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
packages/deployments/contracts/src/cli/init/config/testnet/production.ts

Whitelist NEXT xerc20s

---

packages/deployments/contracts/src/cli/init/config/testnet/production.ts

feat: new xerc20 for dappradar testnet

---

ops/mainnet/prod/core/main.tf

Down scale mainnet

---

packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/test/sdkPool.spec.ts
packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
packages/deployments/contracts/src/cli/init/config/testnet/production.ts
packages/deployments/contracts/src/cli/init/helpers/assets.ts
packages/deployments/contracts/src/cli/init/init.ts

fix: merge changes to sdk and init script from main

---

packages/deployments/contracts/tasks/bumpTransfer.ts

fix: bumpTransfer task

---

packages/agents/chain-abstraction/src/helpers/swapdata.ts
packages/agents/chain-abstraction/src/index.ts
packages/agents/chain-abstraction/src/libs/origin/swapandxcall.ts
packages/agents/chain-abstraction/test/helpers/swapdata.spec.ts
packages/agents/chain-abstraction/test/libs/origin/swapandxcall.spec.ts

Added a Authorization config for One Inch API
Fixes #4927

4927-One Inch config added to chain-abstraction SDK

---

docker-compose.chains.yaml

fix: smoke tests on main

---

.github/workflows/build-test-deploy.yml
docker-compose.services.yaml

chore: use the constant for db_image

---

packages/agents/lighthouse/src/tasks/sendOutboundRoot/operations/sendOutboundRoot.ts

fix: 4969 lh sendoutboundroot for all chains

---

packages/agents/lighthouse/src/tasks/sendOutboundRoot/operations/sendOutboundRoot.ts

fix: send to relayer with correct domain

---

packages/agents/chain-abstraction/package.json

fix:chain-abstraction:bump

---

.github/workflows/build-test-deploy.yml
ops/modules/ecr/main.tf

fix: tag images with the branch name

---

packages/agents/lighthouse/src/config.ts

Support `propose` in config services type for lighthouse
Fixes

config: support propose service

---

packages/adapters/database/src/client.ts

fix: 4971 lh proveandprocess works staging

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/database/test/mock.ts
packages/agents/lighthouse/src/tasks/propose/operations/propose.ts
packages/agents/lighthouse/test/tasks/propose/operations/propose.spec.ts

Update LH propose db handlers
Fixes

fix: lh propose aggregate root handler

---

ops/testnet/prod/core/config.tf

fix: add zksync provider

---

ops/testnet/prod/backend/main.tf
ops/testnet/prod/core/main.tf
ops/testnet/staging/backend/main.tf

fix: public subnets for services

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/database/test/mock.ts
packages/adapters/txservice/src/shared/contracts.ts
packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/tasks/propose/errors.ts
packages/agents/lighthouse/src/tasks/propose/operations/propose.ts
packages/agents/lighthouse/test/tasks/propose/operations/propose.spec.ts

Resolve LH propose task.
Fixes

fix: resolve LH propose task

---

packages/adapters/database/src/client.ts
packages/adapters/subgraph/src/lib/operations/queries.ts
packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts
packages/agents/lighthouse/src/tasks/propagate/propagate.ts
packages/agents/lighthouse/src/tasks/propose/propose.ts

Resolve propagate for op-roots V1

fix: resolve propagate for oproots v1

---

packages/deployments/subgraph/config/amarok-runtime-staging.json

chore: update the blocknumber of Connext subgraph

---

ops/testnet/staging/core/main.tf

fix: lh propose cron

---

ops/testnet/staging/core/config.tf
packages/deployments/contracts/tasks/debugCustomError.ts

fix: message queue config

---

packages/deployments/contracts/contracts/core/connext/helpers/RelayerProxyHub.sol

fix: relayer proxy hub finalize propagate

---

packages/adapters/subgraph/src/lib/operations/queries.ts
packages/agents/cartographer/poller/src/lib/operations/roots.ts

fix: subgraph query and carto:roots for snapshots

---

packages/adapters/database/src/client.ts
packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts

Fix propagate address

---

ops/modules/ecr-lcp/main.tf

fix: improve ecp to remove any tagged images

---

packages/agents/cartographer/poller/src/lib/operations/roots.ts

fix: consistent checkpoint name

---

ops/testnet/prod/core/config.tf

fix: testnet prod terraform

---

.github/ISSUE_TEMPLATE/xERC20.md

feat: create xERC20 template

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/database/test/mock.ts
packages/adapters/txservice/src/shared/contracts.ts
packages/adapters/txservice/test/shared/contracts.spec.ts
packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/tasks/propose/errors.ts
packages/agents/lighthouse/src/tasks/propose/operations/propose.ts
packages/agents/lighthouse/src/tasks/propose/operations/proposeSpoke.ts
packages/agents/lighthouse/test/tasks/propose/operations/proposeSpoke.spec.ts
packages/utils/src/mocks/mock.ts

Handle initial conditions in LH propose

Handle initial conditions in LH propose 

---

packages/agents/lighthouse/package.json
packages/agents/lighthouse/src/mockable.ts
packages/agents/lighthouse/src/tasks/propagate/helpers/linea.ts
packages/agents/lighthouse/test/tasks/propagate/helpers/linea.spec.ts
packages/deployments/contracts/hardhat.config.ts
packages/deployments/contracts/package.json
packages/deployments/contracts/tasks/connector/claimLinea.ts
yarn.lock

feat: 5069 testnet onboarding lh agents works

---

ops/mainnet/prod/core/config.tf

chore: remove llamarpc from LH propagate config

---

docker/lighthouse/lambda/Dockerfile

fix: docker build fix

---

packages/agents/lighthouse/src/tasks/sendOutboundRoot/helpers/bnb.ts
packages/agents/lighthouse/test/tasks/sendOutboundRoot/helpers/bnb.spec.ts

fix: reduce gas limit for bnb sendoutboutroot

---

packages/adapters/subgraph/.graphclientrc.yml

fix: restore gnosis subgraph comment

---

packages/adapters/database/src/client.ts
packages/agents/lighthouse/src/tasks/propose/operations/propose.ts

fix: more fixes for LH propose in Op Roots v1.1

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/database/test/mock.ts
packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/tasks/propagate/operations/index.ts
packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts
packages/agents/lighthouse/src/tasks/propagate/propagate.ts
packages/agents/lighthouse/src/tasks/propose/operations/propose.ts
packages/agents/lighthouse/src/tasks/propose/operations/proposeSpoke.ts
packages/agents/lighthouse/test/tasks/propagate/operations/propagate.spec.ts
packages/agents/lighthouse/test/tasks/propose/operations/propose.spec.ts
packages/agents/lighthouse/test/tasks/propose/operations/proposeSpoke.spec.ts

Call finalize when in op mode

---

docker/bin/wait-for-services.sh

fix: increase wait attempts

---

packages/agents/lighthouse/src/tasks/processFromRoot/helpers/linea.ts
packages/agents/lighthouse/src/tasks/propagate/helpers/linea.ts
packages/agents/lighthouse/test/tasks/processFromRoot/helpers/linea.spec.ts
packages/agents/lighthouse/test/tasks/propagate/helpers/linea.spec.ts

fix: increase gas for linea propagate

---

packages/agents/lighthouse/src/tasks/processFromRoot/helpers/linea.ts
packages/agents/lighthouse/test/tasks/processFromRoot/helpers/linea.spec.ts

fix: linea process from root args

---

packages/agents/lighthouse/src/tasks/propose/operations/propose.ts

fix: duplicated save

---

ops/mainnet/prod/core/config.tf

fix: remove llamarpc rpc

---

ops/mainnet/prod/core/config.tf
ops/mainnet/prod/core/main.tf
ops/testnet/prod/core/config.tf
ops/testnet/prod/core/main.tf
ops/testnet/staging/core/config.tf
ops/testnet/staging/core/main.tf

1. Optimise AS policies to prevent unnecessary scale ups of services that at steady-state run at higher than threshold resources
2. Increase node memory allocation for router subscriber, as it has been going OOM
Fixes

fix: improve auto-scaling policies

---

packages/agents/lighthouse/src/tasks/processFromRoot/processFromRoot.ts
packages/agents/lighthouse/src/tasks/propagate/propagate.ts
packages/agents/lighthouse/src/tasks/prover/prover.ts
packages/agents/lighthouse/src/tasks/sendOutboundRoot/sendOutboundRoot.ts

fix: 5125 sendoutboundroot cron called twice

---

ops/testnet/staging/core/main.tf

fix: increase lh mem

---

ops/testnet/staging/backend/config.tf
ops/testnet/staging/backend/main.tf
ops/testnet/staging/core/config.tf
ops/testnet/staging/core/main.tf
ops/testnet/staging/core/outputs.tf
ops/testnet/staging/core/variables.tf

PR to get staging ops changes into main, so that future PRs from main to staging don't run into conflicts (at least on the ops side).
No changes in actual infra will take place
Fixes

chore: update main ops with latest staging changes

---

ops/env/testnet/core/secrets.prod.json
ops/testnet/prod/core/config.tf
ops/testnet/prod/core/variables.tf

Remove linea node, as it is not reliable.

fix: remove linea node from rpc list

---

ops/env/testnet/core/secrets.staging.json
ops/testnet/staging/core/config.tf
ops/testnet/staging/core/main.tf
ops/testnet/staging/core/variables.tf
packages/deployments/contracts/src/cli/init/config/testnet/staging.ts

feat: add lighthouse web3signer for LH propose

---

packages/adapters/cache/src/lib/caches/messages.ts
packages/adapters/cache/test/lib/caches/messages.spec.ts
packages/agents/lighthouse/src/errors/prover.ts
packages/agents/lighthouse/src/tasks/prover/operations/consumer.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/agents/lighthouse/test/mock.ts
packages/agents/lighthouse/test/tasks/prover/operations/process.spec.ts

fix: retry issue in lh on main

---

ops/testnet/staging/core/main.tf

fix: increase timeout for propose cron

---

ops/testnet/staging/core/main.tf

fix: enable lambda-in-vpc for lh propose

---

packages/deployments/contracts/src/cli/init/config/testnet/production.ts

feat: update alcx testnet asset

---

packages/deployments/contracts/src/cli/init/config/mainnet/production.ts

feat: add mainnet ALCX

---

packages/adapters/cache/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/deployments/contracts/package.json
packages/utils/package.json

Update package json with release version
Fixes

chore: update package json with release version

---

packages/adapters/cache/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/deployments/contracts/package.json
packages/utils/package.json

fix: contract publish npm

---

ops/mainnet/prod/core/config.tf

hotfix: hotfix to remove the public pkt rpc

---

packages/deployments/contracts/src/utils.ts
packages/deployments/contracts/tasks/connector/claimLinea.ts

fix: linea claim message hh task

---

packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts
packages/agents/lighthouse/test/tasks/propagate/operations/propagate.spec.ts

fix: disable checking propagate cooldown

---

packages/deployments/subgraph/src/amarok-runtime-staging/mapping/helper/index.ts
packages/deployments/subgraph/src/amarok-runtime-v0/mapping/helper/index.ts
packages/deployments/subgraph/src/helper/index.ts

fix: linea mainnet subgraph

---

ops/testnet/staging/core/config.tf
ops/testnet/staging/core/variables.tf

fix: remove arb goerli

---

package.json
yarn.lock

See: https://discord.com/channels/992549151134982234/1171397833807646760 for an in-depth discussion
Fixes

fix: update to non-leaking dep

---

ops/modules/kms/locals.tf

fix: remove user

---

packages/agents/lighthouse/src/tasks/processFromRoot/processFromRoot.ts
packages/agents/lighthouse/src/tasks/propagate/propagate.ts
packages/agents/lighthouse/src/tasks/propose/propose.ts
packages/agents/lighthouse/src/tasks/prover/prover.ts
packages/agents/lighthouse/src/tasks/sendOutboundRoot/sendOutboundRoot.ts

chore: improve logging for mode mismatch

---

packages/agents/router/src/tasks/executor/operations/execute.ts
packages/agents/router/test/executor/operations/execute.spec.ts

fix: skip processing a tx with unsupported domain error

---

packages/agents/lighthouse/src/tasks/sendOutboundRoot/helpers/bnb.ts
packages/agents/lighthouse/test/tasks/sendOutboundRoot/helpers/bnb.spec.ts

chore: decrease gaslimit on bnb spoke

---

ops/modules/kms/locals.tf
packages/agents/router/src/tasks/executor/operations/execute.ts
packages/agents/router/test/executor/operations/execute.spec.ts

fix: skip processing a transfer with an error.

---

ops/env/testnet/core/secrets.prod.json
ops/testnet/prod/core/config.tf
ops/testnet/prod/core/variables.tf

Add drpc testnet endpoints to off-chain agent config.
Fixes 
https://github.com/connext/monorepo/issues/5102

feat: add drpc testnet endpoints

---

packages/deployments/contracts/src/cli/init/config/mainnet/production.ts

Zoomer re-registration with pseudo domain

fix: re-zoomer psuedo domain

---

package.json
yarn.lock

Fix: pin envelop to non mem-leaking dependency version

---

packages/adapters/cache/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/deployments/contracts/package.json
packages/utils/package.json

feat: sdk 2.2.0-alpha.2

---

packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/agents/sdk/src/sdkUtils.ts

Fixes #5273 
Will need new sdk version
Fixes

5273 query error

---

packages/adapters/database/src/client.ts
packages/adapters/database/src/index.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/database/test/mock.ts
packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts
packages/agents/lighthouse/src/tasks/propose/operations/proposeHub.ts
packages/agents/lighthouse/src/tasks/propose/operations/proposeSpoke.ts
packages/agents/lighthouse/test/tasks/prover/operations/publisher.spec.ts
packages/utils/src/mocks/mock.ts

Ensure wait period while using outboundroot in a snapshot.
Fixes 
https://github.com/connext/monorepo/issues/5277

fix: ensure wait period while using outboundroot

---

packages/deployments/subgraph/src/amarok-hub-v0/mapping/merkleTreeManager.ts
packages/deployments/subgraph/src/amarok-hub-v0/mapping/optimism.ts
packages/deployments/subgraph/src/amarok-hub-v0/mapping/rootManager.ts
packages/deployments/subgraph/src/amarok-hub-v0/schema.graphql
packages/deployments/subgraph/src/amarok-hub-v0/subgraph.template.yaml
packages/deployments/subgraph/src/amarok-runtime-v0/mapping/spokeConnector.ts
packages/deployments/subgraph/src/amarok-runtime-v0/schema.graphql
packages/deployments/subgraph/src/amarok-runtime-v0/subgraph.template.yaml

Sync staging handlers with main
Fixes

feat: sync staging handlers with main

---

ops/mainnet/prod/backend/config.tf
packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk-wrapper/src/config.ts
packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/agents/sdk/src/config.ts
packages/agents/sdk/src/sdkShared.ts
packages/agents/sdk/test/sdkShared.spec.ts

* feat: allow disabling chains or assets
* chore: disable usdt and dai from sdk server
* feat: config consistency with wrapper
* chore: bump sdk version
* test: getSupported filter
* test: fix test
Fixes

feat: sdk support assets

---

packages/adapters/subgraph/.graphclientrc.yml

chore: update strategy to highestValue

---

packages/adapters/subgraph/src/reader.ts
packages/adapters/subgraph/test/reader.spec.ts

This reverts commit 777e07e2f0e7e8a343380a4cacd678dfe02c9923.
Revert "fix: start in slow mode by default"
Fixes

Revert "fix: start in slow mode by default"

---

packages/agents/lighthouse/src/tasks/propose/propose.ts

hotfix lh propose db url
Fixes

fix: hotfix lh propose db url

---

packages/adapters/subgraph/.graphclient/sources/Connext_Goerli/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Goerli/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Goerli/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Mumbai/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Mumbai/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Mumbai/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_OptimismGoerli/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_OptimismGoerli/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_OptimismGoerli/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Goerli/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Goerli/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_Goerli/types.ts
packages/adapters/subgraph/.graphclientrc.yml

feat: take highest value to prod

---

packages/adapters/subgraph/.graphclientrc.yml

feat: enable decentralized one on gnosis

---

packages/adapters/subgraph/.graphclient/sources/Connext_LocalArbitrumOne/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalArbitrumOne/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_LocalArbitrumOne/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalMainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalMainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_LocalMainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalOptimism/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalOptimism/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_LocalOptimism/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/types.ts

fix: udpate graph client after changes for base
Fixes

fix: udpate graph client after changes for base

---

packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/errors/prover.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/agents/lighthouse/test/mock.ts
packages/agents/lighthouse/test/tasks/prover/operations/process.spec.ts

Lh check pause

---

packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/errors/prover.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/agents/lighthouse/test/mock.ts
packages/agents/lighthouse/test/tasks/prover/operations/process.spec.ts

Cherry pick lh pause check
Fixes

Cherry pick lh pause check

---

ops/testnet/prod/core/config.tf

fix: base goerli LH config

---

packages/adapters/database/src/client.ts
packages/agents/cartographer/poller/src/lib/operations/routers.ts

fix: router liquidity events

---

packages/adapters/database/src/client.ts
packages/agents/cartographer/poller/src/lib/operations/routers.ts

fix: router liquidity events (#5358)

---

ops/mainnet/prod/backend/config.tf

chore: disable gnosis dai in sdk

---

ops/mainnet/prod/backend/config.tf

chore: disable gnosis dai in sdk on prod

---

ops/mainnet/prod/backend/main.tf
ops/mainnet/prod/core/config.tf
ops/mainnet/prod/core/main.tf
ops/mainnet/prod/core/outputs.tf
ops/mainnet/prod/core/variables.tf

update lh and watcher tf configs
Fixes

fix: update lh and watcher tf configs

---

ops/env/mainnet/core/secrets.prod.json

fix: rebuild with new api key

---

ops/env/mainnet/core/secrets.prod.json

fix: add lh propose heartbeat

---

packages/agents/cartographer/poller/src/lib/operations/roots.ts

Hotfix checkpoint

---

packages/adapters/database/db/migrations/20231219013906_add_snapshots_primary_key.sql
packages/adapters/database/db/schema.sql
packages/adapters/database/src/zapatos/schema.d.ts

Add snapshots primary key
Fixes

fix: add snapshots primary key

---

ops/mainnet/prod/core/main.tf

config: run every 15min

---

packages/adapters/database/db/migrations/20231219072355_add_spoke_optimistic_roots_primary_key.sql
packages/adapters/database/db/schema.sql
packages/adapters/database/src/zapatos/schema.d.ts

fix: hotfix add spoke optimistic roots pkey
Fixes

fix: hotfix add spoke optimistic roots pkey

---

packages/agents/lighthouse/src/tasks/prover/operations/process.ts

fix: query spoke connector

---

packages/agents/lighthouse/src/tasks/propose/errors.ts
packages/agents/lighthouse/src/tasks/propose/operations/proposeHub.ts
packages/utils/src/mocks/mock.ts

fix: use snapshot n for proposal

---

packages/agents/lighthouse/src/tasks/propose/operations/proposeHub.ts
packages/utils/src/mocks/mock.ts

fix: snapshot timeout

---

packages/deployments/contracts/src/cli/init/config/mainnet/production.ts

feat: add xoLIT

---

ops/testnet/staging/core/main.tf

chore: bump memory size

---

packages/adapters/database/src/client.ts
packages/adapters/database/test/client.spec.ts
packages/adapters/subgraph/src/lib/operations/queries.ts
packages/adapters/subgraph/src/reader.ts
packages/agents/cartographer/poller/src/lib/operations/roots.ts

fix: replace root timestamp with propose timestamp

---

ops/mainnet/prod/core/main.tf

fix: change propagate frequency to 5 mins
Fixes

fix: change propagate frequency to 5 mins

---

packages/agents/lighthouse/src/tasks/propose/operations/proposeSpoke.ts
packages/agents/lighthouse/test/tasks/propose/operations/proposeSpoke.spec.ts

fix: do not wait for root to be finalized

---

packages/agents/lighthouse/src/tasks/propose/propose.ts

fix: need to return successful response

---

packages/agents/lighthouse/src/tasks/propose/operations/proposeSpoke.ts

Hub spoke is always proposed directly finalize it
Fixes

fix: hub spoke is always proposed directly finalize it

---

packages/adapters/subgraph/.graphclient/sources/Hub_Goerli/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Goerli/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_Goerli/types.ts
packages/adapters/subgraph/.graphclientrc.yml

feat: optimism decentralized network subgraph

---

ops/env/mainnet/core/secrets.prod.json
ops/mainnet/prod/core/config.tf
ops/mainnet/prod/core/variables.tf

config: rotate lighthouse admin key

---

packages/adapters/subgraph/.graphclientrc.yml

fix: switch to  hosted gnosis subgraph

---

packages/agents/lighthouse/src/tasks/prover/adapters/database/helper.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts
packages/agents/lighthouse/test/tasks/prover/operations/publisher.spec.ts

fix: clear local cache

---

packages/agents/lighthouse/src/tasks/prover/operations/process.ts

fix: missing await

---

packages/agents/lighthouse/src/tasks/prover/operations/process.ts

fix: update only proven messages

---

packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Xdai/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Xdai/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Xdai/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Goerli/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Goerli/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_Goerli/types.ts
packages/agents/lighthouse/src/config.ts
packages/deployments/contracts/hardhat.config.ts
packages/deployments/contracts/src/config.ts
packages/deployments/contracts/tasks/connector/setOptimisticMode.ts

feat: 5384 x1 testnet via fast path

---

ops/testnet/prod/core/config.tf
packages/agents/relayer/src/bindings/relays/index.ts
packages/agents/relayer/src/lib/entities/config.ts

fix: connext relayer minGasPrice

---

packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json

build: sdk v2.2.2-alpha.0

---

ops/env/testnet/core/secrets.prod.json
ops/testnet/prod/core/config.tf
ops/testnet/prod/core/variables.tf

fix: x1 testnet private RPC

---

ops/testnet/prod/core/config.tf

fix: add rpc to lighthouse config

---

packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/deployments/contracts/package.json

build: sdk v2.2.2-alpha.1

---

packages/adapters/cache/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/deployments/contracts/package.json
packages/utils/package.json

build: sdk version bump

---

packages/adapters/cache/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/deployments/contracts/deploy/05_deployUtils.ts
packages/deployments/contracts/deployments/x1-testnet/MultiSend.json
packages/deployments/contracts/package.json
packages/utils/package.json

fix: x1 testnet multisend

---

packages/adapters/relayer/src/connext/connext.ts
packages/agents/relayer/src/bindings/relays/index.ts

fix: use ethers instead of txservice on relayer

---

packages/utils/src/peripherals/gelato.ts

fix: x1 conversion rate

---

packages/utils/src/peripherals/gelato.ts

fix: add x1 to testnet fee map

---

ops/testnet/prod/core/config.tf
packages/agents/sequencer/src/lib/operations/execute/fastpath.ts

fix: bypass relayer fee for x1 testnet

---

ops/testnet/prod/core/main.tf

fix: bump up relayer task size

---

ops/testnet/prod/core/main.tf

fix: bump up seq sub auto scaling

---

ops/env/testnet/core/secrets.prod.json
ops/testnet/prod/core/config.tf

fix: change testnet relayer key

---

packages/adapters/cache/src/lib/caches/tasks.ts
packages/adapters/cache/test/lib/caches/tasks.spec.ts
packages/agents/relayer/src/bindings/relays/index.ts

feat: Improve relayer cache operation

---

packages/adapters/cache/src/lib/caches/tasks.ts
packages/adapters/cache/test/lib/caches/tasks.spec.ts
packages/agents/relayer/src/bindings/relays/index.ts

* feat: improve methods
* fix: args updated
Fixes

feat: Improve relayer cache operation (#5506)

---

ops/mainnet/prod/core/main.tf
ops/testnet/prod/core/main.tf
packages/agents/relayer/package.json
packages/agents/relayer/src/bindings/index.ts
packages/agents/relayer/src/bindings/relays/index.ts
packages/agents/relayer/src/make.ts

Health check relayer

---

packages/agents/router/src/tasks/publisher/operations/getXCalls.ts

fix: optimize destination query in router-publisher

---

packages/agents/relayer/src/bindings/relays/index.ts
packages/agents/relayer/src/config.ts
packages/agents/relayer/src/lib/entities/config.ts
packages/integration/test/constants/testnet/index.ts

fix: relayer poller config

---

ops/mainnet/prod/core/main.tf
ops/testnet/prod/core/main.tf

fix: relayer env config

---

packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts

fix: better management last batch execution

---

packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/agents/sdk/src/interfaces/index.ts
packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/src/sdkRouter.ts
packages/agents/sdk/test/sdkBase.spec.ts
packages/agents/sdk/test/sdkRouter.spec.ts
packages/deployments/contracts/src/cli/init/config/testnet/production.ts
packages/examples/sdk-server/src/routes/base.ts
packages/examples/sdk-server/src/server.ts

Added signers logging for analytics

---

packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/agents/sdk/src/interfaces/index.ts
packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/src/sdkPool.ts
packages/agents/sdk/src/sdkRouter.ts
packages/agents/sdk/test/sdkBase.spec.ts
packages/agents/sdk/test/sdkRouter.spec.ts
packages/deployments/contracts/src/cli/init/config/testnet/production.ts
packages/examples/sdk-server/src/routes/base.ts
packages/examples/sdk-server/src/server.ts

* feat: add testnet sDAI
* feat: add signer to estimate functions
* feat: rm random signer from server
* feat: add signer to calculateAmountReceived
* feat: rm signer check from fxns that do not need it
* feat: rm signer check from fxns that do not need it
* test: fix signer tests
* fix: lint
* feat: updated version
* fix: update wrapper version
---------
Fixes

Added signers logging for analytics (#5573)

---

ops/mainnet/prod/core/config.tf

chore: add more chains

---

ops/mainnet/prod/core/main.tf

Increase lh propose freq to every 10 min
Fixes

fix: increase lh propose freq to every 10 min

---

packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumOne/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumOne/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumOne/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalArbitrumOne/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalArbitrumOne/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_LocalArbitrumOne/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalMainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalMainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_LocalMainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalOptimism/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_LocalOptimism/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_LocalOptimism/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Xdai/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Xdai/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Xdai/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Mainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Mainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_Mainnet/types.ts
packages/adapters/subgraph/.graphclientrc.yml

fix: update x1 testnet okx subgraph url
Fixes

fix: update x1 testnet okx subgraph url

---

ops/mainnet/prod/core/main.tf

fix: hot fix lh propagate frequency

---

ops/mainnet/prod/backend/main.tf

feat: increase max instances

---

.github/workflows/build-test-deploy.yml
packages/utils/package.json
packages/utils/src/helpers/domain.ts
packages/utils/test/helpers/domain.spec.ts

feat: dynamically update chainid to domainid map

---

packages/deployments/subgraph/config/amarok-runtime-v0.json
packages/deployments/subgraph/config/amarok-stableswap-v0.json
packages/deployments/subgraph/src/amarok-hub/abis/AvalancheHubConnector.json
packages/deployments/subgraph/src/amarok-hub/abis/BaseHubConnector.json
packages/deployments/subgraph/src/amarok-hub/abis/MantleHubConnector.json
packages/deployments/subgraph/src/amarok-hub/abis/MetisHubConnector.json
packages/deployments/subgraph/src/amarok-hub/abis/PolygonZkHubConnector.json
packages/deployments/subgraph/src/amarok-hub/subgraph.template.yaml
packages/deployments/subgraph/src/amarok-runtime/mapping/helper/index.ts

fix: update batch 1 subgraph configs

---

ops/mainnet/prod/backend/config.tf
ops/mainnet/prod/core/config.tf

Add terraform configs for chain batch

---

ops/env/mainnet/backend/secrets.prod.json
ops/mainnet/prod/backend/variables.tf
ops/mainnet/prod/core/config.tf

fix: hotfix prod tf configs

---

.github/workflows/build-test-deploy.yml
packages/adapters/subgraph/package.json

Release subgraph package

---

ops/mainnet/prod/backend/config.tf

Prod <- Testnet prod Sync

---

packages/agents/lighthouse/src/tasks/propose/operations/proposeHub.ts

fix: hot fix lh propose to handle initial condition

---

ops/mainnet/prod/backend/config.tf
ops/mainnet/prod/core/config.tf

config: remove zksync

---

ops/mainnet/prod/core/main.tf

fix: increase propagate frequency

---

ops/mainnet/prod/core/config.tf
ops/mainnet/staging/core/config.tf

fix: add missing keys

---

ops/modules/db/main.tf

feat: bump db engine version

---

ops/modules/db-replica/main.tf

fix: hot fix update aws replica db version

---

packages/adapters/relayer/src/gelato/gelato.ts
packages/adapters/relayer/test/gelato/gelato.spec.ts
packages/agents/lighthouse/src/tasks/prover/operations/process.ts
packages/agents/router/src/tasks/executor/operations/sequencer.ts
packages/agents/sequencer/src/lib/operations/relayer/fastpath.ts
packages/agents/sequencer/src/lib/operations/relayer/slowpath.ts
packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
packages/deployments/contracts/src/cli/init/config/mainnet/staging.ts
packages/deployments/contracts/src/cli/init/config/testnet/production.ts
packages/deployments/contracts/src/cli/init/config/testnet/staging.ts
packages/deployments/contracts/src/cli/init/init.ts
packages/utils/src/helpers/domain.ts
packages/utils/src/peripherals/gelato.ts

Fixes #5654 
- Updates `GELATO_RELAYER` to be domain aware
- Enables blacklist relayer functionality
- Ensures gelato is set properly on the init script, instead of being named, using `utils` functions
Fixes #5654

feat: update gelato addresses

---

packages/deployments/contracts/package.json
packages/deployments/contracts/src/cli/helpers/constants.ts
packages/deployments/contracts/src/cli/helpers/deployments.ts
packages/deployments/contracts/src/cli/helpers/index.ts
packages/deployments/contracts/src/cli/helpers/log.ts
packages/deployments/contracts/src/cli/helpers/tx.ts
packages/deployments/contracts/src/cli/helpers/types.ts
packages/deployments/contracts/src/cli/init/helpers/assets.ts
packages/deployments/contracts/src/cli/init/helpers/deployments.ts
packages/deployments/contracts/src/cli/init/helpers/messaging.ts
packages/deployments/contracts/src/cli/init/helpers/types.ts
packages/deployments/contracts/src/cli/init/init.ts
packages/deployments/contracts/src/cli/op-mode/helpers/deployments.ts
packages/deployments/contracts/src/cli/op-mode/helpers/index.ts
packages/deployments/contracts/src/cli/op-mode/helpers/types.ts
packages/deployments/contracts/src/cli/op-mode/main.ts
packages/deployments/contracts/src/cli/op-mode/switchMode.ts
packages/deployments/contracts/src/cli/ownership/helpers/constants.ts
packages/deployments/contracts/src/cli/ownership/helpers/deployments.ts
packages/deployments/contracts/src/cli/ownership/helpers/types.ts
packages/deployments/contracts/src/cli/ownership/transferOwnership.ts
packages/deployments/contracts/src/cli/types.ts
packages/deployments/contracts/src/cli/upgrade/helpers/deployments.ts
packages/deployments/contracts/src/cli/upgrade/helpers/types.ts
packages/deployments/contracts/src/cli/watcher/helpers/types.ts

add activate optimistic mode cli method

---

ops/mainnet/prod/core/config.tf
ops/mainnet/prod/core/outputs.tf
ops/mainnet/staging/core/config.tf
ops/mainnet/staging/core/outputs.tf
ops/testnet/prod/core/config.tf
ops/testnet/prod/core/outputs.tf
ops/testnet/staging/core/config.tf
ops/testnet/staging/core/outputs.tf

fix: replace relayer with relayer_server

---

ops/env/mainnet/backend/secrets.prod.json
ops/env/mainnet/core/secrets.prod.json

fix: do not use deprecated graph key

---

packages/deployments/contracts/src/cli/init/config/mainnet/production.ts

fix: add dokia to allowlist routers

---

packages/adapters/relayer/src/gelato/gelato.ts

feat: remove hardcoded gasLimits for gelato relay

---

packages/utils/src/peripherals/gelato.ts

fix: update gelato mainnet proxy address

---

packages/utils/test/peripherals/gelato.spec.ts

fix: gelato address unit test

---

ops/mainnet/prod/core/config.tf

fix: hotfix relayer priority

---

packages/agents/sequencer/src/lib/operations/execute/fastpath.ts

fix: break iff insufficient liquidity

---

ops/mainnet/prod/core/config.tf

This reverts commit 94fd991b9c30a0c3934ac889cfd6148d330ce091.
Fixes

Revert "fix: hotfix relayer priority"

---

packages/adapters/relayer/src/gelato/gelato.ts
packages/deployments/contracts/tasks/addLiquidity.ts

chore: remove limit from gelato api request

---

ops/mainnet/prod/backend/main.tf

feat: increase server min instances

---

ops/mainnet/prod/backend/main.tf
packages/utils/test/peripherals/gelato.spec.ts

testnet-prod <- main

---

packages/adapters/relayer/src/gelato/gelato.ts

fix: keep hardcoded gasLimit until it gets fixed

---

ops/testnet/prod/backend/config.tf
ops/testnet/prod/core/config.tf
ops/testnet/staging/backend/config.tf
ops/testnet/staging/backend/variables.tf
ops/testnet/staging/core/config.tf
ops/testnet/staging/core/main.tf
ops/testnet/staging/core/variables.tf

Staging tf changes

---

packages/agents/router/package.json
packages/agents/router/src/config.ts
packages/agents/router/src/setup.ts
packages/agents/router/src/tasks/publisher/publisher.ts
packages/agents/router/src/tasks/subscriber/subscriber.ts
packages/utils/src/types/primitives.ts
yarn.lock

5738 mq connection handling

---

packages/agents/sequencer/test/lib/helpers/relayerfee.spec.ts
packages/utils/src/helpers/domain.ts

feat: sequencer can pass xerc20 assets into gelato conversion

---

README.md

chore: update twitter link

---

packages/adapters/subgraph/package.json

fix: bump subgraph version

---

ops/mainnet/prod/backend/config.tf
ops/mainnet/prod/core/config.tf

Temporarily disable mode chain until multisig tx executed

---

ops/mainnet/prod/core/config.tf

fix: reduce lh config to be less than 4kb

---

packages/adapters/txservice/package.json
packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/agents/sdk/src/config.ts
packages/deployments/contracts/package.json
yarn.lock

Mode: bump version for sdk and contracts

---

ops/mainnet/prod/backend/config.tf
ops/mainnet/prod/core/config.tf

Prepare terraform configs for mode chain

---

docker-compose.devnet-services.yaml
docker-compose.services.yaml

fix: upgrade postgrest version

---

docker-compose.devnet-services.yaml
docker-compose.services.yaml

fix: update postgrest docker version

---

docker-compose.devnet-services.yaml
docker-compose.services.yaml

fix: postgres docker updated

---

packages/adapters/txservice/package.json
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/deployments/contracts/package.json

Mode: bump sdk and utils

---

packages/utils/src/peripherals/gelato.ts

feat: use arbitrum as equivalent

---

packages/adapters/txservice/package.json
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/deployments/contracts/package.json
packages/utils/package.json

Bump utils and SDK

---

packages/adapters/cache/src/lib/caches/routers.ts
packages/adapters/cache/test/lib/caches/routers.spec.ts
packages/agents/router/src/tasks/publisher/bindings/subgraph/index.ts
packages/agents/router/src/tasks/publisher/context.ts
packages/agents/router/src/tasks/publisher/operations/index.ts
packages/agents/router/src/tasks/publisher/operations/retryXCalls.ts
packages/agents/router/src/tasks/publisher/operations/status.ts
packages/agents/router/src/tasks/publisher/publisher.ts
packages/agents/router/test/mock.ts
packages/agents/router/test/publisher/operations/status.spec.ts
packages/agents/sequencer/src/bindings/server/index.ts
packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
packages/utils/src/types/api.ts

feat: monitor router status

---

packages/agents/sequencer/src/bindings/server/index.ts

Missing params for router status endpoint

---

packages/deployments/contracts/src/cli/init/config/testnet/production.ts

Added **InrETH** and its representation on Goerli and Mumbai
Fixes

feat: InrETH

---

ops/mainnet/prod/core/main.tf

Run lh prover more frequently

---

ops/mainnet/prod/core/config.tf

fix: prove l2 chains every two hours at least

---

packages/agents/lighthouse/src/tasks/prover/operations/process.ts

fix: revert lh origin handle check

---

ops/mainnet/prod/core/config.tf

fix: remove blast metis rpc

---

packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Mainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Mainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_Mainnet/types.ts
packages/adapters/subgraph/.graphclientrc.yml

fix: metis stableswap subgraph goldsky

---

ops/testnet/staging/backend/main.tf

fix: bump up postgrest version

---

ops/mainnet/prod/backend/main.tf
ops/testnet/prod/backend/main.tf

fix: bump postgrest version

---

packages/adapters/txservice/package.json
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/deployments/contracts/package.json
packages/utils/package.json

fix: bump sepolia

---

ops/mainnet/prod/core/config.tf
ops/mainnet/staging/core/config.tf
ops/testnet/staging/core/config.tf
packages/adapters/relayer/src/connext/connext.ts
packages/adapters/relayer/src/gelato/gelato.ts
packages/adapters/relayer/src/index.ts
packages/adapters/relayer/test/connext/connext.spec.ts
packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/tasks/propagate/propagate.ts
packages/agents/relayer/src/bindings/relays/index.ts
packages/agents/relayer/src/config.ts
packages/agents/relayer/src/make.ts
packages/utils/src/constants/index.ts
packages/utils/src/constants/relayer.ts
packages/utils/src/types/relayer.ts

Add keep3r relayer type

---

packages/deployments/contracts/src/cli/init/config/mainnet/production.ts

feat:ezETH xerc20

---

packages/utils/src/peripherals/gelato.ts

fix: added equivalents for gelato

---

packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/utils/package.json

fix: sdk bump gelato

---

packages/utils/src/peripherals/gelato.ts

fix: chainId mapping

---

packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/utils/package.json

fix: sdk bump

---

packages/agents/sdk/src/config.ts

fix: hotfix remove check

---

packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json

fix: sdk bump hotfix

---

packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/types.ts
packages/adapters/subgraph/.graphclientrc.yml
packages/agents/cartographer/poller/db/schema.sql

Backup subgraph mode

---

ops/modules/lambda/variables.tf

fix: increase the default lambda timeout

---

packages/adapters/cache/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/deployments/contracts/package.json

fix: bump other agents

---

ops/mainnet/prod/core/config.tf

Hotfix: remove zksync config from prod seq

---

packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/utils/package.json
packages/utils/src/peripherals/relayer.ts

chore: flipped fees switch

---

ops/mainnet/prod/core/config.tf

Remove zksync config from all

---

packages/agents/lighthouse/src/config.ts
packages/agents/lighthouse/src/tasks/propose/errors.ts
packages/agents/lighthouse/src/tasks/propose/operations/index.ts
packages/agents/lighthouse/src/tasks/propose/operations/proposeHub.ts
packages/agents/lighthouse/test/mock.ts
packages/agents/lighthouse/test/tasks/propose/operations/propose.spec.ts
packages/utils/src/mocks/mock.ts

fix: derisk LH proposehub from RPC delay risk

---

ops/mainnet/staging/backend/config.tf
ops/mainnet/staging/core/config.tf
ops/testnet/prod/backend/config.tf
ops/testnet/prod/core/config.tf
ops/testnet/staging/backend/config.tf
ops/testnet/staging/core/config.tf

Migrate testnet-prod to sepolia

---

ops/mainnet/prod/core/config.tf

fix: bump up max safe roots

---

ops/mainnet/prod/core/config.tf

fix: enforce messaging fees in sequencer

---

packages/adapters/cache/package.json
packages/adapters/subgraph/package.json
packages/adapters/txservice/package.json
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/deployments/contracts/package.json
packages/utils/package.json

feat: sdk v2.5.0-alpha.1

---

packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/agents/sdk/src/sdkBase.ts
packages/agents/sdk/test/sdkBase.spec.ts
packages/utils/src/mocks/mock.ts
packages/utils/src/peripherals/chainData.ts

Relayer fee cap

---

ops/mainnet/prod/core/config.tf

- Temporarily increases fee buffer to relax sequencer enforcements
Fixes

fix: 85% buffer

---

ops/mainnet/prod/core/config.tf

Hotfix inc relayerfee tolerance

---

CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/utils/package.json

fix: bump sdk and utils version

---

ops/mainnet/prod/core/config.tf

Revert "Hotfix inc relayerfee tolerance"

---

packages/adapters/subgraph/.graphclientrc.yml

fix: add bware subgraph

---

packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk-wrapper/src/sdkUtils.ts
packages/agents/sdk-wrapper/test/sdkUtils.spec.ts
packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/agents/sdk/src/interfaces/index.ts
packages/agents/sdk/src/sdkShared.ts
packages/agents/sdk/src/sdkUtils.ts
packages/agents/sdk/test/sdkUtils.spec.ts
packages/examples/sdk-server/examples/index.http
packages/examples/sdk-server/src/routes/utils.ts

Asset prices from carto

---

packages/agents/sequencer/src/bindings/server/index.ts
packages/agents/sequencer/src/lib/operations/execute/fastpath.ts

fix: use lowercase for router status request

---

packages/agents/router/src/tasks/publisher/bindings/subgraph/index.ts
packages/agents/router/src/tasks/publisher/publisher.ts

fix: detect and throw on stuck router intervals

---

packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/types.ts
packages/adapters/subgraph/.graphclientrc.yml

Remove bware mode runtime

---

packages/adapters/subgraph/.graphclient/sources/Connext_Optimism/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Optimism/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Optimism/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Mainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_Mainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_Mainnet/types.ts
packages/adapters/subgraph/.graphclientrc.yml

- Fixes runtime base name
- Regenerates prod client
Fixes

Hotfix prod client

---

ops/mainnet/prod/core/config.tf

fix: it returns weird errors

---

packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/types.ts

fix: update graph client for latest

---

ops/mainnet/prod/core/config.tf

fix: 4kb config size

---

ops/mainnet/prod/core/config.tf

fix: config_size_aws

---

packages/adapters/subgraph/src/lib/helpers/parse.ts
packages/adapters/subgraph/test/lib/helpers/parse.spec.ts

fix: parser validation explicitly checks for undefined and null fields

---

packages/adapters/txservice/src/aggregator.ts
packages/adapters/txservice/test/aggregator.spec.ts

Improvement for txservice Aggregator on Error
This improvement will include information about the RPC provider that triggered the error.

feat: improve txservice logs

---

packages/adapters/txservice/package.json
packages/agents/sdk/CHANGELOG.md

chore: bump up txservice

---

ops/mainnet/prod/core/main.tf

fix: hotfix bump up relayer memory

---

ops/mainnet/prod/core/config.tf

fix: update metis rpc for relayer

---

packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/types.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/types.ts
packages/adapters/subgraph/.graphclientrc.yml

Hotfix graphclient

---

packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/types.ts
packages/adapters/subgraph/.graphclientrc.yml

fix: hotfix add goldsky endpoints

---

packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumOne/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumOne/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumOne/types.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/introspectionSchema.ts
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/schema.graphql
packages/adapters/subgraph/.graphclient/sources/Connext_Polygon/types.ts

chore: rebuild graphclient

---

.github/workflows/build-test-deploy.yml

fix: disable staging smoke tests

---

ops/mainnet/prod/core/config.tf

fix: hot fix switch lh mainnet rpc to alchemy

---

ops/mainnet/prod/backend/config.tf

feat: disable base temporarily

---

ops/mainnet/prod/backend/main.tf

fix: increase replica storage

---

packages/utils/src/maticjs/client.ts
packages/utils/test/maticjs/client.spec.ts

fix: testnet mumbai is no longer supported

---

ops/mainnet/prod/backend/config.tf
packages/utils/test/maticjs/client.spec.ts
packages/utils/test/maticjs/proof.spec.ts

feat: reenable base

---

ops/env/testnet/backend/secrets.prod.json
ops/env/testnet/core/secrets.prod.json

feat: add graph api key to testnet ops

---

ops/env/testnet/backend/secrets.prod.json

fix: testnet/backend prod mac mismatch

---

packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/utils/package.json
packages/utils/src/peripherals/gelato.ts

fix: linea chainid fix

---

packages/agents/sdk-wrapper/package.json
packages/agents/sdk/package.json
packages/utils/package.json

fix: version bump sdk

---

ops/mainnet/prod/backend/config.tf

And xlayer from getSupportedd in sdkserver.
Fixes

feat: rm dai, klp, kp3r, next, testvotes, usdc, usdt

---

packages/agents/sdk-wrapper/CHANGELOG.md
packages/agents/sdk-wrapper/package.json
packages/agents/sdk/CHANGELOG.md
packages/agents/sdk/package.json
packages/utils/package.json
packages/utils/src/peripherals/gelato.ts

fix: metis gelato estimates
