packages/sdk/src/sdk.ts, packages/test-ui/src/App.tsx, packages/utils/src/messaging.ts
Warning: Merging this PR will break live demos until this is merged: https://github.com/connext/nats-auth/pull/1
=> Message signing

packages/sdk/src/crossChainTransfer.ts, packages/sdk/src/sdk.ts, packages/sdk/test/crossChainTransfer.spec.ts, packages/test-ui/src/App.tsx
=> SDK events

packages/router/package.json, packages/router/src/listener.ts, packages/router/src/subgraph.ts, packages/sdk/src/listener.ts, packages/sdk/src/sdk.ts, packages/sdk/src/transactionManager.ts, yarn.lock
- Add methods to add/remove listener
- Fix
=> detach listeners

packages/router/package.json, packages/router/src/contract.ts, packages/router/src/handler.ts, packages/router/src/index.ts, packages/router/src/listener.ts, packages/router/test/handler.spec.ts, packages/sdk/package.json, packages/sdk/src/sdk.ts, packages/sdk/src/transactionManager.ts, packages/utils/src/messaging.ts, yarn.lock
=> Neverthrow

packages/sdk/src/sdk.ts
=> Sdk Event Name Typo

packages/txservice/src/provider.ts
=> Optimism hardcoded gas price

packages/router/src/handler.ts, packages/router/test/handler.spec.ts
=> Validate expiry

packages/integration/package.json, packages/integration/test/load/txserviceConcurrency.ts, packages/integration/test/utils/accountManager.ts, packages/integration/test/utils/config.ts, packages/txservice/package.json, packages/txservice/src/config.ts, packages/txservice/src/error.ts, packages/txservice/src/provider.ts, packages/txservice/src/txservice.ts, packages/txservice/src/types.ts, packages/txservice/test/constants.ts, packages/txservice/test/provider.spec.ts, packages/txservice/test/transaction.spec.ts, packages/txservice/test/txservice.spec.ts, yarn.lock
=> [txservice] Load tests for local chain

packages/integration/ops/config/router/config.json, packages/integration/test/load/txserviceConcurrency.ts, packages/integration/test/utils/config.ts
- using TEST token, run load test with remote chain
- save error reports to stats/ folder
Fixes #123
=> [txservice] Load testing for remote chains

package.json, packages/integration/ops/chains.docker-compose.yml, packages/integration/test/load/routerConcurrency.ts, packages/integration/test/load/routerCyclical.ts, packages/integration/test/load/txserviceConcurrency.ts, packages/integration/test/utils/accountManager.ts, packages/integration/test/utils/chain.ts, packages/integration/test/utils/reporting.ts, packages/integration/test/utils/sdkAgent.ts, packages/integration/test/utils/sdkManager.ts, packages/sdk/src/sdk.ts, packages/sdk/src/subgraph.ts
- Adds stats files for tests
- Improves metrics tracked for concurrency
- Improves logging in sdk agent + account manager
- Improves funding management on account manager
=> Concurrency hotfixes

.github/workflows/build-docker-image-and-verify.yml, packages/integration/test/integration.spec.ts
Add router logs on job failures
=> GitHub add  logs

packages/integration/package.json, packages/integration/test/integration.spec.ts, packages/router/src/adapters/subgraph/index.ts, packages/router/src/lib/errors/prepare.ts, packages/router/src/lib/helpers/prepare.ts, packages/router/src/lib/operations/auction.ts, packages/router/src/lib/operations/prepare.ts, packages/router/test/globalTestHook.ts, packages/sdk/src/sdk.ts, packages/sdk/test/unit/sdk.spec.ts, packages/utils/src/basic.ts
Fixes the `invalid BigNumber` error on the router
=> Load test hotfixes

packages/sdk/src/sdk.ts, packages/sdk/src/subgraph.ts
=> [sdk] removeAllListeners stops subgraph polling

packages/router/src/bindings/contractReader/index.ts, packages/router/src/config.ts, packages/router/src/lib/errors/index.ts, packages/router/src/lib/errors/prepare.ts, packages/router/src/lib/helpers/auction.ts, packages/router/src/lib/helpers/index.ts, packages/router/src/lib/helpers/prepare.ts, packages/router/src/lib/operations/auction.ts, packages/router/src/lib/operations/prepare.ts, packages/router/test/lib/operations/prepare.spec.ts, packages/sdk/src/sdk.ts
Unsubscribe can happen after auction rather than in an interval, which was a little weird. Also removed nested try-catch.
=> Clean up unsubscribe

packages/integration/package.json, packages/integration/test/integration.spec.ts, packages/integration/test/load/routerCyclical.ts, packages/integration/test/utils/sdkAgent.ts, packages/router/package.json, packages/router/src/bindings/messaging/auctionRequest.ts, packages/router/src/bindings/messaging/index.ts, packages/router/src/bindings/messaging/metaTxRequest.ts, packages/router/test/bindings/messaging/auctionRequest.spec.ts, packages/router/test/bindings/messaging/metaTxRequest.spec.ts, packages/sdk/.nycrc.json, packages/sdk/package.json, packages/sdk/src/sdk.ts, packages/sdk/src/subgraph.ts, packages/sdk/src/transactionManager.ts, packages/sdk/test/helper/contract.ts, packages/sdk/test/integration/transactionManager.spec.ts, packages/sdk/test/unit/sdk.spec.ts, packages/sdk/test/unit/subgraph.spec.ts, packages/sdk/test/unit/subgraphsdk.spec.ts, packages/test-ui/src/App.tsx, packages/txservice/package.json, packages/utils/src/asset.ts, packages/utils/src/index.ts, packages/utils/src/messaging.ts, yarn.lock
=> 233 sdk messaging

packages/txservice/src/provider.ts, packages/txservice/test/provider.spec.ts
Simple temporary fix for : https://github.com/connext/nxtp/issues/241
=> [txservice] Add validation step to send method to prevent false submit

packages/sdk/src/transactionManager.ts
=> hotfix signer

packages/sdk/.nycrc.json, packages/sdk/src/error.ts, packages/sdk/src/sdk.ts, packages/sdk/src/subgraph.ts, packages/sdk/src/transactionManager.ts, packages/sdk/test/integration/transactionManager.spec.ts, packages/sdk/test/unit/sdk.spec.ts, packages/sdk/test/unit/subgraph.spec.ts
Refactor some of the erroring in SDK to be a bit more specific and descriptive. Perhaps not the most ideal data structure, but at least a step in the right direction and enough info to continue debugging for now. Also matches other modules' error structure a bit more.
Fixes #238
=> [sdk] Error refactor

packages/sdk/src/sdk.ts, packages/sdk/test/unit/sdk.spec.ts, packages/test-ui/src/components/Swap.tsx
=> Add preferred router

packages/router/src/adapters/subgraph/subgraph.ts, packages/router/src/bindings/contractReader/index.ts, packages/router/src/lib/entities/contractReader.ts, packages/router/test/bindings/contractReader/index.spec.ts, packages/router/test/globalTestHook.ts, packages/sdk/src/sdk.ts, packages/txservice/src/provider.ts, packages/txservice/src/txservice.ts, packages/utils/src/mock.ts
=> Safe confirmations on subgraph

packages/router/src/lib/helpers/index.ts, packages/router/src/lib/helpers/shared.ts, packages/router/src/lib/operations/auction.ts, packages/router/src/lib/operations/prepare.ts, packages/router/test/lib/operations/auction.spec.ts, packages/router/test/lib/operations/prepare.spec.ts, packages/sdk/src/sdk.ts, packages/utils/package.json, packages/utils/src/index.ts, packages/utils/src/time.ts, yarn.lock
=> Use NTP time

packages/contracts/hardhat.config.ts, packages/contracts/src/tasks/renounceOwnership.ts
=> Renounce ownership task

packages/integration/ops/config/router/config.json, packages/integration/test/integration.spec.ts, packages/router/src/config.ts, packages/router/src/lib/errors/fulfill.ts, packages/router/src/lib/errors/index.ts, packages/router/src/lib/helpers/prepare.ts, packages/router/src/lib/operations/auction.ts, packages/router/src/lib/operations/fulfill.ts, packages/router/src/lib/operations/prepare.ts, packages/router/test/config.spec.ts, packages/router/test/lib/helpers/prepare.spec.ts, packages/router/test/lib/operations/auction.spec.ts, packages/router/test/lib/operations/fulfill.spec.ts, packages/router/test/lib/operations/prepare.spec.ts, packages/router/test/utils.ts, packages/sdk/src/sdk.ts, packages/sdk/src/transactionManager.ts, packages/sdk/test/integration/transactionManager.spec.ts, packages/test-ui/src/components/Router.tsx, packages/utils/src/chainData.ts, packages/utils/src/mock.ts, packages/utils/src/util.ts
=> fee config

.github/PULL_REQUEST_TEMPLATE.md, packages/router/src/adapters/subgraph/subgraph.ts
=> Autocancel

CHANGELOG.md, packages/router/src/bindings/fastify/cancel.ts, packages/router/src/bindings/fastify/errors.ts, packages/router/src/bindings/fastify/index.ts, packages/router/src/bindings/fastify/schema.ts, packages/utils/src/basic.ts
Fixes #288.
Add admin endpoint.
=> Admin endpoint for cancellation

packages/utils/src/signatures.ts
=> Signature fix for trust wallet

packages/sdk/src/sdk.ts
=> SDK hotfix

packages/router/src/adapters/subgraph/subgraph.ts, packages/router/test/adapters/subgraph/subgraph.spec.ts
=> 268 subgraph unit test

packages/txservice/src/dispatch/dispatch.ts, packages/txservice/src/dispatch/transaction.ts, packages/txservice/src/error.ts, packages/txservice/src/txservice.ts, packages/txservice/src/types.ts, packages/txservice/test/dispatch/transaction.spec.ts
=> compare to current baseline before bumping gas price; select max

packages/router/src/bindings/contractReader/index.ts
Transaction submission on chain can be race-y.
Adding the `transactionId` for the handling queue to the `handleMultipleTransactions` to reduce the number of races possible.
=> Move all queueing to the top level handling

packages/router/src/adapters/subgraph/subgraph.ts, packages/router/src/bindings/contractReader/index.ts, packages/utils/src/subgraph.ts
=> Get tx receipt fix

packages/router/example.http, packages/router/src/bindings/contractReader/index.ts, packages/router/src/bindings/fastify/index.ts, packages/router/src/bindings/messaging/index.ts, packages/router/src/router.ts, packages/sdk/src/sdk.ts
=> Fixes for diagnostic mode

packages/txservice/src/config.ts, packages/txservice/src/dispatch/dispatch.ts, packages/txservice/src/dispatch/provider.ts, packages/txservice/src/dispatch/transaction.ts
=> do not consult buffer for nonce value

.github/workflows/build-docker-image-and-verify.yml, packages/integration/test/integration.spec.ts, packages/integration/test/utils/config.ts, packages/test-ui/src/App.tsx
=> Always use static providers

packages/router/src/lib/operations/cancel.ts
=> Get this passing

packages/router/src/config.ts, packages/router/src/router.ts, packages/txservice/src/dispatch/dispatch.ts, packages/txservice/src/dispatch/provider.ts, packages/txservice/src/dispatch/transaction.ts
Things we could do for temp solution:
- add gas stations to the config
- hardcode gas in config
- raise confirmations and timeout period in config
=> Hardcode gas via config / infinite attempts

packages/router/src/lib/operations/auction.ts, packages/router/src/router.ts, packages/router/test/globalTestHook.ts, packages/txservice/src/txservice.ts
=> add: use chainData for decimal

packages/txservice/src/dispatch/provider.ts
=> [txservice] Hardcode a gas limit min

packages/txservice/src/dispatch/dispatch.ts
=> [txservice] Log the nonce values in getNonce

packages/txservice/src/txservice.ts
=> [txservice] enforce single instance of txservice; throw on reinstantiate

packages/router/src/bindings/fastify/index.ts, packages/router/src/bindings/metrics/index.ts, packages/router/src/router.ts
=> make it better

CHANGELOG.md, packages/router/test/config.spec.ts, packages/sdk/src/transactionManager/transactionManager.ts, packages/sdk/test/integration/transactionManager.spec.ts, packages/test-ui/src/components/Router.tsx
=> Hardcoded gas limit for SDK txs

packages/sdk/src/transactionManager/transactionManager.ts
- If the transaction fails onchain, it would appear as a failure in metamask making it really hard to debug
- Use the `txservice.parseError` function to handle and properly throw any estimate gas errors
- Use the `gasEstimate.mul(2)` rather than the hardcoded constant as the `gasLimit` value
=> Add estimate gas to limit

packages/txservice/src/dispatch/buffer.ts, packages/txservice/src/dispatch/dispatch.ts, packages/txservice/src/txservice.ts
This solution relies more heavily on the local nonce, as opposed to the brute force "guess and check" method we were doing before.
=> [txservice] Patch serialized send; remove overengineered solution

packages/txservice/src/dispatch/provider.ts
=> [txservice] add 'fast' as gas station res param

packages/txservice/src/dispatch/buffer.ts, packages/txservice/src/dispatch/dispatch.ts
=> [txservice] Hotfix: Add buffer cap

packages/utils/src/signatures.ts
=> Trust fix again

packages/router/src/bindings/contractReader/index.ts, packages/router/src/lib/entities/contractReader.ts, packages/router/src/lib/entities/index.ts, packages/router/test/bindings/contractReader/index.spec.ts
=> subgraph buffer

packages/sdk/src/sdk.ts
=> fix: dryrun

packages/router/src/bindings/contractReader/index.ts
=> fix subgraph buffer

packages/txservice/src/provider.ts
=> [txservice] Hotfix: make sure we are checking to see if res and data defined in getGasPrice

packages/contracts/deploy/deploy.ts, packages/contracts/hardhat.config.ts, packages/contracts/src/tasks/setAggregator.ts, packages/contracts/src/tasks/setDexPrice.ts, packages/router/package.json, packages/router/src/bindings/messaging/auctionRequest.ts, packages/router/src/lib/operations/auction.ts, packages/router/test/bindings/messaging/auctionRequest.spec.ts, packages/router/test/globalTestHook.ts, packages/router/test/lib/operations/auction.spec.ts, packages/utils/src/messaging.ts
=> Auction stuff

packages/sdk/src/transactionManager/transactionManager.ts
xDAI was broken.
Fix xDAI by hardcoding gas estimate.
=> Hotfix for xdai estimate gas issues

packages/sdk/src/error.ts, packages/sdk/src/sdk.ts, packages/sdk/test/unit/sdk.spec.ts
- add: new error invalidCallTo
- add: check callTo address contract deployed status
- add: unit test
=> 391 callTo

packages/router/src/lib/helpers/shared.ts
=> Fix the logic to estimate gas

packages/router/src/bindings/contractReader/index.ts
- rmv: blockNumber flag
- rmv: delay.
=> fix handling tracker

packages/sdk/src/sdk.ts
=> Hotfix lower bound

packages/utils/src/subgraph.ts
=> Bware subgraphs

packages/router/src/config.ts, packages/sdk/src/sdkBase.ts, packages/test-ui/src/components/Router.tsx, packages/utils/src/subgraph.ts
=> Default fallback subgraphs

CHANGELOG.md, packages/router/src/config.ts
`allowFulfillRelay = false` was not respected.
=> Handle fulfill relay

packages/router/src/bindings/messaging/auctionRequest.ts, packages/router/src/bindings/messaging/index.ts, packages/router/src/bindings/messaging/metaTxRequest.ts, packages/router/src/lib/errors/auction.ts, packages/router/src/lib/errors/fulfill.ts, packages/router/src/lib/operations/fulfill.ts, packages/sdk/src/sdkBase.ts, packages/sdk/src/types.ts, packages/sdk/test/unit/sdkBase.spec.ts, packages/utils/src/error.ts
allowFulfillRelay: false was still broken.
=> Allow fulfill relay fix

packages/sdk/src/sdkBase.ts
=> Hotfix: handle csv strings for subgraphs

packages/router/src/lib/errors/auction.ts, packages/router/src/lib/operations/auction.ts, packages/router/test/lib/operations/auction.spec.ts
=> chg: fix logging error for unsupported chains

package.json, packages/integration/ops/config/router/config.json, packages/integration/ops/web3signer.docker-compose.yml, packages/integration/package.json, packages/sdk/src/subgraph/subgraph.ts
- Fix
- Fix config
- Change config to use docker internal network
- Fix typo
=> web3signer itest fix

packages/utils/src/fallbackSubgraph.ts
=> [utils] Hotfix: fix hasSynced logic

add-router.sh, deploy-subgraph.sh
- No way to easily add router to all networks
- Create a script that executes all required network router-adds
=> Add router script

packages/router/test/lib/operations/auction.spec.ts, packages/sdk/src/utils.ts, packages/utils/src/gasEstimates.ts, packages/utils/src/subgraph.ts
- Fix gas estimate
- Remove gas limit hardcode (doesnt seem to work properly)
=> hotfixes 3

packages/router/src/config.ts
=> Hotfix: enforce a minimum subgraph sync buffer setting

packages/utils/src/fallbackSubgraph.ts
=> Hotfix: have subg start out synced

packages/sdk/src/sdkBase.ts, packages/sdk/src/utils.ts, packages/sdk/test/unit/sdkBase.spec.ts
=> add metaxBuffer

packages/sdk/src/sdkBase.ts, packages/sdk/test/unit/sdkBase.spec.ts
Sorting logic was backwards and not unit tested.
=> Sorting fixed

packages/router/src/lib/errors/cancel.ts, packages/router/src/lib/operations/cancel.ts, packages/router/test/lib/operations/cancel.spec.ts, packages/txservice/src/chainreader.ts, packages/txservice/src/provider.ts
=> cancel fulfill hotfix

CHANGELOG.md, packages/router/src/bindings/contractReader/index.ts, packages/router/src/lib/entities/contractReader.ts, packages/router/test/bindings/contractReader/index.spec.ts
=> Track by status not block number

packages/router/src/adapters/contract/contract.ts, packages/router/src/adapters/contract/index.ts, packages/router/src/lib/errors/auction.ts, packages/router/src/lib/errors/contracts.ts, packages/router/src/lib/operations/prepare.ts, packages/router/test/globalTestHook.ts, packages/subgraph/config/v1-runtime.json
=> Emergency hotfix

packages/router/src/adapters/subgraph/subgraph.ts
=> Delete from handling tracker

README.md
The link to TxService is broken
Fix the typo in the link name
=> Fix txservice link

CHANGELOG.md, add-router.sh, deploy-subgraph.sh, packages/contracts/hardhat.config.ts
- optimism not included in `add-router.sh`
- add optimism to `add-router.sh`
- fix chains in `deploy-subgraph.sh`
=> Add optimism to script

packages/router/src/lib/helpers/shared.ts
=> optimism fixes for metaTxFee

packages/contracts/package.json
=> Add contracts source

packages/utils/src/subgraph.ts
=> Hotfix: Update subgraph default URIs

packages/integration/test/load/routerConcurrency.ts, packages/integration/test/load/routerCyclical.ts, packages/router/src/adapters/subgraph/subgraph.ts, packages/router/src/lib/helpers/prepare.ts, packages/router/src/lib/operations/auction.ts, packages/router/src/lib/operations/prepare.ts, packages/router/test/lib/helpers/prepare.spec.ts, packages/router/test/lib/operations/auction.spec.ts, packages/router/test/lib/operations/prepare.spec.ts, packages/sdk/src/error.ts, packages/sdk/src/sdk.ts, packages/sdk/src/sdkBase.ts, packages/sdk/src/utils.ts, packages/sdk/test/unit/sdk.spec.ts, packages/sdk/test/unit/sdkBase.spec.ts, packages/utils/src/asset.ts, packages/utils/src/index.ts, packages/utils/src/router.ts
=> ux transferQuote

packages/sdk/src/sdk.ts, packages/sdk/src/sdkBase.ts, packages/sdk/src/types.ts, packages/test-ui/package.json, packages/test-ui/src/App.tsx, packages/test-ui/src/components/Router.tsx, packages/test-ui/src/components/Swap.tsx, packages/test-ui/src/utils.ts, yarn.lock
- Pass chainData into SDK
- Pass chaindata properly
Chaindata not passed in through SDK properly.
Pass in chaindata.
=> chaindata in sdk

CHANGELOG.md, packages/utils/src/asset.ts
- getting decimals in native asset fails
- handle edgecase
=> Fix native asset handling

packages/sdk/src/subgraph/subgraph.ts, packages/utils/src/fallbackSubgraph.ts
=> Hotfix: sort order for subgraphs

.vscode/settings.json, CHANGELOG.md, packages/txservice/src/chainreader.ts, packages/txservice/src/chainservice.ts, packages/txservice/src/dispatch.ts, packages/txservice/src/error.ts, packages/txservice/src/provider.ts, packages/txservice/test/chainreader.spec.ts, packages/txservice/test/chainservice.spec.ts, packages/txservice/test/dispatch.spec.ts, packages/txservice/test/provider.spec.ts
Too much TransactionServiceFailure
No more TransactionServiceFailure
=> [txservice] Surface error types

packages/contracts/deployments.json, packages/contracts/deployments/arbitrum-one/Multicall.json, packages/contracts/deployments/arbitrum-one/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/deployments/avalanche/Multicall.json, packages/contracts/deployments/avalanche/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/deployments/bsc/Multicall.json, packages/contracts/deployments/bsc/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/deployments/ftm/Multicall.json, packages/contracts/deployments/ftm/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/deployments/goerli/Multicall.json, packages/contracts/deployments/goerli/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/deployments/mainnet/Multicall.json, packages/contracts/deployments/mainnet/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/deployments/matic/Multicall.json, packages/contracts/deployments/matic/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/deployments/moonriver/Multicall.json, packages/contracts/deployments/moonriver/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/deployments/optimism/Multicall.json, packages/contracts/deployments/optimism/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/deployments/xdai/Multicall.json, packages/contracts/deployments/xdai/solcInputs/2af66875574c960b31db37abca96b537.json, packages/contracts/hardhat.config.ts, packages/utils/src/subgraph.ts
Multicalls not deployed.
Deploy multicall.
=> Add multicall

packages/txservice/test/chainreader.spec.ts
=> [txservice] Improve accuracy of getTokenPrice unit tests

packages/txservice/src/chainreader.ts
=> gasFee-hotfixes

packages/router/src/lib/helpers/shared.ts, packages/router/test/lib/helpers/shared.spec.ts, packages/sdk/src/sdk.ts, packages/sdk/src/sdkBase.ts, packages/sdk/test/unit/sdk.spec.ts, packages/sdk/test/unit/sdkBase.spec.ts, packages/txservice/src/chainreader.ts, packages/txservice/test/chainreader.spec.ts
=> [router] [sdk ] mainnetEquivalent for native token

packages/txservice/src/error.ts
=> [txservice] Hotfix: add alreadyknown error parsing regex phrase

packages/router/test/bindings/messaging/auctionRequest.spec.ts, packages/router/test/bindings/messaging/statusRequest.spec.ts, packages/router/test/lib/operations/status.spec.ts, packages/txservice/src/error.ts
=> [router] Add code coverage / unit tests as needed

packages/router/test/bindings/fastify/cancel.spec.ts
=> [router] Add fastify cancel bindings unit test

packages/utils/src/gelato.ts
Mainnet is not integrated with gelato
I added the Mainnet endpoint
=> Added Mainnet endpoint

packages/txservice/src/dispatch.ts, packages/txservice/src/error.ts, packages/txservice/src/provider.ts, packages/txservice/src/types.ts
=> [txservice] Hotfix: remove intermediary type TransactionError

packages/router/src/lib/helpers/shared.ts
=> Fix wrong mapping

packages/router/src/bindings/contractReader/index.ts
- update: logger text and cleanup
- update naming
=> [router] log fixes (!minor)

packages/sdk/src/error.ts, packages/sdk/src/sdk.ts, packages/sdk/src/sdkBase.ts, packages/sdk/src/utils.ts, packages/sdk/test/unit/sdk.spec.ts, packages/sdk/test/unit/sdkBase.spec.ts
- new: method for wallet nonce and transactionId.
- update: transactionId generation
- fix: unit test
closes #603
=> [sdk] generate transactionId and update errors

packages/router/package.json, packages/router/src/bindings/prices/index.ts, packages/router/test/bindings/prices/index.spec.ts
=> MainnetEquivalent for binding prices

CHANGELOG.md, packages/router/src/bindings/prices/index.ts
- `config.chainConfig` may not have `chainId`
- Handle undefined case
=> Undefined in logs

packages/sdk/src/sdkBase.ts
=> [sdk] hotfix passing txId allowed

CHANGELOG.md, packages/router/src/adapters/subgraph/index.ts, packages/sdk/src/sdk.ts, packages/sdk/src/sdkBase.ts, packages/sdk/src/subgraph/subgraph.ts, packages/utils/src/fallbackSubgraph.ts
=> [sdk] Generic subgraph query SDK method

packages/txservice/src/chainreader.ts
=> Hotfixes-cacheDuration

CHANGELOG.md, packages/router/src/adapters/subgraph/subgraph.ts, packages/router/src/bindings/contractReader/index.ts, packages/router/src/bindings/messaging/metaTxRequest.ts, packages/router/src/lib/entities/metrics.ts, packages/router/src/lib/helpers/metrics.ts, packages/router/src/lib/helpers/shared.ts, packages/router/test/lib/helpers/metrics.spec.ts, packages/utils/src/fallbackSubgraph.ts
- Dashboard isn't properly collecting metrics
- Fix metrics
=> Dashboard Fixes

packages/router/src/adapters/web3signer/index.ts, packages/router/src/config.ts, packages/sdk/src/transactionManager/transactionManager.ts, packages/txservice/src/config.ts, packages/txservice/src/shared/contracts.ts, packages/txservice/test/chainreader.spec.ts, packages/txservice/test/config.spec.ts, packages/txservice/test/shared/contracts.spec.ts, packages/txservice/test/shared/errors.spec.ts, packages/txservice/test/shared/syncProvider.spec.ts, packages/txservice/test/shared/transactionBuffer.spec.ts
=> Adding test cases for txservice

packages/router/src/adapters/contract/contract.ts, packages/router/src/lib/helpers/shared.ts, packages/router/test/lib/helpers/shared.spec.ts
- new: isRouterWhitelisted method
- add: check for migrate liquidity
- add: unit test
=> [router] sanity check for migrate liquidity, isRouterWhitelisted

packages/router/src/adapters/contract/contract.ts
=> [contracts] Hotfix: Fallback to txservice if all relayer options fail

CHANGELOG.md, packages/router/src/adapters/contract/contract.ts
- `cancel` sanitation check failing
- Fix typo for sanitation check
=> Should be cancel

packages/router/src/adapters/contract/contract.ts
=> Hotfix: add support for fallback to txservice for both cancel and fulfill

packages/router/src/lib/helpers/shared.ts
- Did not check if whitelist was still in place before checking if routers were approved
- Check whitelist, then fallback to approval status
=> Check ownership

packages/sdk/src/sdkBase.ts, packages/sdk/test/unit/sdkBase.spec.ts, packages/txservice/src/chainreader.ts, packages/utils/src/chainData.ts, packages/utils/src/gasEstimates.ts, packages/utils/src/gelato.ts
=> GasEstimates Per Chain

packages/contracts/package.json, packages/contracts/src/createRouter.ts, packages/contracts/test/router.spec.ts
- fix: typo
- new: create-router script all networks in one go.
=> router-script for multiple networks

packages/sdk/src/sdkBase.ts
=> weighted bid selection

packages/contracts/package.json, packages/contracts/src/whitelist.ts
=> ⚡️new: whitelist script

packages/router/test/lib/operations/metaTx.spec.ts, packages/sdk/src/sdkBase.ts, packages/sdk/test/unit/sdkBase.spec.ts
=> [sdk] reset history for contract writer mock fn

CHANGELOG.md, packages/contracts/test/router.spec.ts, packages/router/src/lib/operations/fulfill.ts, packages/utils/src/encode.ts, packages/utils/src/signatures.ts
- Router was hardcoding relayer fee to 0 when signing
- Use passed in relayer fee
=> Fix harcoded relayer fee

packages/router/src/lib/helpers/metrics.ts, packages/router/test/lib/helpers/metrics.spec.ts
=> Fixes of ConvertToUSD

packages/router/src/lib/operations/metaTx.ts
=> [router] prefer using relayer fee asset from metatx rc fulfill payload

packages/router/src/adapters/contract/contract.ts, packages/router/src/config.ts, packages/router/test/adapters/contract/contract.spec.ts, packages/router/test/adapters/web3signer/index.spec.ts, packages/router/test/config.spec.ts
=> added unit tests

packages/contracts/hardhat.config.ts, packages/contracts/src/tasks/removeRelayerFee.ts
- new: task for remove relayer fee
- add: task to config
=> remove relayer fee

packages/contracts/test/router.spec.ts, packages/router/src/adapters/contract/contract.ts, packages/router/src/adapters/contract/index.ts, packages/router/src/bindings/fastify/index.ts, packages/router/src/lib/helpers/shared.ts, packages/txservice/src/chainreader.ts, packages/utils/src/gasEstimates.ts, packages/utils/src/messaging.ts, packages/utils/src/signatures.ts, packages/utils/src/transactionManager.ts
=> Add infra for remove liq

CHANGELOG.md, packages/router/src/lib/operations/auction.ts, packages/router/src/lib/operations/cancel.ts
- Not properly checking min relayer fee on contracts
- Check if it's a contract or if it's an EOA
=> Gas checks

packages/router/src/lib/operations/cancel.ts, packages/txservice/src/chainreader.ts
=> [router] Hotfix: use correct cancel chain for calculating gas fee

CHANGELOG.md, packages/router/src/adapters/subgraph/index.ts, packages/sdk/src/subgraph/subgraph.ts, packages/utils/src/fallbackSubgraph.ts, packages/utils/src/subgraphHealth.ts
=> Proper subg health URL

packages/contracts/hardhat.config.ts, packages/router/src/lib/helpers/shared.ts, packages/router/test/adapters/contract/contract.spec.ts, packages/router/test/lib/helpers/shared.spec.ts
- Allow cancel if expired
- Try to fix CI
=> local solc

packages/router/src/lib/helpers/shared.ts, packages/router/test/adapters/contract/contract.spec.ts, packages/router/test/lib/helpers/shared.spec.ts
=> Allow cancel if expired

packages/router/test/adapters/subgraph/subgraph.spec.ts, packages/router/test/adapters/web3signer/index.spec.ts
=> add tests to router/subgragh

packages/txservice/test/chainreader.spec.ts, packages/utils/src/gasEstimates.ts
=> Update hardcoded gasEstimates

CHANGELOG.md, packages/utils/src/gelato.ts, packages/utils/test/gelato.spec.ts
Not properly checking gelato chains.
Check Gelato chains.
=> Check Gelato chains properly

CHANGELOG.md, packages/contracts/package.json, packages/router/package.json, packages/router/src/lib/operations/status.ts, packages/router/src/router.ts, packages/router/test/globalTestHook.ts, packages/router/test/lib/operations/status.spec.ts, packages/router/test/router.spec.ts, packages/sdk-server/package.json, packages/sdk/package.json, packages/txservice/package.json, packages/utils/package.json, packages/utils/src/messaging.ts, yarn.lock
=> add: sanity check for router contract

CHANGELOG.md, packages/router/src/adapters/cache/auction.ts, packages/router/src/adapters/cache/index.ts, packages/router/src/adapters/contract/contract.ts, packages/router/src/adapters/contract/index.ts, packages/router/src/adapters/subgraph/index.ts, packages/router/src/adapters/subgraph/subgraph.ts, packages/router/src/bindings/contractReader/index.ts, packages/router/src/bindings/fastify/index.ts, packages/router/src/config.ts, packages/router/src/lib/entities/auctionCache.ts, packages/router/src/lib/entities/cache.ts, packages/router/src/lib/errors/auction.ts, packages/router/src/lib/helpers/auction.ts, packages/router/src/lib/helpers/index.ts, packages/router/src/lib/operations/auction.ts, packages/router/src/lib/operations/metaTx.ts, packages/router/src/router.ts, packages/router/test/adapters/cache/auction.spec.ts, packages/router/test/adapters/contract/contract.spec.ts, packages/router/test/globalTestHook.ts, packages/router/test/lib/helpers/shared.spec.ts, packages/router/test/lib/operations/auction.spec.ts, packages/router/test/lib/operations/prepare.spec.ts, packages/router/test/utils.ts
=> [router] Cache auction bids; prevent overbidding by checking current outstanding liquidity

packages/router/src/lib/helpers/metrics.ts
Metrics collection is erroring.
Add some try-catches.
=> Fix metrics error

CHANGELOG.md, packages/router/src/adapters/contract/contract.ts, packages/router/src/bindings/contractReader/index.ts, packages/router/src/bindings/messaging/metaTxRequest.ts, packages/router/src/lib/entities/metrics.ts, packages/router/src/lib/helpers/metrics.ts, packages/router/test/adapters/contract/contract.spec.ts, packages/router/test/lib/helpers/metrics.spec.ts, packages/utils/src/mock.ts
Metrics collection had a couple of problems:
- Gas was not being properly tracked on normal transactions
- Costs of the router relays was not being properly tracked on router-contract transactions
- Make sure to track gas consumed not gas units
- Move all `gasConsumed` updates to the contract writer
- Add a `relayerFeesPaid` counter to track fees paid to transaction relayers
=> Metrics update

packages/router/src/bindings/contractReader/index.ts
In ReceiverFulfilled status, routers need to wait for safe confirmations of fulfill transactions, not prepare transactions
=> Fix to determine transaction status

packages/contracts/src/whitelist.ts
- scale: whitelist spec
- update whitelist
=> whitelist script

packages/utils/src/gelato.ts
The gelato endpoints should be changed
They were changed
=> chore: Updated gelato endpoints

CHANGELOG.md, packages/contracts/src/whitelist.ts, packages/router/src/lib/helpers/metrics.ts, packages/router/test/lib/helpers/metrics.spec.ts
=> MainnetEquivalent for ConvertToUsd

CHANGELOG.md, packages/router/src/adapters/subgraph/analytics/graphqlsdk.ts, packages/router/src/adapters/subgraph/subgraph.ts, packages/router/src/lib/entities/metrics.ts, packages/router/src/lib/errors/metrics.ts, packages/router/src/lib/helpers/metrics.ts, packages/router/test/adapters/subgraph/subgraph.spec.ts, packages/router/test/lib/helpers/metrics.spec.ts, packages/router/test/lib/operations/fulfill.spec.ts
=> Fix dashboard errors

CHANGELOG.md, packages/router/src/bindings/fastify/index.ts
=> Don't allow relayer for removeLiq

CHANGELOG.md, docker/router/Dockerfile
The current version of Alpine had security issues.
Update version.
=> Latest alpine

packages/utils/src/fallbackSubgraph.ts
=> [utils] Hotfix: add missing forward slash to subgraph endpoint url formation

packages/utils/src/gelato.ts
There was not an Gelato Relay on Optimism 
Deploy the Relay on Optimism :D
=> chore: Added optimism relay

packages/txservice/src/rpcProviderAggregator.ts
=> [txservice] Ignore absolute min gas price for arbitrum only

packages/sdk/src/subgraph/subgraph.ts, packages/sdk/src/transactionManager/transactionManager.ts, packages/sdk/src/types.ts
=> add: sdkBase signer address optional type string

packages/sdk/src/subgraph/subgraph.ts
=> hotfix: subgraph polling

packages/sdk/src/subgraph/subgraph.ts
=> [sdk] remove promise before interval

packages/contracts/deploy/deploy.ts
=> Moonbeam Deployments

packages/sdk/src/subgraph/subgraph.ts
=> fix: polling not active

package.json, packages/auctioneer/ops/start-redis.docker-compose.yml, packages/auctioneer/package.json, packages/auctioneer/src/adapters/RedisStoreManager.ts, packages/auctioneer/src/createAuctioneer.ts, packages/auctioneer/src/handlers/bid.ts, packages/auctioneer/src/index.ts, packages/auctioneer/src/lib/index.ts, packages/auctioneer/src/lib/types.ts, packages/auctioneer/test/bid.test.ts, packages/auctioneer/tsconfig.build.json, yarn.lock
=> Amarok auctioneer

packages/txservice/src/chainreader.ts
=> Fix for decimals

CHANGELOG.md, packages/txservice/src/chainreader.ts
=> Fix gelatoEstimation

packages/deployments/contracts/contracts/TransactionManager.sol, packages/deployments/contracts/contracts/test/TestWeth.sol, packages/deployments/contracts/test/transactionManager.spec.ts
=> 822 contract tests

.vscode/settings.json, packages/sdk/src/sdkBase.ts, packages/txservice/src/chainreader.ts
Gas fees were messed up from ETH to BSC on USDT.
Proper decimal accounting.
=> Fix gas fee calculation

packages/deployments/contracts/hardhat.config.ts, packages/deployments/contracts/package.json
=> add hardhat-upgrades

packages/deployments/contracts/contracts/ProposedOwnableUpgradeable.sol, packages/deployments/contracts/contracts/test/TestProposedOwnable.sol, packages/deployments/contracts/test/utils.ts
=> make ProposedOwnable to upgradeable

packages/deployments/contracts/.openzeppelin/unknown-31337.json, packages/deployments/contracts/contracts/TransactionManager.sol, packages/deployments/contracts/contracts/lib/LibAsset.sol, packages/deployments/contracts/test/transactionManager.spec.ts
=> 817 upgradeable

packages/deployments/contracts/.openzeppelin/rinkeby.json, packages/deployments/contracts/deploy/deploy.ts, packages/deployments/contracts/src/tasks/mintTestToken.ts
=> 840 test upgradability - fix review

packages/deployments/contracts/contracts_forge/Connext.t.sol, packages/deployments/contracts/contracts_forge/RouterPermissionsManager.t.sol, packages/deployments/contracts/foundry.toml
=> 820 restricted router

.github/workflows/build-test-deploy-testnet.yml
=> [ops] separate builds

packages/agents/router/src/router.ts
=> 897 ping sequencer

ops/README.md, ops/modules/service/main.tf, ops/modules/service/variables.tf, ops/testnet/main.tf, ops/testnet/variables.tf
=> change HZ ID, domain name

.github/workflows/build-test-deploy-testnet.yml, ops/testnet/config.tf, ops/testnet/variables.tf
=> Pass infura key

ops/testnet/config.tf
=> update config schemas

packages/adapters/subgraph/src/lib/subgraphs/runtime/graphqlsdk.ts, packages/adapters/subgraph/src/lib/subgraphs/runtime/queries.ts, packages/deployments/contracts/src/tasks/executeEstimateGas.ts, packages/deployments/contracts/tsconfig.build.json, packages/deployments/subgraph/src/amarok-runtime-staging/abis/RouterPermissionsManagerLogic.json, packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-staging/schema.graphql, packages/deployments/subgraph/src/amarok-runtime-staging/subgraph.template.yaml, packages/deployments/subgraph/src/amarok-runtime-v0/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-v0/schema.graphql
=> Fix subg for canonical

packages/deployments/contracts/contracts/nomad-xapps/contracts/relayer-fee-router/RelayerFeeRouter.sol, packages/deployments/contracts/contracts_forge/RelayerFeeMessage.t.sol
closes #983 
Add a RelayerFeeMessage unit test
=> Add RelayerFeeMessage unit test

packages/adapters/subgraph/src/lib/subgraphs/runtime/graphqlsdk.ts, packages/adapters/subgraph/src/lib/subgraphs/runtime/queries.ts, packages/adapters/subgraph/src/reader.ts, packages/agents/router/src/bindings/cache/index.ts, packages/agents/router/src/bindings/subgraph/index.ts, packages/agents/router/src/lib/operations/execute.ts, packages/agents/router/test/bindings/cache/index.spec.ts, packages/deployments/contracts/src/tasks/xcall.ts
=> Update cache status

packages/adapters/cache/.nycrc.json, packages/adapters/cache/src/lib/caches/auctions.ts
=> Dedup the bids

packages/deployments/contracts/contracts_forge/Connext.t.sol, packages/deployments/contracts/contracts_forge/RouterPermissionsManager.t.sol
Subtask of https://github.com/connext/nxtp/issues/982
Updates the foundry unit tests to the Connext contract structure. I had to change how we were mocking some values in the contract with `stdstore.target().sig().with_key().checked_write()` because of some errors after updating the test to use ConnextHandler with proxy
=> Fix ConnextHandler foundry unit tests 

packages/adapters/txservice/src/chainreader.ts, packages/agents/sequencer/src/lib/operations/relayer.ts
=> Fix tx read

packages/adapters/subgraph/src/reader.ts, packages/agents/router/src/lib/errors/execute.ts, packages/agents/router/src/lib/operations/execute.ts, packages/agents/router/test/lib/operations/execute.spec.ts, packages/utils/src/types/xtransfers.ts
Router should check that it has sufficient asset balance before sending a bid for a transfer using that asset.
Fixes: #1019
=> [router] 1019 sufficient liquidity

packages/adapters/cache/src/lib/caches/transfers.ts, packages/adapters/cache/test/lib/caches/transfers.spec.ts, packages/adapters/subgraph/src/lib/helpers/parse.ts, packages/adapters/subgraph/src/reader.ts, packages/adapters/txservice/src/shared/contracts.ts, packages/agents/router/package.json, packages/agents/router/src/bindings/subgraph/index.ts, packages/agents/router/src/config.ts, packages/agents/sequencer/package.json, packages/agents/sequencer/src/config.ts, packages/deployments/contracts/deployments.json, packages/deployments/contracts/src/tasks/addRelayer.ts, yarn.lock
Staging was broke.
Fix staging.
=> Fix staging and local dev

packages/adapters/subgraph/src/lib/subgraphs/runtime/graphqlsdk.ts, packages/adapters/subgraph/src/lib/subgraphs/runtime/queries.ts, packages/adapters/subgraph/src/reader.ts, packages/agents/relayer/src/relayer.ts, packages/agents/router/src/bindings/cache/index.ts, packages/agents/router/src/bindings/subgraph/index.ts, packages/agents/router/test/bindings/cache/index.spec.ts, packages/agents/router/test/bindings/subgraph/index.spec.ts, packages/agents/router/test/mock.ts, packages/agents/sequencer/src/lib/operations/auctions.ts, packages/agents/sequencer/test/globalTestHook.ts, packages/agents/sequencer/test/lib/operations/auctions.spec.ts, packages/agents/sequencer/test/mock.ts, packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-staging/schema.graphql, packages/deployments/subgraph/src/amarok-runtime-v0/schema.graphql, packages/integration/test/constants.ts, packages/utils/src/types/xtransfers.ts, yarn.lock
=> 967 subgraph optimization

ops/testnet/staging/core/config.tf
=> Remove unused subgraph config

packages/agents/backend/poller/package.json, packages/agents/backend/poller/test/adapters/database/client.spec.ts, packages/agents/backend/poller/test/lib/operations/config.spec.ts, packages/agents/backend/poller/test/lib/operations/transfers.spec.ts, yarn.lock
Tests were not following our guidelines.
Fixed tests.
=> Test fixes

packages/deployments/contracts/contracts/diamond/Connext.sol, packages/deployments/contracts/contracts/diamond/facets/ProposedOwnableFacet.sol, packages/deployments/contracts/contracts/diamond/facets/nomad-core/RouterFacet.sol, packages/deployments/contracts/contracts/diamond/facets/nomad-core/XAppConnectionClientFacet.sol, packages/deployments/contracts/contracts/diamond/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts/diamond/utils/Modifiers.sol
=> AppStorage Pattern

packages/deployments/contracts/contracts/diamond/facets/ProposedOwnableFacet.sol, packages/deployments/contracts/contracts/diamond/facets/nomad-core/RouterFacet.sol, packages/deployments/contracts/contracts/diamond/facets/nomad-core/XAppConnectionClientFacet.sol, packages/deployments/contracts/contracts/diamond/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts/diamond/utils/Modifiers.sol, packages/deployments/contracts/contracts/diamond/utils/ReentrancyGuard.sol
=> Add ReentrancyGuard to diamond utils

packages/deployments/contracts/contracts/diamond/Connext.sol, packages/deployments/contracts/contracts/diamond/facets/RouterPermissionsFacet.sol, packages/deployments/contracts/contracts/diamond/libraries/LibConnextStorage.sol
=> Diamond architecture router permission facet

packages/deployments/contracts/contracts/diamond/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/diamond/facets/ProposedOwnableFacet.sol
Add BridgeFacet with the bridge related functions from ConnextHandler and ConnextLogic:
- xcall
- handle
- execute
- bumpTransfer
=> Add BridgeFacet

packages/deployments/contracts/contracts/diamond/facets/RelayerFacet.sol
Add RelayerFacet with the relayer related functions from ConnextHandler and ConnextLogic:
- addRelayer
- removeRelayer
- initiateClaim
- claim
=> Add RelayerFacet

packages/deployments/contracts/contracts/diamond/facets/AssetFacet.sol
Add AssetFacet with the asset related functions from ConnextHandler and ConnextLogic: 
- addStableSwapPool
- setupAsset
- removeAssetId
=> Add AssetFacet

ops/testnet/prod/backend/config.tf, ops/testnet/staging/backend/config.tf, packages/agents/backend/poller/src/backend.ts, packages/agents/backend/poller/src/lib/operations/transfers.ts, packages/deployments/contracts/hardhat.config.ts
- Config needed to be environment aware.
- Need to poll for reconciled txs.
=> Backend updates

packages/deployments/contracts/contracts/diamond/facets/AssetFacet.sol, packages/deployments/contracts/contracts/diamond/facets/BaseConnextFacet.sol, packages/deployments/contracts/contracts/diamond/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/diamond/facets/ProposedOwnableFacet.sol, packages/deployments/contracts/contracts/diamond/facets/RelayerFacet.sol, packages/deployments/contracts/contracts/diamond/facets/RoutersFacet.sol, packages/deployments/contracts/contracts/diamond/facets/nomad-core/NomadRouterFacet.sol, packages/deployments/contracts/contracts/diamond/facets/nomad-core/XAppConnectionClientFacet.sol, packages/deployments/contracts/contracts/diamond/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts/diamond/upgradeInitializers/DiamondInit.sol
…getters
- Initialize storage with DiamondInit
- Add BaseConnextFacet replacing Modifiers
- Add public getters for storage public variables
=> Initialize + Base + Getters

packages/adapters/subgraph/README.md
=> Create readme for nxtp-adapter-subgraph

.github/workflows/build-test-deploy-testnet.yml, ops/testnet/prod/backend/main.tf, ops/testnet/prod/backend/variables.tf, ops/testnet/prod/core/config.tf, ops/testnet/prod/core/variables.tf, ops/testnet/staging/backend/main.tf, ops/testnet/staging/backend/variables.tf, ops/testnet/staging/core/config.tf, ops/testnet/staging/core/main.tf, ops/testnet/staging/core/variables.tf, packages/agents/lighthouse/config.json.example
=> lighthouse terraform

packages/agents/router/src/lib/errors/execute.ts, packages/agents/router/src/lib/operations/execute.ts, packages/agents/router/test/lib/operations/execute.spec.ts, packages/agents/router/test/mock.ts, packages/agents/sequencer/src/lib/operations/auctions.ts, packages/utils/src/mocks/mock.ts
=> Add sanity check for router code

.github/workflows/build-test-deploy-testnet.yml
=> Prod workflow

packages/deployments/contracts/contracts/interfaces/ISponsorVault.sol
Improves `ISponsorVault` interface by adding deposits and withdrawals
Fixes #1175 
#1069
=> Add deposits and withdrawals to the vault interface

packages/deployments/contracts/contracts/facets/StableSwapFacet.sol, packages/deployments/contracts/contracts/libraries/AmplificationUtils.sol, packages/deployments/contracts/contracts/libraries/AssetLogic.sol, packages/deployments/contracts/contracts/libraries/SwapUtils.sol, packages/deployments/contracts/deploy/05_deployDiamond.ts, packages/deployments/contracts/test/connext.spec.ts, packages/deployments/contracts/test/stableswap.spec.ts
=> made all libs internal

packages/deployments/contracts/src/tasks/stableswap/addStableLiquidity.ts, packages/deployments/contracts/src/tasks/stableswap/initializeSwap.ts, packages/deployments/contracts/src/tasks/stableswap/removeStableLiquidity.ts
=> stable swap tasks

packages/deployments/contracts/contracts/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/interfaces/IExecutor.sol, packages/deployments/contracts/contracts/interpreters/Executor.sol, packages/deployments/contracts/contracts/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts_forge/Connext.t.sol, packages/deployments/contracts/contracts_forge/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/interpreters/Executor.t.sol
`Executor.execute` gracefully handles failures and forwards to recovery address.
If the provided `callData` fails, funds will now automatically be sent to a `recovery` address on the destination domain.
Fixes #1081
=> 1081 error handling

packages/adapters/subgraph/.graphclient/index.ts, packages/adapters/subgraph/.graphclient/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Test_Goerli/introspectionSchema.ts, packages/adapters/subgraph/.graphclient/sources/Connext_Test_Goerli/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Test_Kovan/introspectionSchema.ts, packages/adapters/subgraph/.graphclient/sources/Connext_Test_Kovan/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Test_Rinkeby/introspectionSchema.ts, packages/adapters/subgraph/.graphclient/sources/Connext_Test_Rinkeby/schema.graphql, packages/adapters/subgraph/.graphclientrc.yml, packages/adapters/subgraph/src/lib/helpers/create.ts, packages/adapters/subgraph/src/reader.ts, packages/agents/backend/poller/src/backend.ts, packages/agents/backend/poller/src/config.ts, packages/agents/router/src/config.ts, packages/agents/router/src/router.ts, packages/agents/sequencer/src/config.ts, packages/agents/sequencer/src/lib/entities/config.ts, packages/agents/sequencer/src/sequencer.ts, packages/deployments/subgraph/config/amarok-runtime-test.json, packages/integration/test/integration.spec.ts
=> Add test subgraphs

packages/deployments/contracts/contracts/facets/BridgeFacet.sol
=> fix double spend token

packages/deployments/contracts/contracts/facets/AssetFacet.sol, packages/deployments/contracts/contracts_forge/Mock.sol, packages/deployments/contracts/contracts_forge/facets/AssetFacet.t.sol, yarn.lock
Contract unit tests for AssetFacet.sol.
Small bugfix in `removeAssetId` : deleting entry from `canonicalToAdopted`
Testing
Completes #1051
=> AssetFacet unit tests

packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts/core/promise/PromiseRouter.sol, packages/deployments/contracts/contracts_forge/core/promise/PromiseRouter.t.sol, packages/deployments/contracts/contracts_forge/utils/Mock.sol
=> 1256 promise router hash

CHANGELOG.md, package.json, packages/adapters/cache/package.json, packages/adapters/subgraph/package.json, packages/adapters/txservice/package.json, packages/adapters/web3signer/package.json, packages/agents/relayer/package.json, packages/agents/router/package.json, packages/agents/sdk/package.json, packages/agents/sdk/src/sdkUtils.ts, packages/agents/sequencer/package.json, packages/deployments/contracts/package.json, packages/deployments/subgraph/package.json, packages/integration/package.json, packages/utils/package.json
=> New release

packages/agents/sdk/.nycrc.json, packages/agents/sdk/package.json, packages/agents/sdk/src/index.ts, packages/agents/sdk/src/lib/errors/index.ts, packages/agents/sdk/src/lib/helpers/shared.ts, packages/agents/sdk/src/sdk.ts, packages/agents/sdk/src/sdkBase.ts, packages/agents/sdk/src/sdkRouter.ts, packages/agents/sdk/src/sdkUtils.ts, packages/agents/sdk/test/sdk.spec.ts, packages/agents/sdk/test/sdkBase.spec.ts, packages/agents/sdk/test/sdkRouter.spec.ts, packages/agents/sdk/test/sdkUtils.spec.ts, packages/utils/src/mocks/mock.ts
=> [sdk] 1186 unit test

packages/agents/router/src/bindings/cache/index.ts
=> Parallelize loops

packages/deployments/contracts/tasks/renounceOwnership.ts
`renounceOwnership` task did not check if ownership had already been renounced, and had bugs when calculating the delays required,
When you run `renounceOwnership` it will handle the following problems gracefully:
- The delay has not elapsed, but renunciation is proposed
- The renunciation has already occurred
N/A
=> fix: add already renounced check

.gitmodules, packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol, packages/deployments/contracts/contracts/nomad-core/libs/ExcessivelySafeCall.sol, packages/deployments/contracts/package.json, packages/deployments/contracts/remappings.txt, yarn.lock
Uses the [`ExcessivelySafeCall`](https://github.com/nomad-xyz/ExcessivelySafeCall/blob/main/src/ExcessivelySafeCall.sol) library to limit malicious calldata on `Executor.call`
Fixes #1178
=> 1178 safe call

packages/agents/sequencer/src/lib/operations/auctions.ts, packages/agents/sequencer/test/lib/operations/auctions.spec.ts
=> Check if has been executed

ops/modules/daemon/main.tf, ops/modules/service/main.tf, ops/testnet/prod/backend/main.tf, ops/testnet/prod/core/main.tf, ops/testnet/staging/backend/variables.tf
=> Fluent bit & DD logs integration

ops/modules/daemon/main.tf, ops/testnet/staging/backend/variables.tf, ops/testnet/staging/core/variables.tf
=> Dd logs integration

packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-v0/mapping.ts
=> Handle router's liquidity when the transfer gets executed/reconciled

packages/adapters/subgraph/src/lib/operations/queries.ts, packages/adapters/subgraph/src/reader.ts, packages/agents/cartographer/poller/src/adapters/database/client.ts, packages/agents/cartographer/poller/src/adapters/database/index.ts, packages/agents/cartographer/poller/src/lib/operations/transfers.ts, packages/agents/cartographer/poller/test/adapters/database/client.spec.ts, packages/agents/cartographer/poller/test/lib/operations/transfers.spec.ts, packages/utils/src/peripherals/subgraph.ts, yarn.lock
=> 1313 subg query

docker/cartographer/docker-entrypoint.sh
Fix CLI params in docker entrypoint script.
Fixes 
https://github.com/connext/nxtp/issues/1355
=> Fix pm2 CLI for docker startup

docker/cartographer/Dockerfile
Install pm2 globally with npm, so that it is available via docker CLI.
`./docker-entrypoint.sh: line 5: pm2: not found`
Fixes
=> Install pm2 with npm

packages/deployments/contracts/contracts/core/promise/PromiseRouter.sol, packages/deployments/contracts/contracts/core/promise/libraries/PromiseMessage.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/core/promise/PromiseRouter.t.sol
Unit tests for promise router
Adds `PromiseRouter` unit test coverage.
Fixes #1044 
Parent #822 
Based on #1240
=> PromiseRouter unit tests

packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/AssetFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/FacetHelper.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/RoutersFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/AssetLogic.t.sol, packages/deployments/contracts/contracts_forge/utils/Mock.sol
=> AssetLogic unit tests

packages/deployments/contracts/contracts/core/connext/facets/RelayerFacet.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/RelayerFacet.t.sol, yarn.lock
Unit tests for RelayerFacet
Test the interface relayers will use for claiming fees xchain
- Unit tests
Fixes: #822
=> RelayerFacet unit tests

packages/deployments/contracts/contracts/core/connext/facets/upgrade-initializers/DiamondInit.sol
=> set flag initialized when first deployed

packages/deployments/contracts/contracts/core/connext/facets/BaseConnextFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/ProposedOwnableFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/StableSwapFacet.sol, packages/deployments/contracts/contracts/core/connext/interfaces/IConnextHandler.sol, packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/RelayerFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/AssetLogic.t.sol, packages/deployments/contracts/contracts_forge/utils/Deployer.sol
- Do not have granular / functional pausing
- Instead, pause everything except adding liquidity to AMM and `handle` on `pause`
- Add `Pausable` events and interfaces to ownership facet
- Ensure only `addLiquidity` for AMM works on pause
N/A
N/A
=> Everything paused

packages/deployments/contracts/contracts_forge/core/connext/libraries/AmplificationUtils.t.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/AssetLogic.t.sol
=> AmplificationUtils unit tests

packages/deployments/contracts/contracts_forge/core/connext/libraries/MathUtils.t.sol
=> MathUtils unit tests

packages/deployments/contracts/contracts/core/connext/helpers/ConnextPriceOracle.sol, packages/deployments/contracts/contracts_forge/core/connext/helpers/ConnextPriceOracle.t.sol
=> ConnextPriceOracle unit test in foundry

packages/deployments/contracts/contracts_forge/core/connext/helpers/LPToken.t.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/MathUtils.t.sol
=> LPToken Unit Tests

packages/adapters/subgraph/src/lib/operations/queries.ts, packages/agents/cartographer/poller/cartographer.config.js, packages/agents/cartographer/poller/src/adapters/database/client.ts, packages/agents/cartographer/poller/src/lib/operations/transfers.ts
=> Prod release to fix carto again.

packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/RoutersFacet.t.sol
Adds remainder of router facet unit tests.
Unit tests
Fixes #1328
=> 1328 routers facet

packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-v0/mapping.ts
Bring mapping inline with onchain changes made [here](https://github.com/connext/nxtp/commit/51400520a1247b3965178652e97448912ccefa5d)
- Only update router balance if transfer already reconciled
Fixes #1407
=> only update if not reconciled

packages/agents/router/src/lib/entities/context.ts, packages/agents/router/src/lib/operations/execute.ts, packages/agents/router/src/router.ts
=> Refactor nomadContext

packages/agents/router/src/router.ts
=> Nomad-SDK RPC setup

CHANGELOG.md, packages/txservice/src/chainreader.ts
=> Exclude arbitrum from gelatoFee calculation

packages/txservice/src/chainreader.ts
=> Hotfix exclude list

packages/deployments/contracts/contracts/core/connext/facets/AssetFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/upgrade-initializers/DiamondInit.sol, packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibDiamond.sol
Fixes 2s from code arena
See commits and code arena repo
=> 2 code arena

packages/deployments/contracts/contracts/test/Connext.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/LibDiamond.sol
=> LibDiamond initialize test

packages/agents/cartographer/poller/src/adapters/database/index.ts, packages/agents/cartographer/poller/src/routersPoller.ts, packages/agents/cartographer/poller/src/transfersPoller.ts
Add graceful exit to cartographer
Fixes 
https://github.com/connext/nxtp/issues/1458
=> Add graceful exit to cartographer

packages/deployments/contracts/contracts/core/connext/helpers/ConnextPriceOracle.sol, packages/deployments/contracts/contracts/test/TestAggregator.sol, packages/deployments/contracts/contracts_forge/core/connext/helpers/ConnextPriceOracle.t.sol, packages/deployments/contracts/test/connextPriceOracle.spec.ts
=> Additional validation for priceoracle

.vscode/settings.json, packages/deployments/contracts/contracts/core/connext/facets/BaseConnextFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/NomadFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/PortalFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/ProposedOwnableFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/RelayerFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol, packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol, packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts/core/promise/PromiseRouter.sol, packages/deployments/contracts/contracts/core/relayer-fee/RelayerFeeRouter.sol, packages/deployments/contracts/contracts/core/shared/XAppConnectionClient.sol, packages/deployments/contracts/contracts_forge/Connext.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/NomadFacet.t.sol
=> QA code arena

packages/adapters/txservice/src/shared/contracts.ts, packages/agents/sdk/src/config.ts, packages/agents/sdk/src/sdkPool.ts
Fixes for grabbing wrong deployments.
- Skip external StableSwap contract deployment check
- Needed to fetch the proxy of TokenRegistry contract
=> Sdk deployments

CHANGELOG.md, package.json, packages/adapters/cache/package.json, packages/adapters/subgraph/package.json, packages/adapters/txservice/package.json, packages/adapters/txservice/src/shared/contracts.ts, packages/adapters/web3signer/package.json, packages/agents/cartographer/poller/package.json, packages/agents/lighthouse/package.json, packages/agents/relayer/package.json, packages/agents/router/package.json, packages/agents/sdk/package.json, packages/agents/sdk/src/config.ts, packages/agents/sdk/src/sdkPool.ts, packages/agents/sequencer/package.json, packages/deployments/contracts/package.json, packages/deployments/subgraph/package.json, packages/integration/package.json, packages/utils/package.json
=> SDK release

packages/utils/src/mocks/mock.ts, packages/utils/src/types/db.ts
xcall_relayer_fee -> relayer_fee rename
=> Update relayer_fee name

README.md
=> Improving root level readme

docker/cartographer/routers/docker-entrypoint.sh
=> Revert DB rollbacks

ops/env/testnet/core/secrets.prod.json, ops/env/testnet/core/secrets.staging.json, ops/modules/rmq/main.tf, ops/modules/rmq/variables.tf, ops/testnet/staging/backend/main.tf, ops/testnet/staging/backend/variables.tf, ops/testnet/staging/core/config.tf, ops/testnet/staging/core/main.tf, ops/testnet/staging/core/variables.tf
=> secrets and fixes

packages/deployments/contracts/deploy/00_deployNomadCore.ts, packages/integration/test/local.spec.ts
=> add automine for deployments for local chains

packages/deployments/contracts/contracts/core/connext/libraries/SwapUtils.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/SwapUtils.t.sol
=> fix _calculateSwapInv func

packages/agents/router/.nycrc.json, packages/agents/router/src/errors/execute.ts, packages/agents/router/src/subscriber/bindings/messageQueue/index.ts, packages/agents/router/src/subscriber/operations/execute.ts, packages/agents/router/test/subscriber/operations/execute.spec.ts
=> Sanity checks

ops/testnet/prod/core/config.tf, ops/testnet/prod/core/main.tf, ops/testnet/prod/core/variables.tf
=> Prod configs

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/PortalFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol, packages/deployments/contracts/contracts/core/connext/helpers/Executor.sol, packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/AssetLogic.t.sol
=> Spearbit-65

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/helpers/SponsorVault.sol, packages/deployments/contracts/contracts/core/connext/interfaces/ISponsorVault.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol
=> Spearbit-37,53

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/helpers/SponsorVault.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol
Fixes Spearbit #25
https://github.com/spearbit-audits/connext/issues/25
=> Spearbit 25

ops/testnet/prod/core/config.tf, ops/testnet/prod/core/main.tf, ops/testnet/staging/core/config.tf, packages/agents/sequencer/src/config.ts
- Health checks for `sequencer-subscriber` should work
- Scale up  `sequencer-subscriber`
- Scale up  `router-subscriber`
=> Cherry pick prod hot fix

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
https://github.com/spearbit-audits/connext/issues/63
=> Spearbit-63: add recommended checks to `xcall`

packages/agents/sdk/package.json, packages/agents/sdk/src/sdkBase.ts, packages/agents/sdk/test/sdkBase.spec.ts
=> Calculate relayerFee in xcall

packages/adapters/subgraph/src/lib/operations/queries.ts, packages/agents/router/src/publisher/operations/getXCalls.ts, packages/utils/src/peripherals/subgraph.ts
Routers don't need to pick up forceSlow transfers
Fixes
=> add forceslow to metaQueryParams

packages/deployments/contracts/contracts/core/connext/libraries/LibDiamond.sol
Fixes https://github.com/spearbit-audits/connext/issues/68
- Ensures diamond cuts are only valid for a week
- Prevents diamond cuts from being replayed without going through proposal flow
Fixes https://github.com/spearbit-audits/connext/issues/68
=> Spearbit 68

ops/testnet/prod/core/main.tf, ops/testnet/staging/core/main.tf
sequencer-subscriber task memory increased by 100%
Fixes 
https://github.com/connext/nxtp/issues/1590
=> Increase seq-sub memory

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts_forge/Connext.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/NomadFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/PortalFacet.t.sol
Fixes https://github.com/spearbit-audits/connext/issues/43
- Rename `slippageBoundary` to `destinationMinOut`
- Add `originMinOut` to `xcall`
Fixes https://github.com/spearbit-audits/connext/issues/43
=> Spearbit 43

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/PortalFacet.t.sol
Fixes https://github.com/spearbit-audits/connext/issues/55
- Update `slippageTol` to be an absolute amount
- Rename `slippageTol` to `slippageBoundary`
NOTE: This will be coupled with a fix to add two separate slippage constants.
Fixes https://github.com/spearbit-audits/connext/issues/55
=> Spearbit 55

packages/deployments/contracts/contracts/core/promise/PromiseRouter.sol
https://github.com/spearbit-audits/connext/issues/38
=> Spearbit-38: allow return data to be empty in PromiseRouter callback

packages/deployments/contracts/contracts/core/connext/libraries/SwapUtils.sol
Fixes 
https://github.com/spearbit-audits/connext/issues/59
=> gas optimization

packages/agents/sdk/src/config.ts, packages/integration/test/local.spec.ts
=> Check transferStatus using nxtp-sdk in local e2e

packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol
Fixes https://github.com/spearbit-audits/connext/issues/32
- Update comment
Fixes https://github.com/spearbit-audits/connext/issues/32
=> fix: comment

packages/deployments/contracts/contracts/core/connext/facets/NomadFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/PortalFacet.sol, packages/deployments/contracts/contracts_forge/Connext.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/NomadFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/PortalFacet.t.sol
Fixes https://github.com/spearbit-audits/connext/issues/34
**NOTE:** Depends on #1585 being merged
- Adds dust accounting in `onReceive`
Fixes https://github.com/spearbit-audits/connext/issues/34
Fixes https://github.com/spearbit-audits/connext/issues/34
=> Spearbit 34: onReceive dust

packages/deployments/contracts/contracts/core/connext/facets/NomadFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/PortalFacet.sol, packages/deployments/contracts/contracts_forge/Connext.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/NomadFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/PortalFacet.t.sol
Fixes:
- https://github.com/spearbit-audits/connext/issues/44
- https://github.com/spearbit-audits/connext/issues/46
- https://github.com/spearbit-audits/connext/issues/71
Portals will no longer be automatically attempted to be repaid on `reconcile`. Instead, you must always repay the portal loan out of band. This eliminates complexity, and does not substantially increase trust as if anything went wrong with the portal repayment (i.e. slippage too high on swap into adopted asset), the router must be trusted to close out the position out of band.
Fixes:
- https://github.com/spearbit-audits/connext/issues/44
- https://github.com/spearbit-audits/connext/issues/46
- https://github.com/spearbit-audits/connext/issues/71
=> Spearbit 44 46 71

packages/deployments/contracts/contracts/core/shared/Router.sol
Fixes https://github.com/spearbit-audits/connext/issues/35
- Adds a `bytes32(0)` check to the `_isRemoteRouter` check
Fixes https://github.com/spearbit-audits/connext/issues/35
=> spearbit 35: add 0 check

packages/deployments/contracts/contracts/core/connext/facets/StableSwapFacet.sol
Fixes https://github.com/spearbit-audits/connext/issues/40
- Removes `payable` keyword from `swapExact` and `swapExactOut`
Fixes https://github.com/spearbit-audits/connext/issues/40
=> fix: remove payable

packages/deployments/contracts/contracts/core/connext/helpers/SponsorVault.sol
Fixes https://github.com/spearbit-audits/connext/issues/41
- Ensure `SponsorVault` will emit a `Deposit` event when ETH and ERC20 are sent as a payment
Fixes https://github.com/spearbit-audits/connext/issues/41
=> fix: events for token + eth

packages/deployments/contracts/contracts/core/connext/helpers/SponsorVault.sol
Fixes https://github.com/spearbit-audits/connext/issues/48
- Only reimburse fees *up to* the `relayerFeeCap`
Fixes https://github.com/spearbit-audits/connext/issues/48
=> Spearbit 48: reimburse up to cap

packages/deployments/contracts/contracts/core/connext/helpers/Multicall.sol
Fixes https://github.com/spearbit-audits/connext/issues/50
- Make sure `Multicall` is read-only
Fixes https://github.com/spearbit-audits/connext/issues/50
=> Spearbit 50

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/PortalFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/RelayerFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/SwapAdminFacet.sol, packages/deployments/contracts/contracts/core/connext/helpers/SponsorVault.sol, packages/deployments/contracts/contracts/core/connext/helpers/StableSwap.sol, packages/deployments/contracts/contracts/core/promise/PromiseRouter.sol
Fix https://github.com/spearbit-audits/connext/issues/62
- Adds `nonReentrant` modifier to functions that manipulate values
Fixes https://github.com/spearbit-audits/connext/issues/62
=> spearbit 62: reentrancy

packages/deployments/contracts/contracts/core/connext/facets/BaseConnextFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
Fixes https://github.com/spearbit-audits/connext/issues/20
- Renames `EMPTY` constant in `BaseConnextFacet` to `EMPTY_HASH`
Fixes https://github.com/spearbit-audits/connext/issues/20
=> spearbit 20

packages/deployments/contracts/contracts/core/connext/libraries/LibDiamond.sol
Fixes https://github.com/spearbit-audits/connext/issues/69
- Uses flag instead of (unreliable) storage check on the facet lengths
Fixes https://github.com/spearbit-audits/connext/issues/69
=> fix: add flag instead of facet length check

packages/deployments/contracts/contracts/core/connext/helpers/ConnextPriceOracle.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/RoutersFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/helpers/ConnextPriceOracle.t.sol, packages/deployments/contracts/contracts_forge/core/promise/PromiseRouter.t.sol
Fixes https://github.com/spearbit-audits/connext/issues/77
- Makes the `ConnextPriceOracle` inherit the `ProposedOwnable` structure
Fixes https://github.com/spearbit-audits/connext/issues/77
=> Spearbit 77: oracle 2 step ownership

packages/agents/lighthouse/src/lib/helpers/index.ts, packages/agents/lighthouse/src/lib/helpers/relayer.ts, packages/agents/lighthouse/src/lib/operations/cartographer.ts, packages/agents/lighthouse/src/lib/operations/execute.ts, packages/agents/lighthouse/src/lib/operations/relayer.ts, packages/agents/lighthouse/test/lib/operations/relayer.spec.ts
=> fix lighthouse logs

packages/deployments/contracts/contracts/core/connext/facets/BaseConnextFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/ProposedOwnableFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol, packages/deployments/contracts/contracts/core/connext/interfaces/IConnextHandler.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/ProposedOwnableFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/RoutersFacet.t.sol, packages/deployments/contracts/contracts_forge/utils/Deployer.sol
Fixes https://github.com/spearbit-audits/connext/issues/36
- Rename `assetOwnership` -> `assetWhitelist`
- Rename `routerOwnership` -> `routerWhitelist`
- Rename `_amount` to `_amountOut` in `_handleExecuteTransaction`
- Rename `transactingAssetId` to `assetIn` in `xcall`
Fixes https://github.com/spearbit-audits/connext/issues/36
=> Spearbit 36

packages/deployments/contracts/tasks/stableswap/initializeSwap.ts
Fixes https://github.com/spearbit-audits/connext/issues/33 (by adding a comment, true automated fix has to come when these scripts are overhauled).
- Add comment to ensure `setDetails` is called before initializing a stable swap pool
Fixes https://github.com/spearbit-audits/connext/issues/33
=> Spearbit 33

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/interfaces/IConnextHandler.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts_forge/Connext.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/utils/Deployer.sol
See https://github.com/spearbit-audits/connext/issues/72
Adding a sequencer signature requirement, as well as a whitelist for sequencers to resolve this issue
=> Spearbit-72: Require a signature from a whitelisted Sequencer agent in execute fast liquidity route

packages/deployments/contracts/contracts/nomad-core/libs/TypedMemView.sol
Fixes https://github.com/spearbit-audits/connext/issues/79
- Use correct adjustment for `words` function
Fixes https://github.com/spearbit-audits/connext/issues/79
=> Spearbit 79: off by 1

packages/deployments/contracts/contracts/core/connext/libraries/SwapUtilsExternal.sol
Fixes 
https://github.com/spearbit-audits/connext/issues/59
=> Spearbit-59

packages/deployments/contracts/contracts/core/connext/libraries/SwapUtils.sol, packages/deployments/contracts/contracts/core/connext/libraries/SwapUtilsExternal.sol
Fixes 
https://github.com/spearbit-audits/connext/issues/58
=> Spearbit 58

packages/agents/sdk/src/sdkPool.ts, packages/examples/sdk-server/examples/index.http, packages/examples/sdk-server/src/pool.ts, packages/examples/sdk-server/src/types/api.ts
=> Fix sdk pool function()

packages/deployments/contracts/contracts/core/connext/helpers/ConnextPriceOracle.sol, packages/deployments/contracts/contracts/core/connext/helpers/PriceOracle.sol, packages/deployments/contracts/contracts_forge/core/connext/helpers/ConnextPriceOracle.t.sol
Fix https://github.com/spearbit-audits/connext/issues/95
Fixes 
https://github.com/spearbit-audits/connext/issues/95
=> Spearbit 95

packages/deployments/contracts/contracts/core/connext/helpers/ConnextPriceOracle.sol
Fixes 
https://github.com/spearbit-audits/connext/issues/87
=> Spearbit 87

packages/deployments/contracts/contracts/core/connext/helpers/ConnextPriceOracle.sol, packages/deployments/contracts/contracts_forge/core/connext/helpers/ConnextPriceOracle.t.sol
Fixes 
https://github.com/spearbit-audits/connext/issues/90
=> Spearbit 90

packages/deployments/contracts/contracts/core/promise/PromiseRouter.sol
Fixes 
https://github.com/spearbit-audits/connext/issues/91
=> consistently delete array

packages/deployments/contracts/contracts/core/connext/helpers/SponsorVault.sol, packages/deployments/contracts/contracts_forge/core/connext/helpers/SponsorVault.t.sol
Fixes https://github.com/spearbit-audits/connext/issues/86
- Handle case where `gasOracle` returns 0 for denominator
Fixes https://github.com/spearbit-audits/connext/issues/86
=> 86 spearbit

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
Fixes https://github.com/spearbit-audits/connext/issues/84
- Does not portal when local transfers are requested
Fixes https://github.com/spearbit-audits/connext/issues/84
=> fix: no portal local assets

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol
Fixes https://github.com/spearbit-audits/connext/issues/85
- Increments relayer fees instead of overriding
Fixes https://github.com/spearbit-audits/connext/issues/85
=> 85 spearbit

packages/deployments/contracts/contracts/core/promise/PromiseRouter.sol, packages/deployments/contracts/contracts_forge/core/promise/PromiseRouter.t.sol, packages/deployments/contracts/contracts_forge/utils/Mock.sol
Fixes https://github.com/spearbit-audits/connext/issues/39
- Wraps `callback` function in `excessivelySafeCall`
- Adds admin function to set reserve gas value
Fixes https://github.com/spearbit-audits/connext/issues/39
=> Spearbit 39

packages/examples/sdk-server/examples/index.http, packages/examples/sdk-server/src/base.ts, packages/examples/sdk-server/src/index.ts, packages/examples/sdk-server/src/pool.ts, packages/examples/sdk-server/src/types/api.ts
Add sendtransaction endpoint
Fixes
=> Sdk testing

packages/deployments/contracts/contracts/core/connext/helpers/ConnextPriceOracle.sol
Fixes 
https://github.com/spearbit-audits/connext/issues/47
=> Spearbit-47

packages/deployments/contracts/contracts/core/connext/facets/BaseConnextFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/PortalFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/upgrade-initializers/DiamondInit.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/RoutersFacet.t.sol, packages/deployments/contracts/contracts_forge/utils/FacetHelper.sol
Fixes https://github.com/spearbit-audits/connext/issues/92
- Makes `LIQUIDITY_FEE_DENOMINATOR` a constant
- Renames denominator to `BPS_FEE_DENOMINATOR`
Fixes https://github.com/spearbit-audits/connext/issues/92
=> 92 spearbit

ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf
sequencer-subscriber needs routing to receive messages for 9991
Fixes 
https://github.com/connext/nxtp/issues/1666
=> tf config changes

packages/adapters/cache/package.json, packages/agents/router/package.json, packages/agents/sequencer/package.json
=> Remove unused graphql-codegen

packages/deployments/contracts/hardhat.config.ts, packages/deployments/contracts/tasks/traceMessage.ts, yarn.lock
=> Enable traceMessage hh task

packages/examples/sdk-server/config.json.example, packages/examples/sdk-server/examples/index.http, packages/examples/sdk-server/src/index.ts, packages/examples/sdk-server/src/routes/base.ts, packages/examples/sdk-server/src/routes/pool.ts, packages/examples/sdk-server/src/routes/router.ts, packages/examples/sdk-server/src/types/api.ts
Add sdkRouter routes for testing.
Fixes
=> Sdk server

packages/agents/lighthouse/src/lib/operations/cartographer.ts, packages/agents/lighthouse/src/lib/operations/execute.ts, packages/agents/lighthouse/src/lib/operations/relayer.ts
=> Improve logs

packages/deployments/contracts/contracts_forge/core/connext/facets/SwapAdminFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/AmplificationUtils.t.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/AssetLogic.t.sol
Fixes the forge tests
- Adds the `key` field into the created `SwapUtils.Swap` structs
N/A
=> fix: add key

packages/deployments/contracts/abi/contracts/core/connext/facets/AssetFacet.sol/AssetFacet.json, packages/deployments/contracts/abi/hardhat-diamond-abi/HardhatDiamondABI.sol/ConnextHandler.json, packages/deployments/contracts/contracts/core/connext/facets/AssetFacet.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/AssetFacet.t.sol, packages/deployments/subgraph/src/amarok-runtime-staging/abis/ConnextHandler.json, packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-staging/subgraph.template.yaml
=> 1650 subgraph incorrect local asset

ops/modules/auto-scaling/main.tf, ops/modules/auto-scaling/variables.tf, ops/modules/service/outputs.tf, ops/testnet/prod/core/main.tf, ops/testnet/prod/core/variables.tf, ops/testnet/staging/core/main.tf, ops/testnet/staging/core/variables.tf
=> scaling service based on cpu and memory

ops/modules/db/main.tf, ops/modules/db/variables.tf, ops/modules/networking/main.tf, ops/modules/sgs/backend/main.tf, ops/testnet/prod/backend/main.tf, ops/testnet/staging/backend/main.tf, ops/testnet/staging/backend/variables.tf
=> enable public db access

.github/workflows/build-test-deploy.yml, ops/mainnet/prod/core/config.tf, ops/mainnet/prod/core/outputs.tf, ops/testnet/prod/core/config.tf, ops/testnet/prod/core/outputs.tf, ops/testnet/staging/core/config.tf, ops/testnet/staging/core/outputs.tf
=> Fix config

.github/workflows/build-test-deploy.yml
=> FIx workflow

ops/env/testnet/core/secrets.staging.json, ops/testnet/prod/core/config.tf, ops/testnet/prod/core/main.tf, ops/testnet/prod/core/variables.tf, ops/testnet/staging/core/config.tf, ops/testnet/staging/core/main.tf, ops/testnet/staging/core/variables.tf, packages/agents/cartographer/api/example.http, packages/agents/cartographer/poller/db/migrations/20220730013440_min_outs.sql
=> Staging sync

ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf, packages/examples/sdk-server/config.json.example, packages/examples/sdk-server/examples/index.http
=> Update weth config with new addresses

packages/examples/sdk-server/config.json.example
Updating RPC endpoints to working ones that do not require own infura keys just to get started
Fixes
=> Update RPC endpoints to working defaults

packages/deployments/contracts/hardhat.config.ts, packages/deployments/contracts/src/utils.ts, packages/deployments/contracts/tasks/addSender.ts
Creates a task to whitelist a router on a given chain
- `addSender` task manipulates the whitelist to add a given contract to allowed senders on a connector.
N/A
=> Hotfix add sender

packages/utils/test/maticjs/proof.spec.ts
=> maticjs proof.ts tests

packages/deployments/contracts/deploy/03_deployConnext.ts
=> Fix diamond proxy upgrade

ops/mainnet/prod/core/outputs.tf
=> Fix service endpt typo

packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-staging/schema.graphql, packages/deployments/subgraph/src/amarok-runtime-v0/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-v0/schema.graphql
=> Rd originmessage

packages/adapters/subgraph/.graphclient/index.ts, packages/adapters/subgraph/.graphclient/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Staging_Goerli/introspectionSchema.ts, packages/adapters/subgraph/.graphclient/sources/Connext_Staging_Goerli/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Staging_Goerli/types.ts, packages/adapters/subgraph/.graphclient/sources/Connext_Staging_OptimismGoerli/introspectionSchema.ts, packages/adapters/subgraph/.graphclient/sources/Connext_Staging_OptimismGoerli/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Staging_OptimismGoerli/types.ts, packages/adapters/subgraph/src/lib/helpers/parse.ts, packages/adapters/subgraph/src/lib/operations/queries.ts, packages/agents/cartographer/poller/db/schema.sql, packages/agents/cartographer/poller/src/lib/operations/messages.ts, packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-staging/schema.graphql, packages/deployments/subgraph/src/amarok-runtime-v0/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-v0/schema.graphql, packages/utils/src/types/amb.ts, packages/utils/src/types/db.ts
=> update origin message

ops/testnet/prod/backend/config.tf, ops/testnet/prod/backend/main.tf, ops/testnet/prod/backend/outputs.tf, ops/testnet/prod/backend/variables.tf, ops/testnet/prod/core/config.tf, ops/testnet/prod/core/main.tf, ops/testnet/prod/core/outputs.tf, ops/testnet/prod/core/variables.tf, ops/testnet/staging/backend/config.tf, ops/testnet/staging/core/config.tf
=> Fix Configs

packages/deployments/contracts/contracts/messaging/connectors/polygon/PolygonHubConnector.sol, packages/deployments/contracts/contracts/messaging/connectors/polygon/PolygonSpokeConnector.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/polygon/PolygonHubConnector.t.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/polygon/PolygonSpokeConnector.t.sol
=> Polygon connector test

ops/modules/db/main.tf, packages/adapters/subgraph/.graphclient/index.ts, packages/adapters/subgraph/.graphclient/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Goerli/introspectionSchema.ts, packages/adapters/subgraph/.graphclient/sources/Connext_Goerli/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Goerli/types.ts, packages/adapters/subgraph/.graphclient/sources/Connext_OptimismGoerli/introspectionSchema.ts, packages/adapters/subgraph/.graphclient/sources/Connext_OptimismGoerli/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_OptimismGoerli/types.ts, packages/adapters/subgraph/src/lib/operations/queries.ts, packages/adapters/subgraph/src/reader.ts, packages/agents/cartographer/poller/db/schema.sql, packages/agents/cartographer/poller/src/adapters/database/client.ts, packages/agents/cartographer/poller/src/lib/operations/messages.ts
Fixes 
https://github.com/connext/nxtp/issues/1855
=> Merge to main

packages/deployments/subgraph/config/amarok-runtime-staging.json, packages/deployments/subgraph/config/amarok-runtime-v0.json
=> Mumbai graph deployment

packages/deployments/contracts/contracts/core/connext/facets/NomadFacet.sol, packages/deployments/contracts/contracts_forge/Connext.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/NomadFacet.t.sol
=> Add originDomain to Reconciled event

packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-staging/schema.graphql, packages/deployments/subgraph/src/amarok-runtime-v0/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-v0/schema.graphql
=> 1807 offchain rm origindomain

packages/deployments/contracts/hardhat.config.ts
Polygonscan uses different API keys, allow that to be provided separately in the env.
Fixes
=> use polygon scan key

packages/agents/cartographer/poller/db/migrations/20220920101730_messages_transfers_indexes.sql, packages/agents/cartographer/poller/db/schema.sql
=> Add indexes to messages and transfers

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
=> remove: nonReentrant from xcall

packages/deployments/contracts/contracts/messaging/connectors/gnosis/GnosisHubConnector.sol, packages/deployments/contracts/contracts/messaging/connectors/gnosis/GnosisSpokeConnector.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/gnosis/GnosisHubConnector.t.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/gnosis/GnosisSpokeConnector.t.sol
=> Complete gnosis connector

packages/examples/sdk-server/examples/index.http, packages/examples/sdk-server/src/index.ts, packages/examples/sdk-server/src/types/api.ts, packages/examples/sdk-server/src/utils.ts
=> Sdk server utils

packages/agents/lighthouse/src/config.ts
=> Fix lighthouse startup

packages/adapters/subgraph/src/lib/helpers/parse.ts, packages/adapters/subgraph/src/lib/operations/queries.ts, packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts, packages/deployments/subgraph/src/amarok-runtime-staging/schema.graphql, packages/utils/src/mocks/mock.ts, packages/utils/src/types/db.ts, packages/utils/src/types/xtransfers.ts
=> 1807 Updates subgraph adapter

packages/deployments/subgraph/src/amarok-runtime-v0/mapping.ts
=> chg:processed as true if proveAndProcess attempted

packages/adapters/subgraph/src/lib/operations/queries.ts
=> Remove unnecessary query param

.github/workflows/build-test-deploy.yml
=> Remove e2e test for now

ops/testnet/prod/core/variables.tf, ops/testnet/staging/core/variables.tf
=> Add tf vars

packages/adapters/subgraph/.graphclient/index.ts, packages/adapters/subgraph/.graphclient/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Staging_Mumbai/introspectionSchema.ts, packages/adapters/subgraph/.graphclient/sources/Connext_Staging_Mumbai/schema.graphql, packages/adapters/subgraph/.graphclient/sources/Connext_Staging_Mumbai/types.ts, packages/adapters/subgraph/src/lib/helpers/parse.ts, packages/adapters/subgraph/src/lib/operations/queries.ts, packages/adapters/subgraph/src/reader.ts, packages/adapters/subgraph/test/reader.spec.ts, packages/agents/cartographer/poller/src/lib/operations/messages.ts, packages/agents/router/example.http, packages/deployments/contracts/abi/@openzeppelin/contracts-upgradeable/utils/cryptography/draft-EIP712Upgradeable.sol/EIP712Upgradeable.json, packages/deployments/contracts/tasks/addLiquidity.ts, packages/utils/src/types/amb.ts
=> Optimize to only query hub

packages/deployments/contracts/src/init/config/index.ts, packages/deployments/contracts/src/init/config/production.ts, packages/deployments/contracts/src/init/config/staging.ts, packages/deployments/contracts/src/init/init.ts, packages/deployments/contracts/src/init/main.ts
=> Zero config initialize 

ops/testnet/staging/core/config.tf
=> fix mumbai support staging

ops/testnet/prod/core/config.tf
=> mumbai support prod

packages/deployments/contracts/src/init/config/testnet/production.ts, packages/deployments/contracts/src/init/config/testnet/staging.ts
Fixes 
https://github.com/connext/nxtp/issues/2071
https://github.com/connext/nxtp/issues/2091
=> add deployer to watcher list

packages/deployments/contracts/contracts/messaging/connectors/SpokeConnector.sol
see https://github.com/connext/nxtp/issues/2076
=> Require new agg root not empty, nor already pending/proven

docker/sequencer/config.local.json, ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf, packages/agents/sequencer/src/adapters/index.ts, packages/agents/sequencer/src/adapters/relayer/gelato.ts, packages/agents/sequencer/src/config.ts, packages/agents/sequencer/src/lib/entities/config.ts, packages/agents/sequencer/src/lib/helpers/index.ts, packages/agents/sequencer/src/lib/helpers/relayer.ts, packages/agents/sequencer/src/lib/operations/relayer/fastpath.ts, packages/agents/sequencer/src/lib/operations/relayer/slowpath.ts, packages/agents/sequencer/test/adapters/relayer/gelato.spec.ts, packages/agents/sequencer/test/mock.ts, packages/integration/test/constants/testnet/index.ts, packages/utils/src/mocks/mock.ts
- [] New feature (non-breaking change which adds functionality)
Fixes
=> 2097 sequencer sponsoredcall

packages/adapters/subgraph/test/live.ts, packages/deployments/subgraph/src/amarok-hub-staging/mapping/rootManager.ts
=> Update RootAggregated entity key

packages/adapters/subgraph/src/lib/helpers/parse.ts
=> Asset should not be null for zero-asset xcalls

packages/agents/router/src/tasks/publisher/operations/getXCalls.ts
=> Handle zero asset & zero amount transfer on router side

packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts
=> Fix prove and process

packages/adapters/database/src/client.ts, packages/utils/src/types/db.ts, packages/utils/src/types/xtransfers.ts
=> 2127 fix nan slippage

packages/adapters/database/src/client.ts, packages/adapters/database/src/index.ts, packages/adapters/database/test/client.spec.ts, packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts
=> staging sync 

packages/agents/router/src/setup.ts, packages/agents/sequencer/src/config.ts
Fixes 
https://github.com/connext/nxtp/issues/2181
=> Disable reply queues

packages/deployments/contracts/deployConfig/shared.ts, packages/deployments/contracts/src/utils.ts
=> Update getProcotolNetwork in contract utils

ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf
=> Fix message limit

ops/mainnet/prod/core/config.tf
=> Mainnet assets

packages/adapters/database/db/migrations/20221026084236_fix-root-message-id.sql, packages/adapters/database/db/schema.sql, packages/adapters/subgraph/test/live.ts, packages/deployments/subgraph/src/amarok-runtime-staging/mapping/spokeConnector.ts, packages/deployments/subgraph/src/amarok-runtime-staging/mapping/stableSwap.ts, packages/deployments/subgraph/src/amarok-runtime-v0/mapping/spokeConnector.ts
=> Add domain to message id in subgraph and cartographer

.gitignore, ops/mainnet/prod/core/config.tf, packages/agents/lighthouse/src/config.ts
=> Config fixes

.github/workflows/build-test-deploy.yml
=> Add yarn cache

packages/deployments/subgraph/src/amarok-runtime-staging/mapping/helper/index.ts, packages/deployments/subgraph/src/amarok-runtime-v0/mapping/helper/index.ts, packages/deployments/subgraph/src/helper/index.ts
=> Add optimism to hardcoded list

packages/agents/cartographer/poller/src/lib/operations/messages.ts, packages/agents/cartographer/poller/src/lib/operations/transfers.ts, packages/agents/cartographer/poller/test/lib/operations/messages.spec.ts, packages/agents/cartographer/poller/test/lib/operations/roots.spec.ts, packages/agents/cartographer/poller/test/lib/operations/routers.spec.ts, packages/agents/cartographer/poller/test/lib/operations/transfers.spec.ts, packages/agents/cartographer/poller/test/mock.ts
Cartographer tests should cover business logic.
Fixes
=> Fix carto tests

ops/mainnet/prod/core/config.tf, ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf
=> Update relayer config

ops/mainnet/prod/core/config.tf, ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf
Fix relayer web2signer url
Fixes
=> Fix relayer web2signer url

packages/agents/relayer/src/config.ts
=> Fix relayer config var

.github/workflows/build-test-deploy.yml
Fix git workflow for relayer
Fixes
=> Fix git workflow for relayer

ops/mainnet/prod/core/config.tf, ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf, packages/deployments/contracts/package.json, packages/deployments/contracts/tasks/connector/processFromRoot.ts, yarn.lock
Add relayers config to lighthouse tf
Fixes
=> Add relayers config to lighthouse tf

packages/agents/relayer/src/bindings/relays/index.ts, yarn.lock
=> Hotfix: set a min gas limit for relayer to conform to; meet reserve/process gas demand

ops/mainnet/prod/core/config.tf, ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf, packages/agents/lighthouse/src/tasks/processFromRoot/operations/processFromRoot.ts
Set a min gas limit for relayer
Fixes
=> Hotfix: set a min gas limit for relayer

ops/mainnet/prod/core/config.tf, ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf
Set seq-sub prefetch to 4
Fixes
=> Set seq-sub prefetch to 4

packages/adapters/subgraph/src/reader.ts, packages/adapters/subgraph/test/reader.spec.ts, packages/agents/router/src/tasks/publisher/operations/getXCalls.ts, packages/agents/router/test/mock.ts, packages/agents/router/test/publisher/operations/getXCalls.spec.ts, packages/agents/sequencer/test/globalTestHook.ts, packages/agents/sequencer/test/mock.ts, yarn.lock
=> Latest nonce

packages/agents/router/src/tasks/publisher/operations/getXCalls.ts
=> Hot Fix: Handle size zero

ops/mainnet/prod/core/config.tf, ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf, packages/agents/router/src/tasks/publisher/operations/getXCalls.ts
Hot Fix: Reduce seq-sub concurrency to 2
Fixes
=> Hot Fix: Reduce seq-sub concurrency to 2

ops/mainnet/prod/core/config.tf, ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf, packages/adapters/relayer/src/index.ts
=> Add info log

packages/adapters/subgraph/src/lib/operations/queries.ts, packages/adapters/subgraph/src/reader.ts, packages/agents/cartographer/poller/src/lib/operations/roots.ts, packages/agents/cartographer/poller/test/lib/operations/roots.spec.ts
Hot Fix: Use db checkpoints for aggregated roots
Fixes
=> Hot Fix: Use db checkpoints for aggregated roots

ops/mainnet/prod/core/config.tf, ops/testnet/prod/core/config.tf, ops/testnet/staging/core/config.tf, packages/adapters/relayer/src/index.ts
Hot Fix: Use db checkpoints for aggregated roots
Fixes
=> Merge Hot Fix: Use db checkpoints for aggregated roots

packages/adapters/relayer/src/index.ts, packages/agents/lighthouse/src/tasks/processFromRoot/operations/processFromRoot.ts, packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts, packages/agents/lighthouse/test/tasks/processFromRoot/operations/processFromRoot.spec.ts, packages/agents/sequencer/src/lib/operations/execute/fastpath.ts, packages/agents/sequencer/src/lib/operations/execute/slowpath.ts, packages/agents/sequencer/src/lib/operations/relayer/fastpath.ts, packages/agents/sequencer/src/lib/operations/relayer/slowpath.ts, packages/agents/sequencer/src/lib/operations/tasks.ts, packages/agents/sequencer/src/sequencer.ts, packages/agents/sequencer/test/lib/operations/execute/fastpath.spec.ts, packages/agents/sequencer/test/lib/operations/relayer/executefast.spec.ts, packages/agents/sequencer/test/lib/operations/relayer/executeslow.spec.ts, packages/agents/sequencer/test/lib/operations/tasks.spec.ts
=> Do not wait for task completion

packages/deployments/contracts/contracts/core/connext/facets/SwapAdminFacet.sol, packages/deployments/contracts/contracts/core/connext/helpers/StableSwap.sol, packages/deployments/contracts/contracts/core/connext/libraries/Encoding.sol, packages/deployments/contracts/contracts/shared/libraries/TypedMemView.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/192
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/192
=> Spearbit 192

packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/89
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/89
=> Spearbit 89

packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/85
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/85
=> Spearbit 85

packages/agents/router/src/tasks/executor/operations/cartographer.ts, packages/agents/router/src/tasks/publisher/operations/getXCalls.ts, packages/agents/router/test/executor/operations/cartographer.spec.ts
Add pagination to router executor
Fixes
=> Hot fix: Pagination

packages/deployments/contracts/contracts/shared/libraries/TypedMemView.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/49
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/49
=> Spearbit 49

packages/deployments/contracts/contracts/core/connext/libraries/SwapUtils.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/104
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/104
=> Spearbit 104

packages/deployments/contracts/contracts/core/connext/libraries/AmplificationUtils.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/151
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/151
=> Spearbit 151

packages/deployments/contracts/contracts/core/connext/helpers/LPToken.sol, packages/deployments/contracts/contracts/core/connext/helpers/OwnerPausableUpgradeable.sol, packages/deployments/contracts/contracts/core/connext/helpers/StableSwap.sol, packages/deployments/contracts/contracts/messaging/Merkle.sol, packages/deployments/contracts/contracts/shared/ProposedOwnable.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/31
Fixes
=> Spearbit 31

packages/deployments/contracts/contracts/core/connext/libraries/SwapUtils.sol, packages/deployments/contracts/contracts/core/connext/libraries/SwapUtilsExternal.sol
Fixes issue outlined [here](https://github.com/spearbit-audits/connext-nxtp/pull/1#discussion_r999320733)
Fixes
=> Spearbit 154

ops/mainnet/prod/core/config.tf
Mainnet sequencer queue config
Fixes
=> Hot Fix: Mainnet sequencer queue config

packages/agents/sdk/src/config.ts
=> add: config option for cartographerUrls

packages/deployments/contracts/contracts/messaging/libraries/Queue.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/53
=> Spearbit-i53: check to make sure queue is init'd in dequeue

README.md, packages/agents/cartographer/api/example.http, packages/agents/sequencer/src/bindings/publisher/server/index.ts, packages/agents/sequencer/src/lib/operations/execute/slowpath.ts
[Clear executor cache. Queue after publish.](https://github.com/connext/nxtp/commit/4e7b8de22609937d6ed5cbb34c38cd6886108bd2)
Fixes
=> Clear executor cache. Queue after publish.

packages/deployments/contracts/contracts/messaging/libraries/Queue.sol, packages/deployments/contracts/contracts_forge/messaging/RootManager.t.sol, packages/deployments/contracts/contracts_forge/messaging/libraries/Queue.t.sol
See https://github.com/spearbit-audits/connext-nxtp/pull/7#discussion_r998150016
=> Spearbit 56

packages/agents/router/src/tasks/executor/operations/sequencer.ts, packages/agents/router/test/executor/operations/sequencer.spec.ts
=> Handle http errors in router-executor

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/ProposedOwnableFacet.sol, packages/deployments/contracts/contracts/core/connext/helpers/ConnextPriceOracle.sol, packages/deployments/contracts/contracts/core/connext/interfaces/IConnext.sol, packages/deployments/contracts/contracts/messaging/Merkle.sol, packages/deployments/contracts/contracts/messaging/RootManager.sol, packages/deployments/contracts/contracts/messaging/WatcherClient.sol, packages/deployments/contracts/contracts/messaging/WatcherManager.sol, packages/deployments/contracts/contracts/messaging/connectors/Connector.sol, packages/deployments/contracts/contracts/messaging/connectors/SpokeConnector.sol, packages/deployments/contracts/contracts/shared/upgrade/UpgradeBeaconController.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/ProposedOwnableFacet.t.sol, packages/deployments/contracts/contracts_forge/utils/Deployer.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/51
- Removes ability to renounce ownership on: `WatcherManager`, `WatcherClient`, `MerkleTreeMaager`, `RootManager`, `ProposedOwnableFacet`
- Documents consequences in `UpgradeBeaconController` and `ConnextPriceOracle`
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/51
=> Spearbit 51

packages/deployments/contracts/contracts/shared/libraries/TypedMemView.sol
=> Spearbit 42

packages/deployments/contracts/contracts/messaging/connectors/Connector.sol, packages/deployments/contracts/contracts/messaging/connectors/arbitrum/ArbitrumHubConnector.sol, packages/deployments/contracts/contracts/messaging/connectors/optimism/OptimismHubConnector.sol, packages/deployments/contracts/contracts/messaging/connectors/polygon/PolygonHubConnector.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/optimism/OptimismHubConnector.t.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/212
Calls to processMessageFromRoot with an already processed _data still emit MessageProcessed. This might cause issues for off-chain agents like relayers monitoring this event.
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/212
=> Spearbit 212

packages/deployments/contracts/README.md
Addresses https://github.com/spearbit-audits/connext-nxtp/issues/186
Fixes
=> spearbit 186

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/interfaces/IConnext.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/utils/Deployer.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/108
- Adds `forceReceiveLocal` callable by delegates
Fixes
=> Spearbit 108

packages/deployments/contracts/contracts/messaging/WatcherManager.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/SpokeConnector.t.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/194
WatcherManager has a private mapping watchers and a getter function isWatcher() to query that mapping. Since WatcherManager is not inherited by any other contract, it is safe to make it public to avoid the need of an explicit getter function.
Fixes
=> Spearbit 194

packages/deployments/contracts/contracts/messaging/connectors/SpokeConnector.sol
fixes https://github.com/spearbit-audits/connext-nxtp/issues/19
=> Spearbit-i19: add 0 check in verify aggregate root

packages/deployments/contracts/contracts/core/connext/facets/StableSwapFacet.sol, packages/deployments/contracts/contracts/core/connext/helpers/StableSwap.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/237
Merging into #2354 because that is where the offending commit would be introduced
Fixes
=> Spearbit 237 

packages/deployments/contracts/contracts/messaging/connectors/optimism/OptimismHubConnector.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/217
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/217
=> Spearbit 217

packages/deployments/contracts/contracts/messaging/connectors/SpokeConnector.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/211
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/211
=> Spearbit 211

packages/deployments/contracts/contracts/core/connext/facets/SwapAdminFacet.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/228
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/228
=> Spearbit 228

packages/deployments/contracts/contracts/shared/libraries/TypedMemView.sol
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/161
https://github.com/spearbit-audits/connext-nxtp/issues/160
- Removes `sha2` 
- Removes `hash160`
- Removes `hash256`
Fixes
=> Spearbit 161, 160

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/upgrade-initializers/DiamondInit.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/upgrade-initializers/DiamondInit.t.sol, packages/deployments/contracts/contracts_forge/core/connext/libraries/LibDiamond.t.sol, packages/deployments/contracts/contracts_forge/utils/Deployer.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/118
- Adds check for domains on updating xapp manager
- Adds check for domains on initializing diamond
Fixes
=> Spearbit 118

packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/88
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/88
=> Spearbit 88

packages/deployments/contracts/contracts/core/connext/facets/TokenFacet.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/TokenFacet.t.sol, packages/deployments/contracts/contracts_forge/utils/FacetHelper.sol
=> Spearbit 79

packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol
Fixes issues outlined [here](https://github.com/spearbit-audits/connext-nxtp/pull/1#discussion_r1001889377)
Fixes
=> Spearbit 141

packages/deployments/contracts/contracts/core/connext/libraries/SwapUtils.sol, packages/deployments/contracts/contracts/core/connext/libraries/SwapUtilsExternal.sol
Fixes issue outlined [here](https://github.com/spearbit-audits/connext-nxtp/pull/1#discussion_r1001015103)
Fixes
=> Spearbit 155

packages/deployments/contracts/contracts/messaging/libraries/DomainIndexer.sol
See comment https://github.com/spearbit-audits/connext-nxtp/pull/7#discussion_r998695653
=> Spearbit 210

packages/deployments/contracts/contracts/messaging/connectors/arbitrum/ArbitrumHubConnector.sol
=> Optimize require

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/120
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/120
=> Spearbit 120

packages/deployments/contracts/contracts/shared/libraries/TypedMemView.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/48
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/48
=> Spearbit 48

packages/deployments/contracts/contracts/core/connext/facets/PortalFacet.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/149
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/149
=> Spearbit 149

packages/deployments/contracts/contracts/shared/ProposedOwnable.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/133
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/133
=> Spearbit 133

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/146
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/146
=> Spearbit 146

packages/deployments/contracts/contracts/core/connext/libraries/LibDiamond.sol
Fixes comment [here](https://github.com/spearbit-audits/connext-nxtp/pull/1#discussion_r1002567502)
Fixes
=> Spearbit 97

packages/deployments/contracts/contracts/core/connext/libraries/AmplificationUtils.sol, packages/deployments/contracts/contracts/core/connext/libraries/SwapUtilsExternal.sol, packages/deployments/contracts/contracts_forge/core/connext/facets/SwapAdminFacet.t.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/83
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/83
=> Spearbit 83

packages/deployments/contracts/contracts/core/connext/libraries/AssetLogic.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibDiamond.sol
FIxes https://github.com/spearbit-audits/connext-nxtp/issues/224
- Uses `.code.length` instead of assembly
Fixes
=> Spearbit 224

packages/deployments/contracts/contracts/core/connext/facets/BaseConnextFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/upgrade-initializers/DiamondInit.sol, packages/deployments/contracts/contracts/core/connext/libraries/LibConnextStorage.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/227
- Adds a `nonXcallReentrant` modifier
Fixes
=> Spearbit 227

packages/deployments/contracts/contracts/shared/ProposedOwnable.sol, packages/deployments/contracts/contracts_forge/shared/ProposedOwnable.t.sol
=> Spearbit 18

packages/deployments/contracts/contracts/core/connext/facets/SwapAdminFacet.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/117
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/117
=> Spearbit 117

packages/deployments/contracts/contracts/messaging/connectors/polygon/PolygonHubConnector.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/62
- Adds comment explaining a revert
- Intentionally moves revert to `_setMirrorConnector`
Fixes
=> Spearbit 62

packages/deployments/contracts/abi/contracts/messaging/RootManager.sol/RootManager.json, packages/deployments/contracts/contracts/messaging/RootManager.sol, packages/deployments/contracts/contracts_forge/messaging/RootManager.t.sol
=> Revert "2427 fix spearbit pr 34"

packages/deployments/contracts/contracts/messaging/connectors/polygon/PolygonSpokeConnector.sol
Fixes: https://github.com/spearbit-audits/connext-nxtp/issues/27
- Removes redundant sender check in `PolygonSpokeConnector` and adds a comment
Fixes
=> Spearbit 27

packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/187
Fixes
=> Spearbit 187

packages/deployments/contracts/contracts/messaging/connectors/zksync/ZkSyncHubConnector.sol, packages/deployments/contracts/contracts/messaging/connectors/zksync/ZkSyncSpokeConnector.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/209
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/209
=> Spearbit 209

packages/deployments/contracts/contracts/core/connext/facets/BaseConnextFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/InboxFacet.sol, packages/deployments/contracts/contracts/core/connext/facets/TokenFacet.sol, packages/deployments/contracts/contracts/core/connext/helpers/BridgeToken.sol, packages/deployments/contracts/contracts/core/connext/helpers/ConnextPriceOracle.sol, packages/deployments/contracts/contracts/messaging/RootManager.sol, packages/deployments/contracts/contracts/shared/libraries/TypeCasts.sol, packages/deployments/contracts/contracts/shared/libraries/TypedMemView.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/106
- Removes unused code and errors
Fixes
=> Spearbit 106

packages/deployments/contracts/contracts/messaging/libraries/Message.sol
=> Optimize message hash

packages/deployments/contracts/contracts/messaging/connectors/zksync/ZkSyncSpokeConnector.sol
Fixes https://github.com/spearbit-audits/connext-nxtp/issues/81
- Adds clarifying documentation and note from team
Fixes
=> Spearbit 81

packages/deployments/contracts/contracts/messaging/connectors/polygon/tunnel/FxBaseChildTunnel.sol, packages/deployments/contracts/contracts/messaging/connectors/polygon/tunnel/FxBaseRootTunnel.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/polygon/PolygonHubConnector.t.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/polygon/PolygonSpokeConnector.t.sol
fixes https://github.com/spearbit-audits/connext-nxtp/issues/137
=> Spearbit-i137: make set fx root/child tunnel method internal

packages/deployments/contracts/contracts/messaging/connectors/polygon/tunnel/FxBaseChildTunnel.sol, packages/deployments/contracts/contracts/messaging/connectors/polygon/tunnel/FxBaseRootTunnel.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/polygon/PolygonHubConnector.t.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/polygon/PolygonSpokeConnector.t.sol
=> Revert "Spearbit-i137: make set fx root/child tunnel method internal"

packages/deployments/contracts/contracts/core/connext/libraries/SwapUtils.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/100
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/100
=> Spearbit 100

packages/deployments/contracts/contracts/messaging/libraries/DomainIndexer.sol
In response to 2 bits of feedback:
- https://github.com/connext/nxtp/commit/4c582138adeeeb7757092c3851d8ab8f3248721b#r89953790
- https://github.com/spearbit-audits/connext-nxtp/issues/195#issuecomment-1315338861
=> validateDomains: sanity check length of args; events for add/remove domain

packages/adapters/database/db/migrations/20221118203009_update_to_domainsHash.sql, packages/adapters/database/db/schema.sql, packages/adapters/database/src/client.ts, packages/adapters/database/src/zapatos/schema.d.ts, packages/adapters/subgraph/src/lib/helpers/parse.ts, packages/adapters/subgraph/src/lib/operations/queries.ts, packages/utils/src/mocks/mock.ts, packages/utils/src/types/amb.ts, packages/utils/src/types/db.ts
=> Fix propagate schema

packages/agents/lighthouse/src/tasks/propagate/helpers/arbitrum.ts, yarn.lock
=> Arbitrum fix

packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts
=> fix: logging

packages/agents/lighthouse/src/tasks/prover/operations/proveAndProcess.ts
=> Fix address

packages/deployments/contracts/deploy/01_deployMessaging.ts
=> Hotfix: fix the l1-to-l2 alias address calculation

ops/mainnet/prod/core/variables.tf, ops/testnet/prod/core/variables.tf, package.json, packages/adapters/cache/package.json, packages/adapters/database/package.json, packages/adapters/relayer/package.json, packages/adapters/subgraph/package.json, packages/adapters/txservice/package.json, packages/adapters/web3signer/package.json, packages/agents/cartographer/poller/package.json, packages/agents/lighthouse/package.json, packages/agents/relayer/package.json, packages/agents/router/package.json, packages/agents/sdk/package.json, packages/agents/sequencer/package.json, packages/deployments/contracts/package.json, packages/deployments/subgraph/package.json, packages/integration/package.json, packages/utils/package.json
Mainnet Deployments:tada:
Fixes
=> Amarok 0.2.1-beta.7

CHANGELOG.md, ops/mainnet/prod/core/variables.tf, ops/testnet/prod/core/variables.tf, package.json, packages/adapters/cache/package.json, packages/adapters/database/package.json, packages/adapters/relayer/package.json, packages/adapters/subgraph/package.json, packages/adapters/txservice/package.json, packages/adapters/web3signer/package.json, packages/agents/cartographer/poller/package.json, packages/agents/lighthouse/package.json, packages/agents/relayer/package.json, packages/agents/router/package.json, packages/agents/sdk/package.json, packages/agents/sequencer/package.json, packages/deployments/contracts/package.json, packages/deployments/subgraph/package.json, packages/integration/package.json, packages/utils/package.json
Mainnet Deployments:tada:
Fixes
=> Amarok 0.2.1-beta.8

CHANGELOG.md, ops/mainnet/prod/core/variables.tf, ops/testnet/prod/core/variables.tf, package.json, packages/adapters/cache/package.json, packages/adapters/database/package.json, packages/adapters/relayer/package.json, packages/adapters/subgraph/package.json, packages/adapters/txservice/package.json, packages/adapters/web3signer/package.json, packages/agents/cartographer/poller/package.json, packages/agents/lighthouse/package.json, packages/agents/relayer/package.json, packages/agents/router/package.json, packages/agents/sdk/package.json, packages/agents/sequencer/package.json, packages/deployments/contracts/package.json, packages/deployments/subgraph/package.json, packages/integration/package.json, packages/utils/package.json
=> Amarok v0.2.1-beta.8

packages/adapters/database/src/client.ts, packages/adapters/database/test/client.spec.ts
=> Fix: query for index

packages/adapters/database/db/migrations/20221122235058_refactor-metrics.sql, packages/adapters/database/db/schema.sql, packages/adapters/database/src/zapatos/schema.d.ts
=> Refactor views for metrics

packages/agents/router/src/tasks/executor/operations/sequencer.ts
=> Improve router-executor logs

.github/workflows/build-test-deploy.yml
=> Upgrade node version in ci/cd

ops/mainnet/prod/core/main.tf, ops/testnet/prod/core/main.tf, ops/testnet/staging/core/main.tf, packages/agents/sequencer/src/bindings/subscriber/auctions/index.ts
=> Handle slowPath data in executor exit

packages/agents/sdk/src/sdkPool.ts, packages/agents/sdk/test/sdkPool.spec.ts, packages/examples/sdk-server/examples/index.http, packages/examples/sdk-server/src/pool.ts, packages/examples/sdk-server/src/types/api.ts
=> Sdk additions

packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts
=> Send propagate with Gelato also

packages/deployments/contracts/deployments/mainnet/BnbHubConnector.json, packages/deployments/contracts/src/config.ts
=> deploy BnbHubConnector

packages/deployments/contracts/contracts/messaging/connectors/arbitrum/ArbitrumHubConnector.sol, packages/deployments/contracts/contracts/messaging/connectors/arbitrum/ArbitrumSpokeConnector.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/arbitrum/ArbitrumHubConnector.t.sol
=> Arb calldata length check

ops/mainnet/prod/core/main.tf, ops/testnet/prod/core/main.tf, ops/testnet/staging/core/main.tf
=> Bump up seq-sub cpu+mem

packages/agents/sequencer/src/bindings/subscriber/auctions/index.ts
=> Debug logs

packages/agents/lighthouse/src/tasks/propagate/helpers/gnosis.ts, packages/agents/lighthouse/src/tasks/propagate/helpers/index.ts, packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts, packages/agents/lighthouse/test/tasks/propagate/helpers/gnosis.spec.ts
=> Gnosis lighthouse propagate

packages/deployments/contracts/contracts/messaging/connectors/gnosis/GnosisHubConnector.sol, packages/deployments/contracts/contracts/messaging/connectors/gnosis/GnosisSpokeConnector.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/gnosis/GnosisHubConnector.t.sol, packages/deployments/contracts/contracts_forge/messaging/connectors/gnosis/GnosisSpokeConnector.t.sol
=> Gnosis sourceChainId vs destinationChainId

packages/agents/sdk/src/interfaces/index.ts, packages/agents/sdk/src/sdkPool.ts, packages/agents/sdk/test/sdkPool.spec.ts, packages/examples/sdk-server/examples/index.http, packages/examples/sdk-server/src/pool.ts, packages/examples/sdk-server/src/types/api.ts
=> Sdk calculate amount receive

packages/agents/sequencer/src/bindings/publisher/server/index.ts
=> Better logging for sequencer

packages/deployments/contracts/src/init/helpers/assets.ts, packages/deployments/contracts/tasks/setupAsset.ts
=> enforce cap

packages/adapters/watcher/package.json, yarn.lock
=> Unbork build

docker/watcher/Dockerfile, packages/adapters/relayer/tsconfig.build.json
=> Remove unnecessary stuff from watcher config

ops/testnet/staging/core/variables.tf
Resolve watcher container image
Fixes
=> Merge main

packages/agents/lighthouse/src/tasks/propagate/helpers/arbitrum.ts
=> Multiply arbitrum gasLimit

packages/deployments/contracts/src/init/helpers/messaging.ts
See notes about some race conditions introduced here:
https://www.notion.so/connext/Contracts-Overview-aae61df225dd4606bfc21b8b811ea73b#b5ae701b06bf47cca934cc0b86704c8f
It's low effort to just switch up the order here to minimize the chance that an in-flight `xcall` reverts due to messaging layer configuration being caught in a middle-state.
Reverts are the full extent of the risk here! There is no chance of an xcall getting caught in a "bad state" or being stuck.
=> Hotfix: optimal init script config call order to minimize effective downtime

ops/env/mainnet/core/secrets.prod.json, ops/env/testnet/core/secrets.prod.json, ops/env/testnet/core/secrets.staging.json, ops/mainnet/prod/core/config.tf
=> Secrets for relayer

packages/adapters/subgraph/src/lib/helpers/parse.ts, packages/adapters/subgraph/test/lib/helpers/parse.spec.ts, packages/deployments/subgraph/src/amarok-runtime-staging/mapping/transfers.ts, packages/deployments/subgraph/src/amarok-runtime-staging/schema.graphql, packages/deployments/subgraph/src/amarok-runtime-v0/mapping/transfers.ts, packages/deployments/subgraph/src/amarok-runtime-v0/schema.graphql, packages/utils/src/types/xtransfers.ts
Subgraph to capture `amount` on destination chain - the value after swap, if applicable.
Fixes
=> Destination amount

ops/testnet/staging/core/config.tf
=> watcher test config update

packages/adapters/database/src/client.ts, packages/adapters/database/src/index.ts, packages/adapters/database/test/client.spec.ts, packages/agents/cartographer/poller/src/lib/operations/messages.ts, packages/agents/cartographer/poller/test/lib/operations/messages.spec.ts
Fix unprocessedMessage handling
Fixes
=> Fix unprocessedMessage handling

packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts
=> Estimate propagate with msg.value

packages/adapters/database/src/client.ts
=> ProveAndProcess with the latest aggregateRoot

packages/agents/cartographer/poller/src/lib/operations/messages.ts
=> 2850 root message processed

packages/adapters/subgraph/src/lib/entities/config.ts, packages/adapters/subgraph/src/lib/helpers/create.ts, packages/adapters/subgraph/src/lib/helpers/parse.ts, packages/adapters/subgraph/src/reader.ts, packages/adapters/subgraph/test/lib/helpers/create.spec.ts, packages/adapters/subgraph/test/lib/helpers/parse.spec.ts, packages/adapters/subgraph/test/mock.ts, packages/adapters/subgraph/test/reader.spec.ts, packages/deployments/contracts/src/cli/init/config/mainnet/production.ts, yarn.lock
=> 2861 denormalize

ops/modules/cron/main.tf, ops/modules/daemon/main.tf, ops/modules/service/main.tf
=> fix dd_tags overrides DD_ENV

package.json, packages/adapters/cache/package.json, packages/adapters/database/package.json, packages/adapters/relayer/package.json, packages/adapters/subgraph/package.json, packages/adapters/txservice/package.json, packages/adapters/watcher/package.json, packages/adapters/web3signer/package.json, packages/agents/cartographer/poller/package.json, packages/agents/lighthouse/package.json, packages/agents/relayer/package.json, packages/agents/router/package.json, packages/agents/sdk/package.json, packages/agents/sequencer/package.json, packages/agents/watcher/package.json, packages/deployments/contracts/package.json, packages/deployments/subgraph/package.json, packages/integration/package.json, packages/utils/package.json
=> Staging sync for v0.2.1-rc.6 

ops/testnet/prod/core/config.tf
=> Fix lambda DD_ENV

packages/adapters/subgraph/src/reader.ts
=> Hotfix subgraph queries

packages/adapters/subgraph/src/lib/operations/queries.ts
=> Add amount to query

ops/testnet/staging/core/config.tf, packages/adapters/watcher/src/adapter.ts, packages/adapters/watcher/src/alert/keybase.ts, packages/agents/watcher/src/config.ts, packages/agents/watcher/src/operations/validateAndPause.ts, packages/agents/watcher/src/watcher.ts, packages/deployments/contracts/src/cli/watcher/firedrill.ts, packages/deployments/contracts/tasks/setupAsset.ts, yarn.lock
- Ensures watcher can alert to keybase
- Ensures script works
Fixes
=> Watcher fixes

packages/agents/sdk/src/config.ts, packages/agents/sdk/src/sdkPool.ts, packages/agents/sdk/src/sdkShared.ts, packages/examples/sdk-server/src/pool.ts, packages/examples/sdk-server/src/types/api.ts
Fixes https://github.com/connext/monorepo/issues/2942
=> Calculate amount received

packages/agents/sdk/src/index.ts, packages/agents/sdk/src/interfaces/index.ts, packages/agents/sdk/src/sdkPool.ts, packages/agents/sdk/src/sdkShared.ts, packages/agents/sdk/test/sdkPool.spec.ts, packages/agents/sdk/test/sdkShared.spec.ts, packages/examples/bridge-reference/src/components/Pool.tsx, packages/examples/sdk-server/examples/index.http, packages/examples/sdk-server/src/pool.ts, packages/examples/sdk-server/src/types/api.ts
=> Sdk improvements

packages/agents/sequencer/src/lib/helpers/relayerfee.ts, packages/utils/src/peripherals/relayer.ts
=> Missing commit

packages/adapters/cache/src/lib/caches/transfers.ts
=> Override transfer object in the cache

packages/agents/sdk/src/sdkPool.ts
=> Price impact for swap

packages/adapters/cache/src/lib/caches/transfers.ts, packages/adapters/database/src/client.ts, packages/adapters/database/test/client.spec.ts
Merge from main
- [ x ] Bug fix (non-breaking change which fixes an issue)
Fixes
=> Merge from main

packages/agents/sdk/src/index.ts, packages/agents/sdk/src/interfaces/index.ts, packages/agents/sdk/src/sdkPool.ts, packages/agents/sdk/test/sdkPool.spec.ts
=> Sdk updates

packages/agents/router/src/config.ts
=> Default router config

packages/adapters/cache/src/lib/caches/tasks.ts, packages/adapters/cache/test/lib/caches/tasks.spec.ts, packages/agents/relayer/src/bindings/relays/index.ts
=> Clear cache on relayer agent

package.json, packages/agents/lighthouse/src/tasks/propagate/operations/propagate.ts
=> Don't error task

packages/agents/sequencer/src/lib/errors/bid.ts, packages/agents/sequencer/src/lib/errors/executor.ts, packages/agents/sequencer/src/lib/operations/execute/fastpath.ts, packages/agents/sequencer/src/lib/operations/execute/slowpath.ts, packages/agents/sequencer/test/lib/operations/execute/fastpath.spec.ts, packages/agents/sequencer/test/lib/operations/execute/slowpath.spec.ts
Remove router version checks in sequencer.
Fixes 
https://github.com/connext/monorepo/issues/3016
=> Remove router version checks in sequencer.

README.md, packages/agents/router/README.md
=> Fix: typos

packages/adapters/relayer/src/gelato/gelato.ts, yarn.lock
=> Gas limit for arbitrum Gelato relayer

packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
=> Read auction data after the auction timeout

packages/deployments/subgraph/src/amarok-stableswap-staging/mapping/externalStableSwap.ts, packages/deployments/subgraph/src/amarok-stableswap-staging/mapping/helper/index.ts, packages/deployments/subgraph/src/amarok-stableswap-staging/mapping/stableSwap.ts, packages/deployments/subgraph/src/amarok-stableswap-staging/schema.graphql, packages/deployments/subgraph/src/amarok-stableswap-v0/mapping/externalStableSwap.ts, packages/deployments/subgraph/src/amarok-stableswap-v0/mapping/helper/index.ts, packages/deployments/subgraph/src/amarok-stableswap-v0/mapping/stableSwap.ts, packages/deployments/subgraph/src/amarok-stableswap-v0/schema.graphql
=> 3063 calculate virtual price and reserves of the pool on subgraph

packages/adapters/txservice/src/aggregator.ts, packages/adapters/txservice/src/dispatch.ts, packages/adapters/txservice/test/dispatch.spec.ts
=> Sanitize tx

packages/agents/router/src/tasks/executor/context.ts, packages/agents/router/src/tasks/executor/executor.ts, packages/agents/router/src/tasks/executor/operations/sequencer.ts, packages/agents/sequencer/test/bindings/publisher/server/index.spec.ts, packages/utils/src/mocks/mock.ts, packages/utils/src/types/relayer.ts
=> Add routerAddress to executor payload

packages/agents/lighthouse/src/mockable.ts, packages/agents/lighthouse/src/tasks/processFromRoot/helpers/arbitrum.ts, packages/agents/lighthouse/test/tasks/processFromRoot/helpers/arbitrum.spec.ts, packages/deployments/contracts/tasks/connector/processFromRoot.ts, yarn.lock
=> 3103 arbitrum stuck txs

packages/adapters/cache/src/lib/caches/transfers.ts, packages/adapters/cache/test/lib/caches/transfers.spec.ts, packages/agents/router/src/tasks/publisher/bindings/subgraph/index.ts, packages/agents/router/src/tasks/publisher/operations/getXCalls.ts, packages/agents/router/src/tasks/publisher/operations/index.ts, packages/agents/router/src/tasks/publisher/operations/retryXCalls.ts, packages/agents/router/test/publisher/operations/retryXCalls.spec.ts, packages/utils/src/mocks/mock.ts
=> Router should retry xcalls

ops/mainnet/prod/core/main.tf, packages/agents/router/src/tasks/publisher/operations/retryXCalls.ts, packages/utils/src/types/xtransfers.ts
=> Merge main into staging

packages/agents/lighthouse/src/tasks/processFromRoot/helpers/arbitrum.ts
=> 3138 hot fix arbitrum process from root

ops/mainnet/prod/core/config.tf
=> remove optimism alchemy rpc from lh config

packages/agents/lighthouse/test/tasks/processFromRoot/helpers/arbitrum.spec.ts
=> fix arbitrum helpers unit test

ops/mainnet/prod/core/config.tf, packages/agents/lighthouse/test/tasks/processFromRoot/helpers/arbitrum.spec.ts
=> Prod -> Staging sync

ops/mainnet/prod/core/config.tf
=> Switch LH to temp infura rpc

packages/agents/sequencer/src/lib/operations/execute/fastpath.ts, packages/agents/sequencer/test/lib/operations/execute/fastpath.spec.ts, packages/integration/test/constants/testnet/index.ts
=> Better cache cleanup on sequencer-publisher

packages/agents/sdk/src/interfaces/index.ts, packages/agents/sdk/src/lib/errors/index.ts, packages/agents/sdk/src/sdkBase.ts, packages/agents/sdk/src/sdkPool.ts, packages/agents/sdk/src/sdkRouter.ts, packages/agents/sdk/src/sdkShared.ts, packages/agents/sdk/src/sdkUtils.ts, packages/agents/sdk/test/sdkPool.spec.ts, packages/agents/sdk/test/sdkUtils.spec.ts, packages/examples/bridge-reference/src/components/TransferButton.tsx, packages/examples/sdk-server/examples/index.http, packages/examples/sdk-server/src/base.ts, packages/examples/sdk-server/src/pool.ts, packages/examples/sdk-server/src/types/api.ts, packages/examples/sdk-server/src/utils.ts
=> 2940 validation

packages/agents/sdk/src/interfaces/index.ts, packages/agents/sdk/src/lib/errors/index.ts, packages/agents/sdk/src/sdkBase.ts, packages/agents/sdk/src/sdkPool.ts, packages/agents/sdk/src/sdkRouter.ts, packages/agents/sdk/src/sdkShared.ts, packages/agents/sdk/src/sdkUtils.ts, packages/agents/sdk/test/sdkBase.spec.ts, packages/agents/sdk/test/sdkPool.spec.ts, packages/agents/sdk/test/sdkUtils.spec.ts, packages/examples/bridge-reference/src/components/TransferButton.tsx, packages/examples/sdk-server/examples/index.http, packages/examples/sdk-server/src/base.ts, packages/examples/sdk-server/src/pool.ts, packages/examples/sdk-server/src/types/api.ts, packages/examples/sdk-server/src/utils.ts
=> 3061 update slippage backup

packages/agents/sdk/src/sdkBase.ts, packages/examples/sdk-server/examples/index.http, packages/utils/src/peripherals/relayer.ts
=> add more logs at estimate fee

packages/utils/src/constants/gas.ts
=> hotfix: gaslimits

packages/agents/sdk/src/sdkPool.ts
=> Add decimal precision notes

packages/agents/sequencer/src/executer.ts, packages/agents/sequencer/src/index.ts, packages/agents/sequencer/src/publisher.ts, packages/agents/sequencer/src/subscriber.ts
Disable Sequencer dd-trace, in order to help narrow down the seq mem issue.
Fixes
=> Disable Sequencer dd-trace

packages/deployments/contracts/hardhat.config.ts, packages/deployments/contracts/tasks/addAdmin.ts
Adds task used to fix #2176 
proposal txs:
- mainnet: 0x8ce5526a9eff8d6e9146056ab0be330e2ca4f056b38bfea2cccd5b37c4536382
- bnb: 0x722cf5435c0cb012c1e5ec749a19872f42c59978cb8a13291044252f25bb1ec6
- xdai: 0xa657c6af8a2c935b52758a53f1219ee116d0f5db9f75b5c17fe0f5af9c36a4d2
- matic: 0x821166ecb7754a222c90c85d6e51e4362ae2a55bb59022b6ef893bcebf0b5340
- optimism: 0x27b0404ca73b2d173c797972f07de5d56a3c8a0671ceee0f8064695a28bb4c3d
- arbitrum: 0x29b4692d3816ee6379261c887cf475968f0e15929cf800725d428a41ba97239d
here are the safes that are in the process of being registered as nxtp owners:
- https://app.safe.global/eth:0x4d50a469fc788a3c0CdC8Fd67868877dCb246625
- https://app.safe.global/gno:0x7616Bc6d0dee5E250BA5b3dDa6cbbB71786FB638
- https://app.safe.global/bnb:0x9435Ba7C661a0Fd477deED640491de8c100325A …
=> feat: add admin tasks
