connext/monorepo

- packages/router/src/contract.ts
- packages/txservice/src/error.ts
- packages/txservice/src/provider.ts
- packages/txservice/src/transaction.ts
- packages/txservice/src/txservice.ts
- packages/txservice/src/types.ts
- packages/txservice/test/constants.ts
Minor adjustments to tx service logic including:
- ReadTransaction type with the `value` and `from` fields removed: for doing tx reads.
- prevents this (supposedly impossible case) from happening with a flag: "submitFailed".
tx submit -> success -> confirm -> timeout -> bump gas -> tx submit -> revert! -> confirm -> timeout (?*) -> bump gas ??!? -> tx submit ??!?
If `submitFailed`, then we only try to confirm once.
- various sanity checks
> Adjustments

- packages/router/src/adapters/subgraph/index.ts
- packages/router/src/adapters/subgraph/provider.ts
- packages/router/src/lib/helpers/auction.ts
- packages/router/src/lib/helpers/index.ts
- packages/router/src/lib/helpers/prepare.ts
- packages/router/src/lib/operations/prepare.ts
- packages/router/test/globalTestHook.ts
- packages/router/test/lib/operations/auction.spec.ts
- packages/router/test/lib/operations/prepare.spec.ts
- packages/router/test/utils.ts
- packages/sdk/src/sdk.ts
- packages/sdk/test/unit/sdk.spec.ts
Fixes #204 
- Updates the sdk and router to use `block.timestamp` instead of `Date.now()` for all expiry related things
> 204 expiry

- packages/integration/test/load/txserviceConcurrency.ts
- packages/integration/test/utils/config.ts
- packages/router/src/lib/errors/auction.ts
- packages/router/src/lib/errors/index.ts
- packages/router/src/lib/operations/auction.ts
Fixes #158 
WARNING: Did NOT address the following:
- "remove debug code from production build ( dry-run )" : assuming we need this for now. Left a TODO.
- "signer address might be different for different chains" : according to @LayneHaber this isn't actually possible, so non-issue.
- "no rate limiting. potential DoS vector when someone floods the node with auction requests (significant work to be done, handler is async, will trigger a reply message). user might force the router to sign the same message multiple times" : left a TODO, but not sure if this would realistically be implemented here or in the router index. I would imagine the latter.
- "actual estimated gas required to fuel transaction is never checked. current balance might be outdated, especially in race condition scenarios." …
> [router] 4.11: newAuction validators

- packages/txservice/src/provider.ts
- packages/txservice/test/provider.spec.ts
Reverts connext/nxtp#243
Load tests on tx service concurrency performing much more poorly with this fix in. Reverting it
> Revert "[txservice] Add validation step to send method to prevent false submit"

- README.md
- packages/sdk/src/subgraph.ts
- packages/sdk/test/unit/subgraph.spec.ts
- packages/utils/src/transactionManager.ts
Fixes bug where already tracked active transactions are not accounted for when handling active txs. 
This is the issue we are seeing in the intermittent CI failures
> Sdk already active

- CHANGELOG.md
- packages/router/src/lib/operations/fulfill.ts
- packages/utils/src/mock.ts
- packages/utils/src/signatures.ts
- some signatures had invalid `v` values which were reverting onchain but handled offchain
- sanitize signatures before returning
> Signature sanitized

- packages/router/src/config.ts
- packages/router/test/config.spec.ts
- packages/router/test/utils.ts
- packages/test-ui/src/components/Router.tsx
- packages/utils/src/chainData.ts
Need to see router balances for all stable coins across chains.
Display router balances in a table w/ a "Reload" button.
> [test-ui] add router balances table

- packages/router/src/config.ts
- packages/router/src/router.ts
- packages/txservice/src/config.ts
- packages/txservice/src/dispatch/provider.ts
- packages/utils/src/chainData.ts
During high traffic (ergo high gas price) periods, getGasPrice is lagging and not reflective of the current "rapid" gas price. This results in tx's getting stuck for long periods bumping gas continually (up to 10 times before failing), all while the actual gas price domain (e.g. in the 300s gwei) is 3 or 4 multiples higher than the price domain we're in (eg 20-40 gwei).
getGasPrice should check to see if there's a configured gas station, and then grab the gas price from there. If the gas station fails / doesn't work, then we resort to relying on the RPC getGasPrice.
sort of relies on : https://github.com/connext/chaindata/pull/31
> add option to pass in gas station to config

- packages/txservice/src/dispatch/transaction.ts
- packages/txservice/src/error.ts
- packages/txservice/src/txservice.ts
Getting nonce expired errors due to edge case described in comment here:
```ts
if (error.type === AlreadyMined.type) {
if (transaction.attempt === 1) {
// A transaction that's only been attempted once has an expired nonce. This means that dispatch
// assigned us an already-used nonce.
// In this event, we need to go back to the beginning and actually "recreate" the transaction
// itself now. Assuming our nonce tracker (dispatch) is effective, this should normally never occur...
// but there is at least 1 legit edge case: if the dispatch has just come online, it can only rely on
// the provider's tx count (getTransactionCount) to assign nonce - and the provider turns out to be
// incorrect (e.g. off by 1 or 2 pending tx's not in its mempool yet for some reason).
transaction = await …
```
> Nonce expired

- packages/txservice/src/dispatch.ts
- error loudly when submit fails with INSUFFICIENT_FUNDS
- if initial submit, we fail the tx, if resubmit, we keep trying to mine
> [txservice] Handle insufficient funds errors appropriately

- CHANGELOG.md
- packages/router/src/bindings/fastify/index.ts
- Admin cancel endpoint doesn't work without a signature on sender side (which router may not have or need)
- Default `null` signature to empty signature of `0x`
> Use proper default if not defined

- packages/router/src/adapters/subgraph/index.ts
- packages/router/src/adapters/subgraph/subgraph.ts
- packages/router/src/bindings/contractReader/index.ts
- packages/router/src/config.ts
- packages/router/src/lib/operations/auction.ts
- packages/router/test/adapters/subgraph/subgraph.spec.ts
- packages/router/test/globalTestHook.ts
- packages/router/test/lib/operations/auction.spec.ts
- packages/sdk/src/subgraph/subgraph.ts
- packages/sdk/test/unit/subgraph.spec.ts
- packages/utils/src/fallbackSubgraph.ts
Subgraph failing on one chain due to all the subgraph providers being out of sync is causing failure on all chains.
This seems to be occurring in the sdk, not in router - bc router's calls are all wrapped in try/catch per chain.
Error:
```
{"level":50,"time":1635867900140,"pid":1,"hostname":"80993d7e403d","name":"0x29A519e21d6A97cdB82270b69c98bAc6426CDCf9","requestContext":{"id":"st3wTsHgQ6e9OkZ2nP44LQ/7241201","origin":"getActiveTransactions"},"methodContext":{"id":"st3wTsHgQ6e9OkZ2nP44LQ/7241200","name":"getActiveTransactions"},"chainId":"250","error":{"message":"All subgraphs out of sync! Cannot handle active transactions for chain 56","type":"Error","context":{},"stack":"Error: All subgraphs out of sync! Cannot handle active transactions for chain 56\n    at FallbackSubgraph.request …
```
> [sdk/router] fix fallback subgraph in-sync requirements

- CHANGELOG.md
- packages/contracts/hardhat.config.ts
- packages/contracts/src/tasks/addAsset.ts
- packages/contracts/src/tasks/addRouter.ts
- packages/contracts/src/tasks/removeRouter.ts
No hardhat task to remove routers.
Add hardhat task to remove routers
> Remove router task

- packages/contracts/hardhat.config.ts
- packages/integration/test/integration.spec.ts
- packages/sdk-server/src/index.ts
- packages/sdk/src/error.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/sdkBase.ts
- packages/sdk/src/subgraph/subgraph.ts
- packages/sdk/test/unit/sdk.spec.ts
- packages/sdk/test/unit/sdkBase.spec.ts
- packages/utils/src/messaging.ts
Gelato integration needed cleanup. Fixes #503 
Standardize fulfill response, default relayer to Gelato. Add retries to gelato.
> Fulfill response

- packages/utils/src/gelato.ts
The Gelato Relayer didn't have support for Avalanche
The Gelato Relayer Server address for the Gelato Relayer for Avalanche was added.
> feat: Added Avalanche support in gelato relay

- packages/utils/src/subgraph.ts
Fallback subgraphs seem incorrectly defined for Fantom and Arbitrum One
> fix: Fallback subgraphs for Fantom and Arb1

- packages/utils/src/gelato.ts
There was not support for Arbitrum using the Gelato Relayer
We added a Gelato relayer that supports Arbitrum
> Added Arbitrum support using the Gelato Relayer

- packages/subgraph/config/v1-lite.json
- packages/subgraph/package.json
- packages/subgraph/src/v1-lite/abis/TransactionManager.json
- packages/subgraph/src/v1-lite/mapping.ts
- packages/subgraph/src/v1-lite/schema.graphql
- packages/subgraph/src/v1-lite/subgraph.template.yaml
closes: #519
- new: v1 lite for router and sdk
- update command
- deploy subgraphs
List of subgraphs
- https://thegraph.com/hosted-service/subgraph/connext/nxtp-mainnet-v1-lite
- https://thegraph.com/hosted-service/subgraph/connext/nxtp-arbitrum-one-v1-lite
- https://thegraph.com/hosted-service/subgraph/connext/nxtp-fantom-v1-lite
- https://thegraph.com/hosted-service/subgraph/connext/nxtp-matic-v1-lite
- https://thegraph.com/hosted-service/subgraph/connext/nxtp-moonriver-v1-lite
- https://thegraph.com/hosted-service/subgraph/connext/nxtp-xdai-v1-lite
- https://thegraph.com/hosted-service/subgraph/connext/nxtp-avalanche-v1-lite
- https://thegraph.com/hosted-service/subgraph/connext/nxtp-bsc-v1-lite
> subgraph v1 lite

- packages/subgraph/src/v1/mapping.ts
- packages/subgraph/src/v1/schema.graphql
- add: sending chain txCount for datapoint
- update mapping & deploy subgraphs
> metrics sendingchain datapoint

- packages/txservice/src/provider.ts
```{"level":50,"time":1637264209531,"pid":1,"hostname":"1fd4d1eb6749","name":"0x7E76de758cd414096a4882eD2824BC513D7Ed7c9","requestContext":{"transactionId":"0x3d471add26866a92b40f9277cbf08f952452d2a6fa0c3fd823eaf624b6951d06","id":"y1ftfVD5ROOI0QPVvq6JrQ/637595","origin":"handleActiveTransactions"},"methodContext":{"id":"y1ftfVD5ROOI0QPVvq6JrQ/637596","name":"handleSingle"},"chainId":10,"error":{"message":"Server error occurred","context":{"message":"gas price too high: 5000000000 wei, use at most tx.gasPrice = 1038664 wei","chainError":{"code":"SERVER_ERROR","reason":"processing response error"}},"type":"ServerError","stack":"Error: Server error occurred\n    at Object.parseError (/home/node/node_modules/@connext/nxtp-txservice/dist/error.js:312:20)\n    at …
```
> No gas min

- CHANGELOG.md
- packages/router/src/lib/helpers/shared.ts
- packages/router/test/lib/helpers/shared.spec.ts
- packages/test-ui/.env.example
- packages/test-ui/src/components/Swap.tsx
- packages/utils/src/gasEstimates.ts
- Fees not implemented for optimism because oracle setup does not work on that chain yet
- Fee calculation does not include l2 + l1 gas fees
- Use mainnet pricing for optimism fees
- Update fee calculation to work with l2 and l1 fees as [calculated on optimism](https://community.optimism.io/docs/users/fees-2.0.html#fees-in-a-nutshell)
Tested on test-ui with main nets for price verification.
> Optimism fee fix

- packages/router/src/bindings/contractReader/index.ts
- packages/router/src/lib/entities/contractReader.ts
- `ReceiverFulfilled` transactions are never dropped from tracker
- Remove `ReceiverFulfilled` entries by block from tracker
> Use block number for receiver fulfilled

- CHANGELOG.md
- packages/router/src/adapters/subgraph/subgraph.ts
- packages/router/src/bindings/contractReader/index.ts
- packages/router/src/lib/entities/cancel.ts
- packages/router/src/lib/entities/contractReader.ts
- packages/router/src/lib/operations/cancel.ts
- packages/router/test/bindings/contractReader/index.spec.ts
- packages/router/test/lib/operations/cancel.spec.ts
- packages/router/test/utils.ts
- On Arbitrum, `block.number` means the l1 block number-ish. [Documentation here](https://developer.offchainlabs.com/docs/time_in_arbitrum#ethereum-block-numbers-within-arbitrum).
- When checking the timestamp of the sending transaction before cancelling, you must use the `receipt.blockNumber` to get the proper l2 block
- Pull expiry block number from receipt in `cancel`
> Arbitrum cancel

- .eslintrc.js
- packages/router/src/bindings/contractReader/index.ts
- packages/router/src/bindings/messaging/index.ts
- packages/router/src/bindings/messaging/statusRequest.ts
- packages/router/src/lib/operations/index.ts
- packages/router/src/lib/operations/status.ts
- packages/router/test/lib/operations/status.spec.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/sdkBase.ts
- packages/test-ui/src/components/Swap.tsx
- packages/utils/src/messaging.ts
- clean up log
- add: subscribe to status req [router]
- new: binding to handle status req
- new: getStatus operation
- unit test
- add: subscribe and publish messaging func in messaging class
- add: sdk method to getStatus
- add: testUi func for testing
> router status

- CHANGELOG.md
- packages/router/src/adapters/web3signer/index.ts
- packages/router/test/lib/helpers/shared.spec.ts
- packages/txservice/src/types.ts
- packages/txservice/test/constants.ts
- web3signer was presuming we were sending a legacy transaction
- ethers was secretly converting it to a eip-1559 tx whenever possible
- added check for the type of tx in web3signer (0 = legacy; 2 = eip-1559)
- force all txs to be legacy for now, bc ethers conversion to eip-1559 is really gas-inefficient.
> [router] Hotfix: handle setting gas price vs eip-1559 gas fee based on type

- packages/router/src/bindings/contractReader/index.ts
- packages/router/src/lib/entities/contractReader.ts
- packages/router/src/lib/entities/index.ts
- packages/router/src/lib/operations/status.ts
- packages/utils/src/messaging.ts
- add: active transactions tracker type
- add: status response to getRouterStatus
- add: logs for active transactions
> add active transactions tracker logs

- CHANGELOG.md
- packages/router/src/adapters/subgraph/runtime/graphqlsdk.ts
- packages/router/src/adapters/subgraph/runtime/queries.ts
- packages/router/src/adapters/subgraph/subgraph.ts
- packages/router/test/adapters/subgraph/subgraph.spec.ts
- packages/router/test/bindings/contractReader/index.spec.ts
- packages/sdk/src/subgraph/graphqlsdk.ts
- packages/sdk/src/subgraph/queries.ts
- packages/sdk/src/subgraph/subgraph.ts
- packages/sdk/test/unit/subgraph.spec.ts
- packages/sdk/test/unit/subgraphsdk.spec.ts
- When `getActiveTransactions` is called, it is not looking for transactions matching the router/user. this means transactions could be mis-assigned if there is reuse of txids
- See [here](https://www.notion.so/connext/Duplicate-Transaction-Ids-815d14d795bf4a23b72b860f0dadc68a)
- Always use `userId` or `routerId` when querying for active transactions
> Active for router

- CHANGELOG.md
- packages/txservice/src/provider.ts
- packages/txservice/src/shared/errors.ts
- packages/txservice/src/shared/syncProvider.ts
- packages/txservice/src/shared/transactionBuffer.ts
- packages/txservice/test/provider.spec.ts
- packages/txservice/test/shared/contracts.spec.ts
- packages/txservice/test/shared/syncProvider.spec.ts
- packages/txservice/test/shared/transactionBuffer.spec.ts
- packages/utils/src/fallbackSubgraph.ts
Fixes #624 
- Increased weight for reliability metric significantly in the sort order of providers.
- Renamed 'Timeout' to 'StallTimeout'
- StallTimeout errors now bring reliability of a provider instantly to 0 (bc, by default, means provider didn't respond after 10s!)
- Fixed bug in handling StallTimeout error in the `execute` method
- No longer excluding "out-of-sync" providers (i.e. providers that are behind in X # of blocks from others), but concatenating them to be chosen as a fallback.
- The above fix ^ made me realize that the 'concat' operation I was doing in `FallbackSubgraph` had a misplaced parenthesis lol, so I also fixed that!
> [txservice] Better RPC stall timeout handling; emphasize reliability

- CHANGELOG.md
- packages/test-ui/.env.example
- packages/txservice/src/dispatch.ts
- packages/txservice/src/provider.ts
- packages/txservice/src/shared/errors.ts
- packages/txservice/src/shared/syncProvider.ts
- packages/txservice/test/dispatch.spec.ts
- packages/txservice/test/shared/contracts.spec.ts
- packages/txservice/test/shared/syncProvider.spec.ts
(Hopefully) fixes #627 
It seems we were treating `ServerError`s as an indication that an RPC call failed, when in reality they are an indication that only 1 provider failed. This would cause us to fail to fallback to the next provider.
- `ServerError`s are now treated correctly in `execute` wrapper method in `ChainRpcProvider`
- Changed `RpcError.reasons.StallTimeout` -> `StallTimeout`, it's own error type now
(- Also renamed `TimeoutError` to `OperationTimeout` so as to avoid confusion)
- Fixed a bug in `syncProviders()` where we did not catch (and ignore) errors in our `getBlock` calls. This was actually a pretty bad issue, as it prevented us from scoring priority of different providers correctly.
- `ServerError`s also now trigger the same severe penalty on provider's `reliability` …
> [txservice] Hotfix: fallback if server errors occur

- packages/sdk/src/sdkBase.ts
- packages/sdk/src/types.ts
closes: #604 
- add: fees break down on transferQuote response
- update: receiverAmount calc on estimateFee at sdk
> [sdk] fees breakdown at transferQuote

- packages/router/src/bindings/messaging/statusRequest.ts
- packages/router/src/lib/operations/status.ts
- packages/router/test/bindings/messaging/statusRequest.spec.ts
- packages/utils/src/messaging.ts
- fix: routerAddress and function async
- silent logs
> [router] status fixes

- packages/txservice/src/chainreader.ts
- packages/txservice/src/dispatch.ts
- packages/txservice/src/rpcProviderAggregator.ts
- packages/txservice/src/shared/errors.ts
- packages/txservice/test/chainreader.spec.ts
- packages/txservice/test/dispatch.spec.ts
- packages/txservice/test/rpcProviderAggregator.spec.ts
Problem assessment thread: https://discord.com/channels/454734546869551114/860482380321652766/922567480080232500
TL;DR:
- A gas spike happened, we couldn't bump over hard maximum and resubmit.
- A tx "disappeared", meaning the blockade nonce had no transaction.... and since we had bumped over maximum gas, we threw an error. What we should have done is resubmitted at the same gas price since the transaction didn't actually exist on chain!*
- A reboot fixed it, but we shouldn't rely on reboots, especially if we have 64 other txs in the queue.
*(*Idk how it's possible, but it happens. Maybe providers don't broadcast a tx properly, a reorg occurs, geth pending tx pool overflows, who knows? But if I check the tx hash on tenderly, I can see that that tx does not exist, even though the logs say …
> [txservice] Check that transaction exists when mine timeout occurs.

- packages/sdk/src/error.ts
- packages/sdk/src/sdkBase.ts
- packages/sdk/test/unit/sdkBase.spec.ts
- for loop retries 3 times... but if it fails the first time, gelatoSuccess is false, so it just throws right away lol
- default relayer fee is 0, and useRelayers default is true... we should not be using relayers if we use the default value of "0"
- we should fall back to using router network if gelato fails
> [sdk] Resort to using router network if gelato fails; set default useRelayers = false

- packages/router/src/lib/helpers/metrics.ts
- packages/router/src/lib/helpers/shared.ts
- packages/txservice/src/chainreader.ts
- packages/txservice/src/rpcProviderAggregator.ts
- packages/txservice/test/chainreader.spec.ts
- unable to query price oracle at a given block using chain service
- add optional block tag param
> Add blocktag to oracle price queries

- CHANGELOG.md
- packages/router/test/globalTestHook.ts
- packages/router/test/lib/operations/metaTx.spec.ts
- packages/sdk/src/sdk.ts
- packages/sdk/src/sdkBase.ts
- packages/sdk/test/unit/sdk.spec.ts
- packages/sdk/test/unit/sdkBase.spec.ts
- packages/utils/src/fallbackSubgraph.ts
- We weren't actually returning the query result in the 'generic' subgraph query before 🤦‍♂️ 
- Now we do
- Also did a bit of tidying up, the inconsistent fn headers were bothering me.
> [sdk] Return subgraph query; tidy up method headers

- CHANGELOG.md
- packages/txservice/src/dispatch.ts
- packages/txservice/test/dispatch.spec.ts
- If a tx at nonce X failed but never got mined (possibly indicating it was not sent correctly), we throw... but never backfill at that nonce! Thus causing a blockade.
- When a tx errors out, we check to see if it got mined properly. If not, then we reset the local nonce to the value of this tx's nonce. Then, on the next transaction, we will backfill.
- Worst case scenario, if the tx *does* end up getting mined even after resetting local nonce, on the next sent transaction we will just end up favoring the signer's current transactionCount over the local nonce (since we prefer whichever number is higher!).
- Only problem with this diff is that we're resetting the local nonce but not actually guaranteeing that we send a backfill... meaning that we have to *hope* that another transaction …
> [txservice] Rewind nonce if transaction fails and was never mined

- packages/sdk/src/sdkBase.ts
Fulfill without relayers without subgraph polling didn't work.
Fix.
> Move promise inside loop

- packages/utils/src/gasEstimates.ts
Syntax error while getting default hardcoded gas limit in case that `gasEstimates` are not defined on `chainInfo`.
> fix syntax issue while getting default gas limit

- packages/txservice/src/chainreader.ts
- packages/utils/src/chainData.ts
- packages/utils/src/gasEstimates.ts
The problem exists on layer 2 networks, especially on arbitrum one. We can just get gasPriceBid but gasPricePaid is actually used.
> Add gasPricefactor

- packages/utils/src/gelato.ts
There was not a Gelato Relayer on Gnosis Chain
Deploy a Gelato Relayer on Gnosis Chain :)
> feat: Added Gelato Relayer on Gnosis Chain

- packages/adapters/cache/src/index.ts
- packages/adapters/cache/src/lib/caches/index.ts
- packages/adapters/cache/src/lib/caches/transactions.ts
- packages/adapters/cache/src/lib/caches/transfers.ts
- packages/adapters/cache/test/lib/caches/consumer.spec.ts
- packages/adapters/cache/test/lib/caches/transfers.spec.ts
- packages/agents/router/src/bindings/subgraph/index.ts
- packages/agents/router/src/router.ts
- packages/agents/router/test/mock.ts
- packages/agents/sequencer/test/mock.ts
In current model, we basically publish the `NewXCall` event  whenever there's a new `xcall` in general. This will result in the router immediately getting hundreds/thousands/etc `NewXCall` events fired off every time it boots and it's behind the current state on-chain. As a result, the router would be spamming the seq. with bids.
While we'll probably have some cold-start logic in the future (e.g. put a nonce to start with in the config for each chain, etc), I think it would be best to just go ahead and collate the data at some point in the process here in order to derive which `NewXCall` events are "valid".
TL;DR: "Don't publish NewXCall if it's not a New XCall"
I propose we do the collation in the cache itself. The update for this is pretty straightforward. We would move from indexing …
> [cache] Index transfers by transfer ID and collate

- packages/router/src/lib/helpers/metrics.ts
The gas fees during swaps are deducted from the router contracts. However, the `router_gas_balance` metric is currently collecting the balance from the signer address and not the router contract address.
Use the `routerAddress` from context instead, it will fall back to the signer address if not defined in the configuration file.
> [metrics] Fix router_gas_balance metric

- packages/deployments/contracts/contracts/Connext.sol
- packages/deployments/contracts/contracts/interfaces/IConnext.sol
- packages/deployments/contracts/contracts/lib/Connext/ConnextUtils.sol
- packages/deployments/contracts/contracts/nomad-xapps/contracts/relayer-fee-router/RelayerFeeRouter.sol
- packages/deployments/contracts/contracts_forge/Connext.t.sol
- packages/deployments/contracts/contracts_forge/RouterPermissionsManager.t.sol
- packages/deployments/contracts/deploy/02_deployConnext.ts
- packages/deployments/contracts/test/connext.spec.ts
Subtask of #900 
The relayers need a way to initiate the claim for it fees in the destination domain which should be fulfilled in the origin domain by the RelayerFeeRouter
Add `initiateClaim` and `claim` functionalities to Connext
> Add InitiateClaim and Claim functionalities to Connext

- packages/deployments/contracts/contracts/Connext.sol
- packages/deployments/contracts/contracts/interfaces/IConnext.sol
- packages/deployments/contracts/contracts_forge/Connext.t.sol
Subtask of https://github.com/connext/nxtp/issues/900 , built on top of https://github.com/connext/nxtp/pull/955
The ability for user to send along an additional fee to “bump” the transaction
Add a bumpTransfer method to be called on the origin domain
> Add bumpTransfer method

- packages/adapters/cache/src/lib/caches/auctions.ts
- packages/adapters/cache/test/lib/caches/auctions.spec.ts
- packages/agents/router/src/bindings/subgraph/index.ts
- packages/agents/sequencer/src/lib/operations/auctions.ts
- packages/utils/src/mocks/mock.ts
- packages/utils/src/types/api.ts
- packages/utils/src/types/auctions.ts
Router bids are just building up into an endless list on backend bc they're not indexed by router address... it's just adding redundant bids.
Fix to index by router addr. If a router sends in a bid, it replaces the previous one it had set.
> save auction bids indexed by router addr

- packages/deployments/contracts/contracts_forge/ConnextHandler.t.sol
- packages/deployments/contracts/contracts_forge/ForgeHelper.sol
- packages/deployments/contracts/contracts_forge/RouterPermissionsManager.t.sol
- packages/deployments/contracts/contracts_forge/interpreters/Executor.t.sol
- packages/deployments/contracts/contracts_forge/lib/LibCrossDomainProperty.t.sol
- Contract test names were not unique, making it difficult to run one at a time by name
Closes #1021 
Subtask of #822 
- Based of off #960 to allow for unit test fixing without refactoring
- Follow standard test format with contract + function namespacing
> 1021 rename tests

- packages/txservice/src/chainreader.ts
- packages/utils/src/gelato.ts
The Gelato oracle on Optimism was not having into account the GasLimit on L1 to calculate the estimated fee
I added the GasLimit for L1 on the oracle request in the _gelato.ts_ file.  
Moreover I changed the function _calculateGelatoFee()_ in the _chainreader.ts_ at the txservice to accept the pre-calculated gas limit L1 as additional parameter to estimate the gas.
> Fixed Gelato gas estimation on Optimism

- packages/deployments/contracts/contracts/interfaces/IConnextHandler.sol
- packages/deployments/contracts/contracts/interfaces/ISponsorVault.sol
- packages/deployments/contracts/contracts/lib/Connext/ConnextLogic.sol
- packages/deployments/contracts/contracts/nomad-xapps/contracts/connext/ConnextHandler.sol
- packages/deployments/contracts/contracts/test/TestSponsorVault.sol
- packages/deployments/contracts/contracts_forge/ConnextHandler.t.sol
- packages/deployments/contracts/test/connext.spec.ts
subtask of #1060 
ConnextHandler execute logic needs to be integrated with ISponsorVault to be able to sponsor liquidity and relayer fees
Add new logic to handle sponsoring fees
> Sponsoring fee execute logic

- packages/deployments/contracts/contracts/diamond/libraries/AssetLogic.sol
Move AssetLogic library to diamond library and use LibConnextStorage for reading from storage instead of using functions parameters
> Move AssetLogic library to diamond

- packages/deployments/contracts/contracts/diamond/Connext.sol
- packages/deployments/contracts/contracts/diamond/facets/RouterPermissionsManagerFacet.sol
- packages/deployments/contracts/contracts/diamond/libraries/LibConnextStorage.sol
Adds RouterPermissionsManagerFacet which includes the combined logic from the RouterPermissionsManager contract and the RouterPermissionsManagerLogic library.
As part of this refactor into a facet the following changes were included:
- This facet includes the methods `setupRouter` and `removeRouter` which originally were included in the `ConnextHandler` contract
- Converted the methods `onlyRouterOwner` and `onlyProposedRouterOwner` into modifiers since they were acting like that but were declared as methods due to the library restrictions.
- Converted the private variable `_delay` into a constant. I think it makes sense given that it was a variable initialized only once, and for consistency given that we also have a similar constant declared in `ProposedOwnable`
> Move RouterPermissionsManager to diamond facet

- packages/deployments/contracts/contracts/lib/Connext/ConnextLogic.sol
Burning from user after transferring funds to contract when it should be burning from contract
User no longer gets charged 2x for a transfer on non-canonical chains
Fixes
> fix: burn from handler not from user

- packages/agents/backend/poller/src/lib/operations/transfers.ts
Transfer data in the DB and subgraph are out of sync for a prolonged period. poller poll loop not functioning properly.
- [ x] Bug fix (non-breaking change which fixes an issue)
`Connextscan` UI should not be out of sync with subgraphs.
Fixes: https://github.com/connext/nxtp/issues/1280
> 1280 production testnet subgraphs and db are out of sync

- packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol
- packages/deployments/contracts/contracts/core/connext/interfaces/IConnextHandler.sol
- packages/deployments/contracts/contracts_forge/core/connext/facets/RoutersFacet.t.sol
- packages/deployments/contracts/contracts_forge/utils/Deployer.sol
- packages/deployments/contracts/contracts_forge/utils/ForgeHelper.sol
Updates the contracts to allow a router owner to remove liquidity on behalf of a router.
Previously, only `router`s could call `removeLiquidity`. Now the `router` or `routerOwner` has the ability to do that.
Fixes #1292
> 1292 router owner withdraw

- packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
- packages/deployments/contracts/test/connext.spec.ts
`_executeSanityChecks` were not asserting that there should be 0 routers when fast executing. Instead, they were only asserting that *if you were slow executing* there would be no routers.
I'm so sorry alex i didn't make an issue but it's like 2 lines of code forgive me
> stronger assertions on reconciliation for fast liq

- packages/deployments/contracts/contracts_forge/core/connext/helpers/Executor.t.sol
> Executor unit tests

- packages/adapters/subgraph/src/lib/operations/queries.ts
- packages/agents/cartographer/poller/cartographer.config.js
- packages/agents/cartographer/poller/src/adapters/database/client.ts
- packages/agents/cartographer/poller/src/lib/operations/transfers.ts
Fixes execute and reconcile destinations queries from `cartographer`  to use latest state in db and as the starting point for queries to the subgraph.
Fixes 
https://github.com/connext/nxtp/issues/1395
> 1395 fix execute and reconcile destinations queries to subgraph

- packages/adapters/subgraph/src/lib/operations/queries.ts
- packages/adapters/subgraph/src/reader.ts
- packages/agents/cartographer/poller/src/adapters/database/client.ts
- packages/agents/cartographer/poller/src/adapters/database/index.ts
- packages/agents/cartographer/poller/src/lib/operations/transfers.ts
- packages/agents/cartographer/poller/test/adapters/database/client.spec.ts
- packages/agents/cartographer/poller/test/lib/operations/transfers.spec.ts
There is a race condition between the cartographer queries to origin and destination side of the transfer. The end state of the transfer in the DB differs depends on the ordering of these two queries.
Resolve race conditions and allow origin and destination side  updates to DB be idempotent and order independent.
https://github.com/connext/nxtp/issues/1404
Fixes 
https://github.com/connext/nxtp/issues/1404
> 1404 race condition in cartographer subgraph queries

- packages/agents/router/src/bindings/subgraph/index.ts
- packages/agents/router/src/lib/operations/execute.ts
- yarn.lock
We need to convert a domainId from `string` to `number` because if its type is a string, it compares the domainId with the names like `rinkeby`, `goerli`, etc. 
The data structure of nomad domains ===>
```
BridgeContext {
domains: Map(5) {
'goerli' => {
name: 'goerli',
domain: 3331,
...
},
'rinkeby'=>{
name: 'rinkeby',
domain: 1111,
...
},
'kovan'=>{
name: 'kovan',
domain: 2221,
...
},
}
```
reference: @nomad-xyz/multi-provider/src/provider.ts :: resolveDomain()
```
resolveDomain(nameOrDomain: string | number): number {
let domain: Domain | undefined;
if (typeof nameOrDomain === 'number') {
domain = this.registeredDomains.find((d) => d?.domain === nameOrDomain);
} else if (typeof nameOrDomain === 'string') {
domain = this.registeredDomains.find(
(d) => d?.name.toLowerCase() === …
```
> Fix input params for nomad functions

- packages/deployments/subgraph/src/amarok-runtime-staging/mapping.ts
- packages/deployments/subgraph/src/amarok-runtime-v0/mapping.ts
- packages/integration/test/constants.ts
- yarn.lock
> Subgraph `handleExecute` mapping should use amount-after-fees for debiting router

- ops/testnet/staging/core/config.tf
> remove ankr

- packages/agents/lighthouse/src/lib/errors/cartographer.ts
- packages/agents/lighthouse/src/lib/operations/execute.ts
Seeing this error:
Which occurs in the `catch` block in `packages/agents/lighthouse/src/lib/operations/cartographer.ts`.
```ts
} catch (error: any) {
logger.error("Error Cartographer Binding", requestContext, methodContext, jsonifyError(error as NxtpError), {
transaction,
});
}
```
It seems it's likely being thrown here, in `packages/agents/lighthouse/src/lib/operations/relayer.ts`.
```ts
const destinationConnextAddress = config.chains[args.params.destinationDomain].deployments.connext;
```
I guess we're just not checking beforehand that a domain for a given transfer is supported. While all domains *should* be supported in theory, we should still catch this case especially for debugging our staging environment / broken configurations.
Fire off an error, `DomainNotSupported`, if we don't …
> make sure domain is supported as sanity check in execute

- packages/deployments/contracts/package.json
Fixes https://github.com/connext/nxtp/issues/1538.
`artifacts` file in package.json was removed in https://github.com/connext/nxtp/commit/f893f302401fbef12872f02b95eaa14d1138f110.
The fix is to add it back.
Tested by `yarn pack`ing and installing local `nxtp-sdk` and `nxtp-contracts` packages into the bridge-ui. Artifacts get included and unresolved contracts are found.
Fixes 
https://github.com/connext/nxtp/issues/1538
> Re-add artifacts file to nxtp-contracts

- packages/deployments/contracts/contracts/core/connext/facets/BaseConnextFacet.sol
- packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
- packages/deployments/contracts/contracts/core/connext/facets/PortalFacet.sol
- packages/deployments/contracts/contracts/core/connext/interfaces/IConnextHandler.sol
- packages/deployments/contracts/contracts_forge/core/connext/facets/PortalFacet.t.sol
Fixes spear bit issue #26 where portals could be repaid with any supported asset.
- Updates the interface of the `repay*` functions to take in necessary info to generate `transferId`
- `transferId` is calculated onchain, based on canonical token information retrieved by asset
- If the supplied asset is incorrect, then the `transferId` will be generated incorrectly and the `portalDebt` checks would fail
Fixes spearbit #26
> Spearbit 26

- packages/agents/lighthouse/src/config.ts
Right now, the lighthouse never uses a backup relayer because the lighthouse is missing to load relayerUrl when loading config.
Fixes
> Lighthouse Backup Relayer

- packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol
- packages/deployments/contracts/contracts_forge/core/connext/facets/RoutersFacet.t.sol
https://github.com/spearbit-audits/connext/issues/74
> Spearbit-74: delete router's aave portal approval status when removeRouter is called

- packages/deployments/contracts/contracts/core/connext/helpers/LPToken.sol
Fixes https://github.com/spearbit-audits/connext/issues/70
- `LPToken` now only inherits from `ERC20Upgradeable`
- Implement a `burnFrom` function that is  `onlyOwner` callable
Fixes https://github.com/spearbit-audits/connext/issues/70
> Spearbit 70: admin burnable

- packages/deployments/contracts/contracts/core/connext/facets/NomadFacet.sol
- packages/deployments/contracts/contracts/core/connext/interfaces/IBridgeHook.sol
- packages/deployments/contracts/contracts/core/connext/interfaces/IConnextHandler.sol
- packages/deployments/contracts/contracts_forge/Connext.t.sol
- packages/deployments/contracts/contracts_forge/core/connext/facets/NomadFacet.t.sol
- packages/deployments/contracts/contracts_forge/core/connext/facets/SwapAdminFacet.t.sol
- packages/deployments/contracts/contracts_forge/core/connext/libraries/AmplificationUtils.t.sol
- packages/deployments/contracts/contracts_forge/core/connext/libraries/AssetLogic.t.sol
Updates the interface of `onReceive` to include the added `_sender` field. Related to issues mentioned [here](https://github.com/spearbit-audits/connext/issues/82)
Requires #1376 
- Adds a `IBridgeHook` interface that mimics expected Nomad interface
- Makes the `NomadFacet` conform to the `IBridgeHook` interface
- Updates the `onReceive` interface to the latest nomad `BridgeRouter` interface
- Asserts the `_sender` is `Connext` on the origin domain
Fixes issues outlined in spearbit comments: https://github.com/spearbit-audits/connext/issues/82#issuecomment-1196956926
> Add sender check

- packages/agents/cartographer/api/metrics.md
- packages/agents/cartographer/poller/db/migrations/20220730013440_min_outs.sql
- packages/agents/cartographer/poller/db/migrations/20220824094332_metrics_transfer_add_fee_revenue.sql
- packages/agents/cartographer/poller/db/schema.sql
Addition of new metric endpoints: 
- `hourly_transfer_metrics`
- `hourly_transfer_volume`
Transfer schema alteration:
Addition of two columns to transfers, Details: https://github.com/connext/nxtp/issues/1689
- transfer_status_update_by_agent
- transfer_status_message_by_agent
> Addition of new hourly metrics and transfer schema change

- packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol
- packages/deployments/contracts/contracts_forge/core/connext/facets/BridgeFacet.t.sol
- reduce redundant token registry calls
- deduce whether the input asset is a canonical asset, and use this to determine whether we should burn the local asset (i.e. whether it is representative)
> Condense logic for xcall messaging helper(s); reduce excessive delegate calls

- packages/adapters/database/src/client.ts
- packages/adapters/subgraph/.graphclient/index.ts
- packages/adapters/subgraph/.graphclient/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_Test_Goerli/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_Test_Goerli/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_Test_Goerli/types.ts
- packages/adapters/subgraph/src/mockable.ts
- packages/adapters/subgraph/src/reader.ts
- packages/adapters/subgraph/test/reader.spec.ts
- packages/agents/cartographer/poller/src/lib/operations/messages.ts
Two very annoying workarounds in this PR:
- Graph client bypassed for hub subgraph (need @wanglonghong help)
- Transaction wrapper bypassed for processed root messages (need @preethamr help)
> Bypass graph client

- ops/mainnet/prod/core/config.tf
- ops/testnet/prod/core/config.tf
- ops/testnet/staging/core/config.tf
Hot Fix: Reduce seq-sub concurrency to 2
Fixes
> Hot Fix: Reduce seq-sub concurrency to 2

- packages/deployments/contracts/contracts/messaging/connectors/gnosis/GnosisSpokeConnector.sol
- packages/deployments/contracts/contracts/messaging/connectors/multichain/BaseMultichain.sol
- packages/deployments/contracts/contracts/messaging/connectors/optimism/OptimismSpokeConnector.sol
- packages/deployments/contracts/contracts_forge/messaging/connectors/multichain/MutlichainHubConnector.t.sol
Fix https://github.com/spearbit-audits/connext-nxtp/issues/74
Description: The following functions do not validate that the input _data is 32 bytes.
GnosisSpokeConnector._sendMessage
GnosisSpokeConnector._processMessage
BaseMultichain.sendMessage
OptimismSpokeConnector._sendMessage
The input _data contains the outbound Merkle root or aggregated Merkle root, which is always 32 bytes. If the root is not 32 bytes, it is invalid and should be rejected.
Fixes 
https://github.com/spearbit-audits/connext-nxtp/issues/74
> Spearbit 74

- packages/deployments/contracts/contracts/messaging/connectors/SpokeConnector.sol
Fixes: https://github.com/spearbit-audits/connext-nxtp/issues/11
- Replaces `bytes32(uint256(uint160(msg.sender)))` with `addressToBytes32(msg.sender)`
Fixes
> Spearbit 11

- packages/deployments/contracts/deploy/01_deployMessaging.ts
- yarn.lock
The address of the "AMB" on arbitrum will actually be a prefunded EOA that represents the origin sender's alias.
We should set our AMB on the arbi spoke connector to be the hub's alias
Fixes
> Hotfix: for ArbitrumSpokeConnector, deploy with AMB set to ArbitrumHubConnector's alias address

- packages/deployments/contracts/src/cli/init/helpers/types.ts
- packages/deployments/contracts/src/cli/init/init.ts
- yarn.lock
- fixes #2832 by setting `relayerFeeVault` on `init`
- initializes `relayerFeeVault` to deployed relayer proxies
Fixes #2832 
https://github.com/CoinHippo-Labs/connext-bridge/pull/8
> 2832 relayer fee

- packages/agents/relayer/src/bindings/relays/index.ts
Updates relayer to use `txservice` instead of the `signer.sendTransaction(...)`
Fixes #3020 
Updates relayer to use `txservice` instead of the `signer.sendTransaction(...)`
Fixes #3020
> fix: use txservice

- packages/agents/relayer/src/bindings/relays/index.ts
Remove relayer gas estimate, as this causes an error, and is instead already done with in txservice.
Fixes 
https://github.com/connext/monorepo/issues/3074
> Remove relayer gas estimate

- packages/adapters/txservice/src/aggregator.ts
- packages/adapters/txservice/src/config.ts
- packages/adapters/txservice/src/shared/errors.ts
- packages/adapters/txservice/test/aggregator.spec.ts
- packages/agents/watcher/src/config.ts
- packages/deployments/contracts/src/typechain-types/contracts/shared/libraries/index.ts
- packages/deployments/contracts/src/typechain-types/factories/contracts/shared/libraries/index.ts
- packages/deployments/contracts/src/typechain-types/index.ts
Now we can specify a quorum (consensus) must be met in order to validate returned values from providers.
When a quorum is specified, we go from being stringent/economical with our RPC requests to a mode where we consult all available RPC providers and require that at least Q providers agree on a return value for the request, where Q is the configured quorum.
An unconfigured quorum or a quorum value of 1 means we continue using the provider shuffling and only consult 1 provider at a time until we get a response.
Having a quorum is valuable for agents that need maximum accuracy to operate: namely watcher.
> Add config for quorum to RpcProviderAggregator; require quorum is met if specified

- packages/agents/sdk/package.json
- packages/agents/sdk/src/sdkPool.ts
- packages/agents/sdk/src/sdkShared.ts
- packages/agents/sdk/test/sdkPool.spec.ts
- packages/agents/sdk/test/sdkUtils.spec.ts
`calculateSwapPriceImpact` was reading token decimals from contract. Since this data is saved in the pool object already, we don't need this extraneous rpc call.
Fixes
> Sdk decrease rpc calls

- packages/deployments/contracts/contracts/messaging/RootManager.sol
- packages/deployments/contracts/contracts/messaging/connectors/SpokeConnector.sol
- packages/deployments/contracts/contracts/messaging/libraries/SnapshotId.sol
- packages/deployments/contracts/contracts_forge/messaging/PingPong.t.sol
- packages/deployments/contracts/contracts_forge/messaging/ProposeFinalizePropagate.t.sol
- packages/deployments/contracts/contracts_forge/messaging/RootManager.t.sol
- packages/deployments/contracts/contracts_forge/messaging/connectors/SpokeConnector.t.sol
- packages/deployments/contracts/contracts_forge/messaging/libraries/SnapshotId.t.sol
- packages/deployments/contracts/contracts_forge/utils/ForgeHelper.sol
- packages/deployments/contracts/contracts_forge/utils/Mock.sol
Reduce gas consumption on the message layer to a fraction of the current cost by adding to the system the ability to operate in an optimistic mode when desired.
System will have two modes: `Optimistic Mode` and `Slow Mode` (current one).
Optimistic mode is based on an external agent fetching the `inboundRoots` and calculating the new `aggregateRoot` off-chain to propose on the RootManager contract.
The propose will have a dispute time where other off-chain agents will have the chance to verify that the proposed data is correct and dispute it if something is not right.
The way we propagate the aggregateRoots will not change.
- Messages will reach L1 (RootManager) faster and without the need of going through AMBs
-
> feat: optimistic roots smart contracts

- packages/deployments/contracts/contracts/messaging/RootManager.sol
- packages/deployments/contracts/contracts/messaging/connectors/SpokeConnector.sol
- packages/deployments/contracts/contracts/messaging/libraries/SnapshotId.sol
- packages/deployments/contracts/contracts_forge/messaging/RootManager.t.sol
- packages/deployments/contracts/contracts_forge/messaging/connectors/SpokeConnector.t.sol
- Make the SnapshotId library into an internal library
- On RootManager added getter for the SNAPSHOT_DURATION
- On SpokeConnector added getter for the SNAPSHOT_DURATION
> refactor: snapshot id internal lib

- packages/adapters/database/src/client.ts
- packages/agents/cartographer/poller/src/lib/operations/messagestatus.ts
Many reconciled messages have the status `SpokeRootArrivedOnHub`. Under load, limiting the `root_messages` query to 10 means many messages will not find an associated aggregate root.
This is not a sustainable change, but this problem is currently impacting production testnet instances. (see transfer `0x717a71dad3c2948f154fb1f78f29c0ab9d2cd0886faa290ff7ff83d540f62109`)
Fixes
> fix: increase limit when finding associated root messages

- packages/agents/sequencer/src/lib/errors/relayer.ts
- packages/agents/sequencer/src/lib/helpers/relayerfee.ts
- packages/agents/sequencer/test/lib/helpers/relayerfee.spec.ts
- packages/deployments/contracts/src/domain.ts
- packages/utils/src/helpers/hex.ts
- yarn.lock
Uses pricing of canonical asset any time fees are paid in local or adopted. This is because gelato will not support next assets on their API, and have inconsistent asset support across chains (i.e. mainnet DAI is okay, but BSC DAI is not supported).
Currently blocking execution of transfers where users have paid in these assets.
Fixes (hopefully) #4140  / #4152
> Fix next fee estimation

- .github/workflows/build-test-deploy.yml
- build-docker-images.sh
- docker/db/Dockerfile
- ops/mainnet/prod/backend/main.tf
- ops/modules/db/main.tf
- ops/modules/db/outputs.tf
- ops/testnet/prod/backend/main.tf
- packages/adapters/database/README.md
- packages/adapters/database/db/migrations/20230510210620_pg_cron_for_mat_view.sql
- packages/adapters/database/db/schema.sql
- packages/adapters/database/package.json
> 4145 pg cron

- packages/utils/src/helpers/merkle.ts
> Cache completed subtrees

- packages/agents/router/src/tasks/publisher/bindings/server/index.ts
- packages/agents/sequencer/src/bindings/subscriber/auctions/index.ts
- packages/agents/sequencer/src/config.ts
- packages/agents/sequencer/src/lib/entities/config.ts
- packages/agents/sequencer/test/mock.ts
- packages/utils/src/types/api.ts
> Improve logging and refactor

- packages/adapters/cache/src/lib/caches/transfers.ts
- packages/agents/router/src/tasks/publisher/operations/retryXCalls.ts
- packages/agents/router/test/publisher/operations/retryXCalls.spec.ts
> Paginate reading pending txs from the redis cache

- README.md
- ops/modules/db/main.tf
- packages/agents/sequencer/src/config.ts
> fix: resolve testnet prod sync conflicts

- packages/agents/sequencer/src/lib/operations/execute/fastpath.ts
- packages/agents/sequencer/src/lib/operations/execute/slowpath.ts
* fix: wait until none
* fix: slowpath cache issue
Fixes
> fix: resolve the duplication issue in the seq cache

- packages/adapters/database/src/client.ts
- packages/utils/src/helpers/merkle.ts
> feat: reenable cache

- packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
Adding Xocolatl MXN Stablecoin $XOC, to the production allow-listed script.
This pull request adds the representations by domain of Xocolatl MXN Stablecoin. 
Connext address currently has mint/burn auth in Polygon(POS), Gnosis, and BSC.
Representations were added to `MAINNET_PRODUCTION_INIT_CONFIG` object in the array of `assets` to file ~/packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
N/A
[chaindata repo pull request 75](https://github.com/connext/chaindata/pull/75)
> Add ladao-xocolatl to prod allow-listing

- packages/deployments/contracts/contracts/messaging/connectors/zksync/ZkSyncHubConnector.sol
- packages/deployments/contracts/contracts_forge/messaging/connectors/zksync/ZkSyncHubConnector.t.sol
Fixes m6 + l6 https://www.notion.so/0xmacro/Connext-2-Preliminary-Audit-Report-external-private-a5e5ad6fb49141f29b8283dfbeb50a18#63a65a2c3ba249f1b7d9ca7060905892
Fixes
> Macro m6 + l6

- packages/deployments/contracts/contracts/messaging/connectors/wormhole/BaseWormhole.sol
- packages/deployments/contracts/contracts_forge/messaging/connectors/wormhole/WormholeHubConnector.t.sol
- packages/deployments/contracts/contracts_forge/messaging/connectors/wormhole/WormholeSpokeConnector.t.sol
> fix: capping gasLimit in the `quoteEvmDeliveryPrice`

- packages/agents/sdk/src/interfaces/index.ts
- packages/agents/sdk/src/sdkUtils.ts
> feat: add ability to search by execute and reconcile hash

- packages/adapters/cache/package.json
- packages/adapters/database/package.json
- packages/adapters/relayer/package.json
- packages/adapters/subgraph/package.json
- packages/adapters/txservice/package.json
- packages/adapters/watcher/package.json
- packages/adapters/web3signer/package.json
- packages/agents/cartographer/poller/package.json
- packages/agents/chain-abstraction/CHANGELOG.md
- packages/agents/chain-abstraction/package.json
- packages/agents/lighthouse/package.json
- packages/agents/relayer/package.json
- packages/agents/router/package.json
- packages/agents/sdk-wrapper/CHANGELOG.md
- packages/agents/sdk-wrapper/package.json
- packages/agents/sdk/CHANGELOG.md
- packages/agents/sdk/package.json
- packages/agents/sequencer/package.json
- packages/agents/watcher/package.json
- packages/deployments/contracts/package.json
- packages/deployments/subgraph/package.json
- packages/integration/package.json
- packages/utils/package.json
> build: bump sdk-core

- packages/agents/sdk-wrapper/CHANGELOG.md
- packages/agents/sdk-wrapper/package.json
- packages/agents/sdk-wrapper/src/sdkPool.ts
- packages/agents/sdk-wrapper/src/sdkShared.ts
- packages/agents/sdk-wrapper/test/sdkPool.spec.ts
- packages/agents/sdk-wrapper/test/sdkShared.spec.ts
- packages/agents/sdk/CHANGELOG.md
- packages/agents/sdk/package.json
- packages/agents/sdk/src/interfaces/index.ts
- packages/agents/sdk/src/sdkPool.ts
- packages/agents/sdk/src/sdkShared.ts
- packages/agents/sdk/test/sdkShared.spec.ts
- packages/examples/sdk-server/src/routes/shared.ts
> fix: provider passing in options

- packages/adapters/cache/src/lib/caches/auctions.ts
- packages/adapters/cache/test/lib/caches/auctions.spec.ts
- packages/adapters/subgraph/src/lib/operations/queries.ts
- packages/agents/sequencer/src/bindings/server/index.ts
- packages/agents/sequencer/test/bindings/server/server/index.spec.ts
- packages/agents/sequencer/test/lib/operations/execute/fastpath.spec.ts
> fix: prune auction cache properly

- packages/agents/router/src/tasks/publisher/operations/getXCalls.ts
- packages/agents/router/test/publisher/operations/getXCalls.spec.ts
> fix: unit test on testnet prod

- ops/mainnet/prod/core/main.tf
- ops/testnet/prod/core/main.tf
When we have a large backlog in Connext Relayer, in cases where gelato send fails,  it could run out of cache memory.
Solution: Upgrade to a larger instance.
This makes Connext Relayer less likely to run out of memory.
> Upsize relayer instance type pre-scale sequencer and LH

- packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
> feat: add xALCX

- packages/agents/sdk/CHANGELOG.md
- packages/agents/sdk/package.json
- yarn.lock
> sdk-v2.1.3-alpha.2

- packages/adapters/database/test/mock.ts
- packages/agents/lighthouse/.nycrc.json
- packages/agents/lighthouse/src/tasks/propose/operations/propose.ts
- packages/agents/lighthouse/test/globalTestHook.ts
- packages/agents/lighthouse/test/mock.ts
- packages/agents/lighthouse/test/tasks/propose/operations/propose.spec.ts
- packages/agents/watcher/test/mock.ts
- packages/agents/watcher/test/operations/validateAndSwitch.spec.ts
> fix: 4945 unit test coverage checks staging

- packages/agents/lighthouse/src/tasks/prover/operations/process.ts
- packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts
- packages/agents/lighthouse/src/tasks/prover/operations/types.ts
- packages/agents/lighthouse/test/mock.ts
- packages/agents/lighthouse/test/tasks/prover/operations/process.spec.ts
- packages/agents/lighthouse/test/tasks/prover/operations/publisher.spec.ts
> Prover op mode fixes

- packages/agents/lighthouse/src/tasks/propose/operations/propose.ts
- packages/agents/lighthouse/src/tasks/prover/operations/publisher.ts
- packages/utils/src/constants/index.ts
- packages/utils/src/constants/lighthouse.ts
> Fix LH prover

- packages/adapters/database/src/client.ts
- packages/adapters/database/src/index.ts
- packages/adapters/database/test/client.spec.ts
- packages/adapters/database/test/mock.ts
- packages/agents/lighthouse/src/errors/prover.ts
- packages/agents/lighthouse/src/tasks/propose/errors.ts
- packages/agents/lighthouse/src/tasks/propose/operations/propose.ts
- packages/agents/lighthouse/src/tasks/propose/operations/proposeSpoke.ts
- packages/agents/lighthouse/test/tasks/propose/operations/propose.spec.ts
- packages/agents/lighthouse/test/tasks/propose/operations/proposeSpoke.spec.ts
> feat: dedup the aggregated root in propose

- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/xERC20.md
- packages/agents/lighthouse/src/tasks/processFromRoot/processFromRoot.ts
- packages/agents/lighthouse/src/tasks/propagate/propagate.ts
- packages/agents/lighthouse/src/tasks/prover/prover.ts
- packages/agents/lighthouse/src/tasks/sendOutboundRoot/sendOutboundRoot.ts
> Testnet prod sync

- ops/testnet/prod/core/main.tf
> fix: increase lh mem

- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/xERC20.md
- ops/testnet/prod/core/main.tf
- packages/agents/lighthouse/src/tasks/processFromRoot/processFromRoot.ts
- packages/agents/lighthouse/src/tasks/propagate/propagate.ts
- packages/agents/lighthouse/src/tasks/prover/prover.ts
- packages/agents/lighthouse/src/tasks/sendOutboundRoot/sendOutboundRoot.ts
> testnet-prod sync

- packages/adapters/database/src/client.ts
- packages/adapters/database/test/client.spec.ts
> fix: change aggregate root queries

- packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
Added `IXT` token for whitelisting
Chains supported: 
- Polygon (Homechain)
- BSC
- ETH Mainnet
- Arbitrum one
Fixes #5072
> feat: added IXT token

- packages/agents/router/src/errors/execute.ts
- packages/agents/router/src/setup.ts
Handle MQ connection error events gracefully.
Resolves:
https://discord.com/channels/992549151134982234/1168903324427374632/1168903435551264809
> Handle MQ connection error events

- packages/adapters/cache/src/lib/caches/messages.ts
- packages/adapters/cache/test/lib/caches/messages.spec.ts
- packages/agents/lighthouse/src/errors/prover.ts
- packages/agents/lighthouse/src/tasks/prover/operations/consumer.ts
- packages/agents/lighthouse/src/tasks/prover/operations/process.ts
- packages/agents/lighthouse/test/mock.ts
- packages/agents/lighthouse/test/tasks/prover/operations/process.spec.ts
> fix: retry issue on prod

- packages/deployments/contracts/src/cli/helpers.ts
- packages/deployments/contracts/src/cli/init/config/testnet/staging.ts
- packages/deployments/contracts/src/cli/init/init.ts
> 5187 whitelist watcher

- packages/agents/router/src/tasks/executor/operations/execute.ts
- packages/agents/router/test/executor/operations/execute.spec.ts
> fix: handle unsupported error in router executer

- packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumGoerli/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumGoerli/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumGoerli/types.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumOne/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumOne/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_ArbitrumOne/types.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_Goerli/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_Goerli/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_Goerli/types.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_LocalArbitrumOne/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_LocalArbitrumOne/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_LocalArbitrumOne/types.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_LocalMainnet/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_LocalMainnet/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_LocalMainnet/types.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_LocalOptimism/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_LocalOptimism/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_LocalOptimism/types.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_Mainnet/types.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_Mumbai/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_Mumbai/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_Mumbai/types.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_OptimismGoerli/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Connext_OptimismGoerli/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Connext_OptimismGoerli/types.ts
- packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/introspectionSchema.ts
- packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/schema.graphql
- packages/adapters/subgraph/.graphclient/sources/Hub_LocalMainnet/types.ts
> fix: rebuild graphclient for missing entity

- ops/mainnet/prod/backend/config.tf
- packages/agents/sdk-wrapper/CHANGELOG.md
- packages/agents/sdk-wrapper/package.json
- packages/agents/sdk-wrapper/src/config.ts
- packages/agents/sdk/CHANGELOG.md
- packages/agents/sdk/package.json
- packages/agents/sdk/src/config.ts
- packages/agents/sdk/src/sdkShared.ts
- packages/agents/sdk/test/sdkShared.spec.ts
> Sdk supported assets filter

- packages/agents/lighthouse/src/tasks/propose/errors.ts
- packages/agents/lighthouse/src/tasks/propose/operations/proposeHub.ts
- packages/agents/lighthouse/src/tasks/propose/propose.ts
fix: add safe guard to lh to not propose when subgraph stale
- [] Configuration / tooling changes
Fixes
> fix: add safe guard to lh to not propose when subgraph stale

- ops/mainnet/prod/core/main.tf
Increase lh prover frequency to once an hour, to reduce messaging opex.
Fixes
> fix: increase lh prover frequncy to once an hour reduce opex

- ops/mainnet/prod/backend/main.tf
> feat: increase max instances

- ops/testnet/staging/backend/config.tf
- ops/testnet/staging/core/config.tf
- ops/testnet/staging/core/main.tf
- ops/testnet/staging/core/outputs.tf
> Fix staging tf

- packages/adapters/database/src/client.ts
- packages/adapters/database/test/client.spec.ts
- packages/agents/cartographer/poller/src/lib/operations/transfers.ts
- Resets the `error_status` along with backoff and execution timeouts
TLDR:
- transfer error statuses are not always updated dynamically, they update according to an exponential backoff
- this could cause stale errors, particularly around relayer fees and slippage which are moment-in-time evaluation
- slippage / relayer fee changes reset the backoff, but not always the error which leaves the error handling to be offloaded onto the client, and is not indicative of the error on the latest transfer params
- there could be other issues around the errors being stale, which we will have to resolve manually, but resetting the errors on increase will help as well
Considered making a separate database function or flag, but `resetBackoffs` is only ever used in the case new slippage or relayer fee …
> 5877 reset errors

- packages/agents/sdk/src/sdkBase.ts
- packages/agents/sdk/test/sdkBase.spec.ts
- packages/utils/src/mocks/mock.ts
- packages/utils/src/peripherals/chainData.ts
- packages/utils/src/peripherals/relayer.ts
- packages/utils/test/peripherals/relayer.spec.ts
Closes #5996 
- Moves max enforcement logic to shared utilities, not just `sdkBase`
- Updates the utils to ensure the prices are denominated in WETH
Fixes
> fix: move max enforcement to utils

- ops/modules/lambda/main.tf
> fix: add max 1 concurrency limit on all lambda functions

- packages/agents/chain-abstraction/test/libs/shared/quote.spec.ts
- packages/agents/lighthouse/package.json
- packages/agents/lighthouse/src/tasks/processFromRoot/helpers/linea.ts
- packages/agents/lighthouse/src/tasks/propagate/helpers/linea.ts
- packages/deployments/contracts/package.json
- packages/deployments/contracts/tasks/connector/claimLinea.ts
- packages/utils/package.json
- yarn.lock
- Update sdk
- Fix local claiming
Fixes
> Fix: linea pmfr

- ops/mainnet/prod/core/main.tf
- ops/mainnet/prod/core/outputs.tf
Need to stop dao router from bidding/boosting transfers.
Fixes
> fix: disable internal router from bidding
